### ISSUE TITLE
Incorrect dragged element position when window scrolled

### ISSUE THREAD

**Issue by dsvgit** [clauderic/react-sortable-hoc#101]
To reproduce:
1. select element
2. scroll window (by scroll wheel or keyboard)
3. try to move element
result: other elements moves like if you didn't scroll
screens to reproduce:
http://joxi.ru/L210W96F8RvW0m -> http://joxi.ru/krDOqLzcEKw3QA -> http://joxi.ru/Dr863dRF4ody62

**Comment by dsvgit** [comment]
To addition, lockToContainerEdges doesn't work if you scroll window

**Comment by uditalias** [comment]
+1

**Comment by dsvgit** [comment]
@uditalias I use Alt. Usually components that use SortableContainer or Element are wrapped in @connectToStores

**Comment by kohlmannj** [comment]
For what it's worth: I'm seeing something similar with a Redux-wrapped component using react-sortable-hoc. Can try to provide more details if you're interested.

**Comment by dsvgit** [comment]
you can reproduce it here https://clauderic.github.io/react-sortable-hoc/#/basic-configuration/basic-usage?_k=62gk8p

**Comment by Ghostavio** [comment]
I'm having the same issue.

**Comment by charlierudolph** [comment]
Also just ran into this. @clauderic I'm willing to help out on this. Any guidance you could give on how we would need to approach solving this?

**Comment by charlierudolph** [comment]
@dsvgit @uditalias @kohlmannj @Ghostavio 

Got this working using the `getContainer` prop (alternatively use the `useWindowAsScrollContainer` prop) to connect it to the proper scroll container and it works exactly as it does in the demo.
