### ISSUE TITLE
Sortable <tr>?

### ISSUE THREAD

**Issue by edamron** [clauderic/react-sortable-hoc#107]
Can I use react-sortable-hoc to make rows of a table draggable?  I'm currently .map(ing) over an array, and I'd like to use a font-awesome 'hamburger' icon in the first column / td of the table as the drag handle / SortableHandle.

Possible?

So far, without success, I've tried passing "useDragHandle={true}" to my SortableContainer, using an <td><i/></td> element inside my SortableHandle, and ensuring I'm providing an index prop on my SortableHandle.

Must I use an unordered list?

Thanks very much!

**Comment by edamron** [comment]
You may ignore this question.  It wasn't very difficult for me to change my code over to using a <ul> vs. a table.

Thanks

**Comment by nbkhope** [comment]
@edamron how did you do it? I'm trying to make the rows of a table sortable

**Comment by edamron** [comment]
I abandoned the use of tables and went with a simple unordered list.

**Comment by joshkadis** [comment]
@nbkhope Exact same problem, did you figure it out?

**Comment by edamron** [comment]
Nope...restructured my page to go with a simple <ul>

**Comment by joshkadis** [comment]
Yup, saw that. Was wondering if the other interested party had found a solution. Thanks! 😄

**Comment by nbkhope** [comment]
@joshkadis I couldn't figure it out.

**Comment by codyduval** [comment]
For others looking to sort a table: 

You'll need to add a `helperClass` on your sortable list that adds the css styles that get dropped when the the `tr` is in "drag" mode and is no longer a child of a `table`.  (example: `helperClass='sortableHelper'`).  That helperClass should reference a css class where you can add in the missing styles, in my case, just adding a `display: table !important` did the trick.

**Comment by d30jeff** [comment]
I've tried @codyduval 's solution. However the rows position are off when `drag` is active.

Is that an expected behavior?

FWIW, I'm using `bootstrap` css.
