### ISSUE TITLE
Scrolling over sortable elements doesn't work on Phones and Tablets on examples

### ISSUE THREAD

**Issue by Rask777** [clauderic/react-sortable-hoc#109]
I think this is not device specific issue, but here is a list of devices I used for testing:
- Iphone 6S 
- Nexus 6P  
- Ipad 4 6.0
Tested on provided examples.
1 Go to http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/basic-usage
2 Scroll the list
Actual result:
It drags and moves an item but doesn't scroll the list

Maybe it's by design since the Activate onPress (200ms) works as expected.

**Comment by clauderic** [comment]
@Rask777 it works fine for me, just make sure you scroll the actual browser window down a little, as the list overflows a little on smaller screens. Tested on iOS safari/chrome and Android chrome

**Comment by edwardfhsiao** [comment]
well, maybe it's the ios version problem? it does not work well for me on ios11 safari and chrome
https://github.com/clauderic/react-sortable-hoc/issues/304

**Comment by edwardfhsiao** [comment]
#304
