### ISSUE TITLE
Replace `_.omit` with a vanilla method (perf, size, future proofing)

### ISSUE THREAD

**Issue by levithomason** [clauderic/react-sortable-hoc#114]
Reference: https://github.com/Semantic-Org/Semantic-UI-React/issues/864

### Speed
In some recent benchmarks over at Semantic-UI-React, the `_.omit` method has proven to be _extremely_ slow.  I achieved **>12,000 times performance gain with a 4 line vanilla replacement**.

### Size
Even with cherry-picking, the `_.omit` method requires many dependencies, totaling 96 modules, 3,172 lines, and ~84kb (unminified).  This will be bundled by users consuming `react-sortable-hoc` whether or not they are using lodash.

### It will be dropped in v5

[Per the author](https://github.com/Semantic-Org/Semantic-UI-React/issues/864#issuecomment-261152847), `_.omit` will be dropped in v5 due to some design concerns.

**Comment by clauderic** [comment]
Hey @levithomason,

Thanks for the detailed explanation as to the motives of your request. If you're feeling up for it, I'd be more than happy to review a PR to that effect.

**Comment by levithomason** [comment]
Sure, looks like there are only two basic usages. I'll throw something together soon as I am able.

**Comment by levithomason** [comment]
PR up #115
