### ISSUE TITLE
UMD build broken in IE

### ISSUE THREAD

**Issue by arackaf** [clauderic/react-sortable-hoc#116]
It looks like the UMD build is broken in IE :(

![image](https://cloud.githubusercontent.com/assets/11261266/21772927/d639f458-d652-11e6-9b17-322edb56274e.png)

I'm not sure what else I can add besides that screenshot, but if there's anything else I can add, please don't hesitate.

I wish I could be of more help on this

**Comment by clauderic** [comment]
Hey @arackaf, haven't forgotten about this! I just got a new laptop and am still in the process of setting everything back up.

I'll try to do some digging on my end as soon as I get my VMs set up and running, which will hopefully help me pinpoint the issue. In the meantime, let me know if you find anything on your end!

**Comment by arackaf** [comment]
Outstanding - glad to hear it.  Appreciate all you do! :)

**Comment by Sridatta7** [comment]
Hi @clauderic,

I was just wondering if there is any update on this.
