### ISSUE TITLE
"Value" field not included on SortableElementProps TypeDefinition

### ISSUE THREAD

**Issue by andrewdewaal** [clauderic/react-sortable-hoc#117]
This does not allow us to create a SortableElement from typescript with the needed "value" property in the TSX file.

**Comment by clauderic** [comment]
Hey @andrewdewaal, would you mind providing more details / an example of what you mean?

**Comment by felipe-vicente** [comment]
Having the same problem. I was trying to create a component using SortableElement HOC (that injects SortableElementProps in the component).

```javascript
interface Props extends SortableElementProps {
  className: string
  // value: string
}

const SortListItem = (props: Props) => {
  const { value, className } = props

  return (
    <ListItem className={props.className}>
      <DragHandle />
      <ListItemText primary={props.value} />
    </ListItem>
  )
}

export default SortableElement(SortListItem)
```

but the `value` prop is not defined on the interface

```javascript
export interface SortableElementProps {
  index: number;
  collection?: Offset;
  disabled?: boolean;
}
```

had to add a value inside my own props, wich is a "not cool turnaround"...

**Comment by rodrigo-fonseca** [comment]
> Having the same problem. I was trying to create a component using SortableElement HOC (that injects SortableElementProps in the component).
> 
> ```js
> interface Props extends SortableElementProps {
>   className: string
>   // value: string
> }
> 
> const SortListItem = (props: Props) => {
>   const { value, className } = props
> 
>   return (
>     <ListItem className={props.className}>
>       <DragHandle />
>       <ListItemText primary={props.value} />
>     </ListItem>
>   )
> }
> 
> export default SortableElement(SortListItem)
> ```
> 
> but the `value` prop is not defined on the interface
> 
> ```js
> export interface SortableElementProps {
>   index: number;
>   collection?: Offset;
>   disabled?: boolean;
> }
> ```
> 
> had to add a value inside my own props, wich is a "not cool turnaround"...

I had the same issue, I solve it by doing this:

```

interface SortableItemProps extends SortableElementProps {
  value: string;
}

const SortableItem = SortableElement<SortableItemProps>(
  ({ value }: SortableItemProps) => {
    return (
      <IonItemStyled lines="none">
        {value}

        <div slot="end">
          <FontAwesomeIcon icon="arrows-alt-v" />
        </div>
      </IonItemStyled>
    );
  }
);
```
