### ISSUE TITLE
Link inside of SortableElement breaks sort in FF

### ISSUE THREAD

**Issue by Moerphy** [clauderic/react-sortable-hoc#118]
Testcase: https://jsfiddle.net/tz2daph1/1/
When clicking on the list item it works correctly, when clicking the link itself it only moves a short distance with the mouse, then stops moving until mouseup. And then it follows the mouse again like it would normally until the next mouseup event.

This only happens in Firefox 50 for me, works in all other major browsers.

**Comment by Moerphy** [comment]
Thanks for the fast fix! Seems like the bug still happens if the SortableContainer is using the distance property. I think moving the fix to handleStart instead of handlePress should fix that too.

https://jsfiddle.net/tz2daph1/2/

**Comment by clauderic** [comment]
Riiiiiight! Will fix shortly, sorry about that!

**Comment by clauderic** [comment]
Just pushed a fix to npm with `0.4.7`, give it a spin and let me know if all is well!

**Comment by Moerphy** [comment]
Thanks, looks like it works perfectly now!
