### ISSUE TITLE
Drag&Drop between sortable containers

### ISSUE THREAD

**Issue by philtrep** [clauderic/react-sortable-hoc#119]
A nice feature for this component would be the ability to drag&drop SortableElements between multiple SortableContainers.

**Example:**
Initial State
```
Container A [Elem1, Elem2, Elem3] 
Container B [Elem4, Elem5]
```
Move `Elem1` from `Container A` to `Container B`
```
Container A [Elem2, Elem3] 
Container B [Elem4, Elem1, Elem5]
```

**Comment by clauderic** [comment]
I agree! This is definitely something that's planned in the future, but I don't currently have the bandwidth to make it happen. If you have any ideas regarding implementation, feel free to join in the conversation in #3.

Closing this as it is a duplicate of #3.
