### ISSUE TITLE
Basic styles?

### ISSUE THREAD

**Issue by webular** [clauderic/react-sortable-hoc#12]
Nice library.  Loving it.

It would be nice if you could include in the repo some basic styles to give developers (especially those not good at making things look great) a starting point to then further customize.

**Comment by clauderic** [comment]
The thing is, since this is a HOC, your components don't get wrapped by a new component, they're simply enhanced, therefore there isn't a `className` to attach some basic styles to. Feel free to inspect the basic styles of the demo and copy paste them if you like. It's really nothing fancy.
