### ISSUE TITLE
msTransform doesn't work in IE9

### ISSUE THREAD

**Issue by sergey-erkin** [clauderic/react-sortable-hoc#121]
Drag and drop doesn't work in IE9

IMO there is a mistake in utils.js
export const vendorPrefix = (function () {
   ...
    switch (pre) {
        case 'ms':
            **return 'ms';**
        default:
            return (pre && pre.length) ? pre[0].toUpperCase() + pre.substr(1) : '';
    }

In case of IE9 vendorPrefix() has to return 'Ms' due IE9 works with "-ms-transform".

**Comment by SMenigat** [comment]
Could you open a PR for this?

**Comment by Robinfr** [comment]
I've created a PR for this. If what was said is true, this should work (I don't have IE9 to test it on).
