### ISSUE TITLE
Select in SortableItem doesn't have value if is draggable

### ISSUE THREAD

**Issue by tomasztomys** [clauderic/react-sortable-hoc#122]
If you drag an item with select, the value of select set to value of first item's select and return to itself value after drop. But text on the left of select is correct.

![image](https://cloud.githubusercontent.com/assets/7750691/22104907/c05cc772-de41-11e6-93ab-c98eb5d79bc2.png)

https://jsfiddle.net/60848oue/

**Comment by clauderic** [comment]
Hey @tomasztomys, this was fixed by #123 and shipped in `0.4.8` 🎉  Thanks for reporting this!
