### ISSUE TITLE
Integration with Bootstrap grid system

### ISSUE THREAD

**Issue by eliseumds** [clauderic/react-sortable-hoc#124]
Hey everyone,

First of all, congratulations on the nice library :)

I'd like to know whether it's possible to make it work with an arbitrary number of rows when we use Bootstrap grids, for example. In my example, it only works with a single row:

![uploader2](https://cloud.githubusercontent.com/assets/640840/22134975/4ffa1a82-df1f-11e6-8258-d14fa9770f7a.gif)

Actually, it's the same behaviour as RubaXa/Sortable's *List B* and *Multi* examples: https://rubaxa.github.io/Sortable/

**Comment by clauderic** [comment]
Hey @eliseumds! 

As long as your elements are of equal width and height, you'll be able to enable grid sorting by passing a value of 'xy' to the ˋaxis` prop of your enhanced SortableContainer component.

**Comment by eliseumds** [comment]
Of course, it was in the docs :S Thanks @clauderic!

**Comment by eliseumds** [comment]
Oh, it worked so well! I had an outdated version installed lol

![uploader3](https://cloud.githubusercontent.com/assets/640840/22151240/60352b38-df71-11e6-8232-64fb6447550e.gif)

How beautiful is it? :)
