### ISSUE TITLE
Item being dragged disappears when the sortable-list is inside a bootstrap modal.

### ISSUE THREAD

**Issue by David-Neto** [clauderic/react-sortable-hoc#126]
When a list is placed inside a bootstrap modal and an element gets dragged, it disappears temporarily until it's released/dropped. The functionality works as expected with the changes to the sort order performing as normal, just the visual effect of the element being dragged seems to be missing in this situation.

In the test I performed I was using a handle, both the item and the handle disappear.

My gut tells me it might be related to css z-index property interfering, but this is merely a guess.

Cheers.

**Comment by clauderic** [comment]
Hey @David-Neto, it is indeed a z-index issue. See https://github.com/clauderic/react-sortable-hoc/issues/87
