### ISSUE TITLE
Item disappearing when dragging

### ISSUE THREAD

**Issue by jeffbonasso** [clauderic/react-sortable-hoc#129]
I am trying to use where my sortable list is in a modal. I tried react-bootstrap modal and react-modal-dialog libraries and with both my item disappears when dragging. You mention in your readme about potential of item disappearing. Is there an easy solution if this occurs?

**Comment by clauderic** [comment]
Hey @jeffbonasso, this is a duplicate of https://github.com/clauderic/react-sortable-hoc/issues/87.

Short answer: It's a z-index issue

**Comment by jeffbonasso** [comment]
Awesome. Set a higher z-index on SortableElement and worked like a charm. Thanks!
