### ISSUE TITLE
Exported as InfiniteCalendar in the UMD build

### ISSUE THREAD

**Issue by davidmurdoch** [clauderic/react-sortable-hoc#13]
See https://github.com/clauderic/react-sortable-hoc/commit/f5cee9f06aebbfdfcbf861ef2f913bb377004306#diff-780cbc3a123afd2a22df8818a1db3d08R30

**Comment by clauderic** [comment]
Derp. The dangers of copy pasting... Thanks for catching this

**Comment by clauderic** [comment]
Fixed in `0.0.2` release
