### ISSUE TITLE
[Question] is it possible to work with this.children in stead of wrapping?

### ISSUE THREAD

**Issue by nealoke** [clauderic/react-sortable-hoc#132]
Hi, i'm wondering if you can also use the sortable in the following way in stead of wrapping.

```
<SortableList onSortEnd={this.handleSort} useDragHandle={true}>
	{array.map((value) => {
		return (
			<SortableElement>
				<SortableHandle>::</SortableHandle>
				{value}
			</SortableElement>
		);
	})}
</SortableList>
```

**Comment by clauderic** [comment]
Hey @nealoke,

Absolutely! If you'd prefer to use that kind of syntax, you can probably create those yourself by doing something along the lines of:

```js
import {sortableContainer, sortableElement, sortableHandle} form 'react-sortable-hoc';

const wrapper = (props) => <div {...props}>{props.children}</div>;
const SortableList = sortableContainer(wrapper);
const SortableElement = sortableElement(wrapper);
const SortableHandle = sortableHandle(wrapper);
```

**Comment by nealoke** [comment]
@clauderic thank you for this! I do get 1 error using the suggested wrapper though. See below

![image](https://cloud.githubusercontent.com/assets/17417414/22865335/127859bc-f162-11e6-90a3-3cecb3aaa08f.png)

**Comment by clauderic** [comment]
Right! Looks like it's not being properly omitted. I'll issue a fix for that shortly, though in the meantime, to get around this, you can exclude it yourself by doing something along the lines of:

```js
import {sortableContainer, sortableElement, sortableHandle} form 'react-sortable-hoc';

const wrapper = ({getHelperDimensions, ...props}) => <div {...props}>{props.children}</div>;
const SortableList = sortableContainer(wrapper);
const SortableElement = sortableElement(wrapper);
const SortableHandle = sortableHandle(wrapper);
```

**Comment by clauderic** [comment]
Just published `0.5.0` with this fixed!

**Comment by nealoke** [comment]
@clauderic where can i get this 0.5.0? :) it's not on releases here no gitbhub

**Comment by nealoke** [comment]
@clauderic Yes this fixed it 👍 Thank you very much!
