### ISSUE TITLE
getContainer() cannot be a parent component

### ISSUE THREAD

**Issue by jeanblanchard** [clauderic/react-sortable-hoc#135]
I wanted to use `getContainer()` in the `SortableContainer` HOC to set the scroll container to a parent component.

Unfortunately the `getContainer()` is called in `SortableContainer.componentDidMount()`, when the parent component is not yet mounted, so it returns undefined, and crashes.

Suggestion: allow specifying the `container` and `scrollContainer` separately in `SortableContainer` (adding a `getScollContainer()` function property would make the most sense; it would actually match the internal representation). Then lazily call `getScrollContainer()` when needed.

---

More information: basically the use case is the same as with `useWindowAsScrollContainer`, but where only part of the page scrolls.

**Comment by clauderic** [comment]
Hey @jeanblanchard,

I haven't tried reproducing this yet, but I believe you're right! Really hadn't thought of that edge-case when we implemented that feature.

If you'd like to contribute to this repo, I'd be happy to review a PR to solve this! 😄

**Comment by alex-vg** [comment]
@clauderic I need this feature too, could you merge the PR?

**Comment by aurels** [comment]
@alex-vg Hi, would you give me an example showing how you put a value into `this.props.scrollContainer` ?

**Comment by alex-vg** [comment]
```
  componentDidMount() {
    this.domNode = ReactDOM.findDOMNode(this);
  }

  getContainer = () => this.props.scrollContainer || this.domNode;

render() {
    return (
            <CustomSortableContainer
              ...
              getContainer={this.getContainer}
            />
```
Since I wanted to be able to set the container from the outside of the component, I added `this.props.scrollContainer ||`.

**Comment by aurels** [comment]
Thanks !

**Comment by clauderic** [comment]
Just to follow-up on this issue, the `getContainer` prop now accepts passing it a Promise that returns the container from a parent component

**Comment by lbhbrave** [comment]
> Just to follow-up on this issue, the `getContainer` prop now accepts passing it a Promise that returns the container from a parent component

Would you mind give me a example how to use Promise to getContainer. I get the same problem as below and look for a solution. Thx very much

**Comment by NexxLuo** [comment]
The following code will report a error 'Cannot read property 'ownerDocument' of null'


`import React, { Component } from "react";
import { render } from "react-dom";
import { SortableContainer, SortableElement } from "react-sortable-hoc";
import arrayMove from "array-move";
import AutoSizer from "react-virtualized-auto-sizer";

const SortableListContainer = ({ children }) => {
  return (
    <AutoSizer>
      {({ height, width }) => {
        return <div style={{ height: height, width: width }}>{children}</div>;
      }}
    </AutoSizer>
  );
};

const SortableItem = SortableElement(({ value }) => <div>{value}</div>);

const SortableList = SortableContainer(({ items }) => {
  return (
    <SortableListContainer>
      <div style={{ width: "100%", height: "100%" }} id="container">
        {items.map((value, index) => (
          <SortableItem key={`item-${index}`} index={index} value={value} />
        ))}
      </div>
    </SortableListContainer>
  );
});

class SortableComponent extends Component {
  state = {
    items: ["Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6"]
  };
  onSortEnd = ({ oldIndex, newIndex }) => {
    this.setState(({ items }) => ({
      items: arrayMove(items, oldIndex, newIndex)
    }));
  };

  getContainer = () => {
    return document.getElementById("container");
  };

  render() {
    return (
      <div style={{ height: 400, width: 600 }}>
        <SortableList
          items={this.state.items}
          getContainer={this.getContainer}
          onSortEnd={this.onSortEnd}
        />
      </div>
    );
  }
}

render(<SortableComponent />, document.getElementById("root"));`
