### ISSUE TITLE
Buttons not supported for shouldCancelStart

### ISSUE THREAD

**Issue by joelworsham** [clauderic/react-sortable-hoc#136]
It would be nice if the tag `button` was also in the default list. Of course, I can add my own function to modify this, but it just seems like `<button>`s would be expected for this behavior.

https://github.com/clauderic/react-sortable-hoc/blob/master/src/SortableContainer/index.js#L40

**Comment by clauderic** [comment]
Hey @joelworsham, that's a good observation, thanks for pointing that out. If you have time, is this something you'd like to submit a PR for? I'd be happy to review if so 😄

**Comment by Robinfr** [comment]
Made PR for you since I like this library. :smile:

**Comment by Robinfr** [comment]
Can be closed since the PR was merged.

**Comment by joelworsham** [comment]
Thanks guys!
