### ISSUE TITLE
[Polyfill needed] Array.from is unsupported in Safari 8 and Internet Explorer

### ISSUE THREAD

**Issue by stenbln** [clauderic/react-sortable-hoc#139]
Its an awesome library, however, it doesn't work with Safari (I've tested Chrome and Firefox successfully). 

This is the error that I get when I try to sort the items:
`[Error] TypeError: undefined is not a function (evaluating 'Array.from(arr)')`

and this is the line that is apparently causing the problems:
`function _toConsumableArray(arr) {
        if (Array.isArray(arr)) { 
              for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) {
                       arr2[i] = arr[i]; } return arr2; } 
       else { 
                return Array.from(arr);
        }
 }`

Any suggestions on how to solve this?

**Comment by stenbln** [comment]
It seems that this function `Array.from("some array")` is not supported for my Safari version (8). 

According to [this](https://kangax.github.io/compat-table/es6/#test-spread_(...)_operator) page Safari 8 is lacking many functionalities, Safari 9 is a bit better and Safari 10 (newest) has everything supported.

**Comment by clauderic** [comment]
Hey @stenbln, thanks for reporting this. This isn't something in the code explicitly, so I'll take a look and and try to make sure webpack doesn't fall back on Array.from behind the scenes, because I'd rather not have to include a polyfill for this since there are other cross-browser ways to achieve the same thing. 

In the meantime, if you're itching to try out `react-sortable-hoc`, you can add a [polyfill](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill) for Array.from in your code before `react-sortable-hoc` is initialized.

**Comment by stenbln** [comment]
Great. I've added the code that you linked and now it works even in Safari 8. 

Maybe you find this information helpful. I've found out that this `[].slice.call("some array")` does the same thing as `Array.from("some array")` and it is supported also in Safari. 

Thanks for the library. I really like it :1st_place_medal:

**Comment by DeeLindesay** [comment]
FYI 
The demo at http://clauderic.github.io/react-sortable-hoc
doesn't work in IE 11 

I've added to this issue as I think it's related?

**Comment by mccambridge** [comment]
I ran into a similar issue that adding a Polyfill for `Array.from` fixed. Isn't there a way to just not use `Array.from`?

**Comment by Shardendu-kantha** [comment]
@mccambridge can you please help me in adding Array.from Plyfill. I tried this (https://www.npmjs.com/package/array-from), this is not working in IE. Still getting the same error in console.

> object doesn't support property or method 'from'

Please let me know how you used Polyfill

**Comment by arvind1234** [comment]
@Shardendu-kantha I am not sure if you were able to get it working. If not, try using https://www.npmjs.com/package/array.from package. And in your code you would have to do the following:
require('array.from').shim();

Your code can then use Array.from.

@clauderic any chance, you were able to rewrite the library without using Array.from?

**Comment by Shardendu-kantha** [comment]
@arvind1234 hey, sorry for being little late. I got it resolved by the same suggested by you.

[https://github.com/clauderic/react-sortable-hoc/issues/263#issuecomment-321741371](url)

**Comment by tonatiuh** [comment]
In response to comment from @DeeLindesay, I found the demo working when I tested it today in IE11: 

![image](https://user-images.githubusercontent.com/602727/36610788-0c7c4c64-1897-11e8-874d-4c91ab68d763.png)
