### ISSUE TITLE
A fix for Server side rendering issue

### ISSUE THREAD

**Issue by sahanDissanayake** [clauderic/react-sortable-hoc#14]
I get the window not defined error

Is there a way to avoid this please ?

I'm using Meteorjs which has NPM support

**Comment by sahanDissanayake** [comment]
nevermind, just had to import the code on client side..

**Comment by jetarin-min** [comment]
I have encountered the same problem. My project is universal server-side render. I try to put component once it did mounted, but it didn't solve. How do you import lib on client side?

**Comment by sahanDissanayake** [comment]
I gave up using this with MeteorJS I used react-sortablejs
