### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by olegreznichenko** [clauderic/react-sortable-hoc#140]
How to make that it was possible to transfer one of items from one list to another. Both lists wrapped container. At the same time, in the same list is at least 5 and Maxim 5 of elements, and the other a minimum of 2 up to 2.
Example, when you throw a list of items from which a maximum of 2 from the list where a maximum of 5, then the location of items replase from another list which dropped, and vice versa.

**Comment by clauderic** [comment]
This isn't supported quite just yet, but there's a PR to make it happened. Stay tuned https://github.com/clauderic/react-sortable-hoc/pull/138

**Comment by maotan** [comment]
@clauderic  when do you plan to merge

**Comment by maotan** [comment]
@clauderic  when do you plan to merge?
