### ISSUE TITLE
[Question]  large data set / virtualization on a mansonry layout

### ISSUE THREAD

**Issue by MarcMagnin** [clauderic/react-sortable-hoc#148]
Hi,
I was wondering if that would be doable to combine virtualization with animated filtering such as for instance what mixtitup provides: https://www.kunkalabs.com/mixitup/

The idea would be to present a lot of items (let say 30K images to represent), virtualize them and have the nice and smooth filtering animations of such library as mixitup.

Many thanks!

**Comment by clauderic** [comment]
Hey @MarcMagnin, unless you're specifically trying to manually sort the items via drag & drop, I'm afraid that's out of scope of this project.

Having said that, you could perhaps check out [react-flip-move](https://github.com/joshwcomeau/react-flip-move). I don't know whether it's compatible with virtualization libraries though.

**Comment by MarcMagnin** [comment]
Cheers! I'll take a look.
