### ISSUE TITLE
Sorting happens while mousedown after the drag movement ends

### ISSUE THREAD

**Issue by mmela** [clauderic/react-sortable-hoc#149]
Hi everyone,

I'm experiencing following with a grid setup:
1) Start drag with mousedown
--> other items in the grid make space nicely
2) Movement stops (still mousedown)
--> items return to their positions instead of keeping the space as in 1)
3) mousedown released
--> Dragged item gets positioned in the drag location (as it should)

render():
```
<SortableList
  items={this.state.imageBlocks}
  axis="xy"
  pressDelay={200}
  shouldCancelStart={this.shouldCancelStart}
  onSortEnd={this.onSortEnd}
  helperClass="SortableHelper" />
```

SortableItem and SortableList:
```
const SortableItem = SortableElement(({index, item}) => {
  return (
    <div className="image-block">
      <div className="image-block-container">
        <Image src={item.src}/>
      </div>
    </div>
  );
});

const SortableList = SortableContainer(({items}) => {
    return (
        <ul className="SortableList">
            {items.map((item, index) =>
                <SortableItem key={`item-${index}`} index={index} item={item} />
            )}
        </ul>
    );
});
```

**UPDATE: the `SortableList` needed `display: flex;`. Now everything works smoothly.**

**Comment by Robinfr** [comment]
Could you provide a jsfiddle?
