### ISSUE TITLE
Better Docs

### ISSUE THREAD

**Issue by sahanDissanayake** [clauderic/react-sortable-hoc#15]
I have no idea how to get the EXACT replica of the basic usage which is shown on the index page

Like no docs for that, I could get the plugin working but I do not know how to show the dragging element preview to follow the cursor like in the example

**Comment by clauderic** [comment]
The current docs assume a basic level of understanding of ES6 syntax and Webpack (or some other module bundler of your choice). What exactly are you struggling with?

**Comment by sahanDissanayake** [comment]
Yep, ES6 I think I know enough, So back to what I'm struggling.

When you click on a item on list to move around. My list item does NOT popup like in the index page it just disappear and a placeholder is shown when the mouse of moved up and down while mouse buttons is still down.

Does that make sense ?

**Comment by clauderic** [comment]
Probably a `z-index` issue, did you pass in a `helperClass` and apply some styles to it? Try giving it a higher z-index

**Comment by sahanDissanayake** [comment]
let me show you in example
Yep will do, Sometimes this happens. 
I click one move it around
I click one more and the  suddenly two items have disappeared 

Let me try what you suggested. Thanks 
![two_more](https://cloud.githubusercontent.com/assets/5580680/16179337/8ae6c4c2-36b6-11e6-9322-d587687856f2.png)
![one_more](https://cloud.githubusercontent.com/assets/5580680/16179338/8aea660e-36b6-11e6-8c37-3fb225766f69.png)

**Comment by sahanDissanayake** [comment]
```
import React from 'react';

if (Meteor.isClient) {
    import {SortableContainer, SortableElement, arrayMove} from "react-sortable-hoc";
    
    SortableItem = SortableElement(({menuitem}) => (
        <li className="list-group-item">
            <h4 className="list-group-item-heading">{menuitem.name}</h4>
            {
                menuitem.description && (
                    <p className="list-group-item-text">{menuitem.description}</p>
                )
            }
        </li>
    ));

    SortableList = SortableContainer(({items}) => {
        return (
            <ul className="list-group menu-item-sort">
                {items.map((menuitem, index) =>
                    <SortableItem key={'sort -' + menuitem._id + '_index'} index={index} menuitem={menuitem} />
                )}
            </ul>
        );
    });
}

export default class SortableComponent extends React.Component {
    constructor(props) {
      super(props);

        this.state = {
            items: props.data
        }
    }

    onSortEnd(oldIndex, newIndex){
        let items = this.state.items;
        items.splice(oldIndex.newIndex, 0, items.splice(oldIndex.oldIndex, 1)[0]);

        console.log( items );

        Meteor.call('menuitem.updateOrder', items, (err, result) => {
            if (err) {
                alert(err.details);
            }
        });
        this.setState({
            items: items
        });
    }

    render() {
        return (
            Meteor.isClient ? <SortableList items={this.state.items} helperClass={"active"} onSortEnd={this.onSortEnd.bind(this)}/> : <span />
        )
    }
}

````

**Comment by sahanDissanayake** [comment]
if you are seeing the following pic you may see something really weird going on

z-index is totally messed up if a unfixable way 😭 

![weird](https://cloud.githubusercontent.com/assets/5580680/16179364/9a581ff4-36b7-11e6-87b4-ab4907a6c7ba.png)

**Comment by sahanDissanayake** [comment]
For some reason,

When clicked on an item on the list, the ghostItem is created just before the end of the body tag, which is why the the z-index does not work anymore

**Comment by clauderic** [comment]
Are you using the window as a scroll container or do you have an overflow scrolling container? In case you're using the window, you have to pass in `useWindowAsScrollContainer={true}`

**Comment by sahanDissanayake** [comment]
I'm using just an <ul> element as the container nothing fancy, I used ``useWindowAsScrollContainer={true}`` but still get the moving issue just after two list items moving up and down
![nooooo](https://cloud.githubusercontent.com/assets/5580680/16180492/3dc9abfe-36da-11e6-8a21-668998d9737b.png)

**Comment by sahanDissanayake** [comment]
is this because there are different heights of items inside the container ?

**Comment by sahanDissanayake** [comment]
I wish you had the actual examples shown on the websiite inside the exmples/ in this git repo :(

**Comment by clauderic** [comment]
Is there any way you can share a link to this? Either hosting it somewhere or using something along the lines of [ngrock](https://ngrok.com/).

The height of the items should not matter, this library supports variable item heights.

As to your point about better examples, I'll see what I can do when I get some time to work on that.

**Comment by sahanDissanayake** [comment]
I was in a hurry to get something working. So I moved on and used a different drag and drop plugin. 

Thanks
