### ISSUE TITLE
Helper item has no unique identifier

### ISSUE THREAD

**Issue by joelworsham** [clauderic/react-sortable-hoc#154]
Is there any way to get a unique identifier on the helper? Currently, my list items have unique `id`'s and some are styled differently because of this. When dragging, the helper item does not inherit the `id` (makes sense, given that would be 2 idential `id`'s on the page), but it doesn't have ANY unique identifier.

Is there any way something can be passed onto the helper for styling purposes? Maybe a custom defined `id` or `data-*` or something?

**Comment by clauderic** [comment]
Sure, you can use the `helperClass` prop to give it a custom class!

**Comment by joelworsham** [comment]
I don't believe this solves the issue though. That property goes onto the container and will add 1 class to all helpers. What I said above is that I need each helper to be uniquely identified to the item it was created for.

**Comment by clauderic** [comment]
I guess I don't follow then. 

The `helperClass` is a custom class that is dynamically added to the helper (not the container). You can pass a custom class or `data-id` to your wrapped SortableElement, so you could so something like this in css to uniquely style them:

```css
.sortableHelper.mySpecialElement {
  background-color: red;
}

.sortableHelper[data-id="1234"] {
  color: blue;
}
```

**Comment by joelworsham** [comment]
I'm not seeing any `data-id` on the helper. How do I get the `data-id` to show? Also, I would really need to a way to customize what the id is. I'm assuming it's the index of the item? But I need to have something else fill that.

**Comment by clauderic** [comment]
You have to pass the data-id to the component you're wrapping with SortableElement first. Check out this fiddle for details https://jsfiddle.net/xokw3hoq/

**Comment by joelworsham** [comment]
Oh yes I see. Man, I was thinking about this in the wrong way. I was overcomplicating things in my mind.

Thanks for clearing it up!
