### ISSUE TITLE
React Native Support?

### ISSUE THREAD

**Issue by joshuapinter** [clauderic/react-sortable-hoc#156]
Your demos are beautiful and work extremely reliably. There's nothing quite like this on React Native. Do you have any thought as to what it would take to provide support for React Native as well? 

Many Thanks,

Joshua

**Comment by clauderic** [comment]
Hey @joshuapinter,

While I have no plans on fully porting this library to React Native, I do have a barebones version for vertical lists, with support for variable item heights and smooth transitions.

I'll try to get around to cleaning up the code for it and open sourcing it in the near future, but I'm pretty swamped at the moment 😅

**Comment by joshuapinter** [comment]
Thanks @clauderic. I ended up making some improvements to [react-native-sortable-list](https://github.com/gitim/react-native-sortable-list) to get to feature parity across platforms. It's working very well for native now. Not as powerful as your library but good enough for most cases. :)

**Comment by uffou** [comment]
A react native port would be much appreciated

**Comment by agibson73** [comment]
This component is beautiful and I would love to have it in React Native
 ++

**Comment by QQizi** [comment]
I support that !

**Comment by geminiyellow** [comment]
hope we can see a react-native version

**Comment by miguelocarvajal** [comment]
Hey @clauderic 

You mentioned a barebone version for vertical lists. Did you ever get around to publishing it?

**Comment by barrylachapelle** [comment]
+1
