### ISSUE TITLE
Dragging between two lists

### ISSUE THREAD

**Issue by jcuenod** [clauderic/react-sortable-hoc#158]
Maybe I missed it but I can't figure out whether it's possible to drag items between two lists using this component (I want to have a list of enabled and a list of disabled features that can be sorted and enabled by moving between the lists).

**Comment by clauderic** [comment]
Hey @jcuenod, see #138 for progress on this

**Comment by jcuenod** [comment]
ahh - sorry, thanks.

**Comment by clauderic** [comment]
No worries 😄 👍

**Comment by rashmimh** [comment]
Hi, do we support for this now? Thank you in advance.

**Comment by adnan-makecustomersforlife** [comment]
> Hi, do we have example for this now?
> I checked [#138](https://github.com/clauderic/react-sortable-hoc/pull/138) we don't have demo link there.
> Thank you in advance.

Demo Link: 
https://codesandbox.io/embed/react-sortable-hoc-2-lists-5bmlq
