### ISSUE TITLE
[question] generic mechanism to store sort information

### ISSUE THREAD

**Issue by simoneb** [clauderic/react-sortable-hoc#161]
I've seen in the examples that there is an `arrayMove` utility function to mutate arrays in memory, to store them in the component state for example.

What I would like to do is come up with a generic mechanism to store the sorting information somewhere (i.e. localStorage or a database) so that the order can be restored at some later point. Storing this information is simple with the `onSortEnd` callback. What I'm having troubles with is restoring the order from an unsorted data source and the stored information about the order.

Specifically, I would like to implement a generic mechanism to do that, i.e. an HOC.

I tried out a few different approaches:

- store order information by identifying each sortable item by a key on the data object bound to it, then sort the data source before rendering the sortable children
- change the rendering order of sortable children based on the stored information
- change the `index` property of sortable children before rendering them

Of these, the only one I could get to work was the first, as the other two approaches somehow messed up the d&d behavior of the container (items disappearing besides the one being dragged, ...)

The problem with the first approach is that my HOC needs to sort the data before rendering the children, which mean that it needs to be aware of the data, know which property of the child to use to identify it, and finally that it requires an uncommon way to render children which is not very React-ish. That's because iterating the data source within and HOC means that the children of the HOC can't be a classic iteration of a data source, i.e:

`HOC(props => props.data.map(item => Child(item)))`

but rather:

`HOC(item => Child(item))`

which is not idiomatic React.

I'm wondering if I'm missing something here and if one of the first two approaches would work instead, or if there's a different way to implement the latter without the drawbacks.

**Comment by clauderic** [comment]
Hey @simoneb, this will largely depend on your implementation, but assuming you had an array of keyed items such as `[{id: 1, name: 'Bob'}, {id: 2, name: 'Alice'}, {id: 3, name: 'William'}]`, you should be able to do this by using IndexedDB, WebSQL, localStorage.

Here's a basic example of what that might look like with localStorage (untested):
```
const users = [{id: 1, name: 'Bob'}, {id: 2, name: 'Alice'}, {id: 3, name: 'William'}];
const initialOrder = localStorage.getItem('order');

class SortableComponent extends Component {
  state = {
    items: initialOrder.map(id => users.find(user => user.id === id)),
  };
  onSortEnd = ({oldIndex, newIndex}) => {
    this.setState({
      items: arrayMove(this.state.items, oldIndex, newIndex),
    } () => 
      localStorage.setItem('order', items.map(item => id))
    );
  };
  render() {
    return <SortableList items={this.state.items} onSortEnd={this.onSortEnd} />;
  }
}
```
