### ISSUE TITLE
Advice (Pull Request?) on how to add transparency into Prev/Next indexes via onSortMove event?

### ISSUE THREAD

**Issue by curtd59** [clauderic/react-sortable-hoc#165]
within `/SortableContainer/index.js `

I want to test whether an item in the list can be dropped at given index (new position).

When dragging, I want to call a function that determines whether or not to 'open a space' for a drop.
For example, if onDragOver( index.myValue === false) then do not animate and create a drop opportunity.  

This function fires during move.

```
      _this.handleSortMove = function (e) {
        var onSortMove = _this.props.onSortMove;

        e.preventDefault(); // Prevent scrolling on mobile

        _this.updatePosition(e);

        // === start add ====
        if (onSortMove) {
           if !onSortMove(e, { index, _this.prevNode, _this.nextNode })  return;
        }
        //=== end add ===
       
        _this.animateNodes();
        _this.autoscroll();

        // remove this line
        //if (onSortMove) onSortMove(e);
      };

```

Looks like the indexes are found here?

```
      ( ... )
      key: 'animateNodes',
      value: function animateNodes() {
      ( ... )

          // Get a reference to the next and previous node
          var nextNode = i < nodes.length - 1 && nodes[i + 1];
          var prevNode = i > 0 && nodes[i - 1];

          // ===== Add start =====
          _this.nextNode = nextNode;
          _this.prevNode = prevNode;
          //===== Add end =====

```

and that we would need to variables visible to onSortMove here:

```
   function _class(props) {
      _classCallCheck(this, _class);

          // ===== Add start =====
      var _this.prevNode = null;
      var _this.nextNode = null;
          // ===== Add end =====
 
```

Is that something someone can suggest how I should accomplish?  I'm willing to do the work. 

BACKGROUND EXPLANATION
For very large data sets, hierarchical data (think trees, or transactions within charts of accounts) creates punitive costs when querying the database.  There are well known algorithms for solving this problem by maintaining an ordered list rather than a linked list, if you are willing to pay a slightly higher cost on insert of new rows, and write transactions to manage them.  (which is trivial).  

On the front end, reordering a simple list rather than a hierarchical list is trivial to program by comparison.  However, it requires we create light custom functions to test whether a drop index candidate is valid  or not.

React-Sortable-HOC provides an extremely light, clean, and fast method of combining virtualization components and highly performant drag and drop.  And it works on both mobile and desktop platforms.  So it is better suited to large scale applications than much heavier solutions.  

So if I can add this functionality to React-Sortable-HOC it positions the component in the market for components as a much higher end, rather than merely 'lighter' solution.

What I would like is a function called onDragOver to return true or false, where false would cancel the animation creating an opportunity for a drop event at that location. This would mean the user would see only viable drop candidates when dragging over other rows in the list.

What is an example case?  Well, lets say the  "accepts-vegetables:" property of the target index is 'true'.  Then dragging a 'chicken' over that item would return false, and not animate a new space for the drop event.

Thanks

**Comment by curtd59** [comment]
OnSortMove passes the event, previous index, and next index values already. (Found after hunting through the (well written) source.

```
    onSortMove = ({e, prev, next}) => {
        console.log("generated:", JSON.stringify(prev, next, e) )
    };

```

Hopefully this will benefit someone else.

**Comment by rajasimon** [comment]
@curtd59 I can't make that to work. Did you changed anything in the source? I tried this but sadly only `event` is received not `prev` and `next`

```
onSortMove = ({e, prev, next}) => {
    console.log(event)
    console.log(prev)
   console.loog(next)
}
```
`<SortableList items={items}  onSortMove={this.onSortMove} .../>`
