### ISSUE TITLE
Dragging of not empty input[type=file]

### ISSUE THREAD

**Issue by notfffMe** [clauderic/react-sortable-hoc#167]
Hello!
Dragging of not empty input[type=file] throws an Error

**Uncaught InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string**

 because of  this piece of code in ./src/SortableContaine/index.js:

clonedFields.forEach((field, index) => {
    return (field.value = fields[index] && fields[index].value);
 });

**Comment by clauderic** [comment]
Good catch, thanks for reporting this. It might be a few days until I can look into this, so if this is something you'd like to tackle, PRs are most welcome.

**Comment by clauderic** [comment]
Actually, there's already a PR open https://github.com/clauderic/react-sortable-hoc/pull/137, having said that, the proposed solution there is to omit setting the value for file inputs. Not sure if there's a better workaround if we still want to preserve the value.
