### ISSUE TITLE
I've the next problem

### ISSUE THREAD

**Issue by JonDotsoy** [clauderic/react-sortable-hoc#168]
> /State Editing

https://github.com/clauderic/react-sortable-hoc/blob/72156af006737ba0fda3921453cd179adec8ac4b/src/Manager.js#L25

![image](https://cloud.githubusercontent.com/assets/3086539/24311976/463cd9fe-10b5-11e7-9a29-99b917107dc6.png)

![image](https://cloud.githubusercontent.com/assets/3086539/24312105/df09b53a-10b5-11e7-91e4-ae4dff950595.png)

![image](https://cloud.githubusercontent.com/assets/3086539/24312110/e4a1b3ee-10b5-11e7-90fd-df538ea9820b.png)

![image](https://cloud.githubusercontent.com/assets/3086539/24312145/05186d20-10b6-11e7-9655-752e13cecb06.png)

**Comment by clauderic** [comment]
Hey @JonDotsoy, this issue report really isn't actionable. If you'd like me to help you, please take the time to describe the steps to reproduce the issue you've encountered as well as share the code needed to reproduce the issue.
