### ISSUE TITLE
unable to handle items prepended during sorting

### ISSUE THREAD

**Issue by jedwards1211** [clauderic/react-sortable-hoc#174]
I'm trying to make a sortable list that can dynamically load more items at either the top or bottom when the user scrolls to it.

But if I drag the item at index 50 to the top of the list, wait for my code to insert e.g. 10 items at the start of the list, then release the item, `onSortEnd` is called with `oldIndex: 50`.  After the 10 items were inserted at the top of the list, the grabbed item was then at index 60, so the wrong item gets moved by `onSortEnd`.

Not only that but a copy of the item I'm dragging shows up if I scroll back down to it.

This seems to be a fundamental limitation of how `react-sortable-hoc` works.  Aside from finding the new index of the grabbed item via `indexOf` or `===` comparison, the only solution I can imagine would involve some kind of `id` or `key` property on items.

Adding to the difficulty is the fact that I'm trying to display a reactive view in a meteor app.  The items present and their order could be changed at any time from outside the client, and it should be able to respond to that.  Seems like I'll have to fork this project and do some major surgery to be able to handle reordering during dragging.

The item being dragged could even be deleted by someone else (or stop matching the current filter) while being dragged, in which case I have to be able to terminate user sorting and tell them what happened.

@clauderic what are your thoughts on this?

**Comment by clauderic** [comment]
That sounds like a really odd use-case, or I'm having a really hard time visualizing what you're trying to describe. Why do you need to dynamically add items to the list during sorting?

`react-sortable-hoc` supports virtualization libraries like https://github.com/bvaughn/react-virtualized out of the box, if that's what you're trying to accomplish manually.

If that's not quite your use-case, you should still be able to make it work if you know ahead of time how many items you'll have. `react-sortable-hoc` doesn't care how many items are in the DOM when you begin sorting, so long as you give them the right indexes. 

For example, say you had 3 items in the DOM when sorting begins, and then dynamically added 3 before those, you'd need to make sure the indexes of the items initially visible were `4`, `5`, `6`

**Comment by jedwards1211** [comment]
@clauderic We're talking about a reactive website subscribing to a Meteor collection where elements can get added, removed, and changed from anywhere in the list at any time by another user.

I suppose if I were going to use this and changes to the list come in from the Meteor subscription, I could just hold off on actually incorporating those changes while the user is sorting.  But their sort might be invalid in that case anyway...so I'm just going to make my own thing with `react-dnd`.
