### ISSUE TITLE
Unexpected behaviour on Samsung Internet browser

### ISSUE THREAD

**Issue by adamredwards** [clauderic/react-sortable-hoc#177]
We have been testing react-sortable-hoc on a variety of mobile devices and browsers. The plugin is working great on the majority of platforms, however we discovered some weirdness in the default Internet browser on Samsung. 

I've added a list of the issues below, along with some screenshots.

- The draggable element is cloned, but the original is still shown in the list
- The new item becomes detached from the component and floats on top of the page once it has been clicked
- The items in the list are not re-ordered

![screenshot_20170330-164923](https://cloud.githubusercontent.com/assets/23029098/24513894/5d4e474a-156a-11e7-8418-f6e4761c8834.jpg)
![screenshot_20170330-165019](https://cloud.githubusercontent.com/assets/23029098/24513895/5d51ea76-156a-11e7-9deb-6fa6bbb1b721.jpg)

Any help or ideas are appreciated.

**Comment by corneldm** [comment]
@adamredwards does it matter whether or not useDragHandle is enabled? I'm seeing a similar issue with touch events + SortableHandle that I'm debugging. The demo page (http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/drag-handle?_k=tto9vw) works flawlessly, however, so it might be related to position calculations for the particular elements I'm nesting. I'll try reducing what I have to match the demo structure.

**Comment by corneldm** [comment]
My issue's resolved. I was accidentally building multiple SortableHandle components (instantiating within render), instead of declaring the constant outside my list item component.

**Comment by clauderic** [comment]
Hey @adamredwards, thanks for sharing your findings. 

This isn't something I've seen myself. Do you see the same behavior if you visit the demo site? If not, can you share more details about your setup?

Do you know if a simulator exists for that specific device? It'll be hard for me to help debug this without being able to see for myself.
