### ISSUE TITLE
Custom className on SortableElement

### ISSUE THREAD

**Issue by expdevelop** [clauderic/react-sortable-hoc#179]
Awesome work, thanks for this!

How to append styles when user clicks on an element like on [the demo](http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=vwrvdh)?
I was trying to write styles for :focus & :active states, but it is not working

**Comment by expdevelop** [comment]
Solved by helperClass prop :)

**Comment by bonavida** [comment]
@expdevelop How did you use the helperClass prop?

I tried using `helperClass={'selected'}` and then I added the class to my styles.css:
```css
.selected {
    background-color: #75B7FF;
}
```
but nothing works :(

**Comment by tommybernaciak** [comment]
How? Property 'helperClass' does not exist for SortableElement.
