### ISSUE TITLE
index missing in SortableElement

### ISSUE THREAD

**Issue by XeniaSiskaki** [clauderic/react-sortable-hoc#180]
Problem can be seen in https://jsfiddle.net/XeniaSiskaki/kajt284L/1/

I would like for each `SortableElement` to have an `x` icon so that the user can click on it and delete the element from the list. However, I cannot access the index in the `SortableElement`. Is that a bug or desired behavior?

**Comment by clauderic** [comment]
Duplicate of https://github.com/clauderic/react-sortable-hoc/issues/128

This is an unfortunate side-effect of omitting `react-sortable-hoc` props from being passed down. I'll try to come up with a more suitable workaround, but in the meantime, you can do something like this:
https://jsfiddle.net/kajt284L/2/

**Comment by XeniaSiskaki** [comment]
Thanks!
