### ISSUE TITLE
Missing shouldCancelStart event in typescript definition file

### ISSUE THREAD

**Issue by charlesrey** [clauderic/react-sortable-hoc#186]
Hi,
In the typescript definition file located [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/react-sortable-hoc/index.d.ts) it seems that the shouldCancelStart function on the SortableContainerProps is missing.

Thanks for your help,

Charles.

**Comment by clauderic** [comment]
Hey @charlesrey, great observation, I'm not a user of TypeScript myself. If you have time, can you open up a PR in that repo? 😄
