### ISSUE TITLE
Feature: switch instead of shift option

### ISSUE THREAD

**Issue by alexdemartos** [clauderic/react-sortable-hoc#188]
Hi,

it would be great to add an option for choosing between switch positions or shift positions when ordering. I know this is pretty easy to do in the backend (onSortEnd), but the front animations are made for shifting.

Example: move last element to the beggining.

Shift (now): [0, 1, 2, 3] -> [3, 0, 1, 2]
Switch: [0, 1, 2, 3] -> [3, 1, 2, 0] 

Thank you.

**Comment by clauderic** [comment]
I don't think animations would make sense in such a scenario. However, if you set `transitionDuration` to `0`, then you can easily handle this yourself in `onSortEnd`.
