### ISSUE TITLE
When the sort starts (mouse down) the helper is added but the ghost is hot hidden

### ISSUE THREAD

**Issue by zaygraveyard** [clauderic/react-sortable-hoc#19]
### How to reproduce
1. Go to the [demo page](http://clauderic.github.io/react-sortable-hoc/)
2. Add `.Showcase__style__stylizedHelper {background: transparent;}` to the styles.
3. Press (without moving or releasing the mouse) on an item of the list.

### What happens
The item is still visible (white background), if you move the mouse the item is now hidden (background grey)

### What was expected
The item is hidden (background grey)

I can submit a PR if needed.

**Comment by clauderic** [comment]
Fixed in `0.0.3`
