### ISSUE TITLE
Disabled prop no longer passed to WrappedComponent

### ISSUE THREAD

**Issue by davidgoli** [clauderic/react-sortable-hoc#190]
Our implementation of a sortable list ca. 0.0.9 depended on the `disabled` prop being passed through to the wrapped child component, but it appears as of 0.6.2 this is no longer the case. Our workaround currently looks like this:

```js
const Item = SortableElement(({ child, itemClassName, disableSorting }) => {
  const classes = classnames('sortable-item', { 'sortable-item--disabled': disableSorting }, itemClassName)
  return <RecordListItem className={classes}>{child}</RecordListItem>
})

const List = SortableContainer(({ items, loaded, copy, itemClassName, disableSorting }) => {
  const renderChild = (child, index) => {
    const props = {
      key: `item-${index}`,
      itemClassName,
      index,
      child,
      disabled: disableSorting,
      disableSorting,
    }
    return <Item {...props} />
  }

  return (
    <RecordList loaded={loaded} copy={copy}>
      {items.map(renderChild)}
    </RecordList>
  )
})
```

Would be great to just use the `disabled` prop and not have a duplicate prop for this. Is there any reason why `disabled` is explicitly omitted from the passed-through props?

**Comment by clauderic** [comment]
Yeah, this is an unfortunate side-effect of https://github.com/clauderic/react-sortable-hoc/issues/98

See #128 and #180 for more context
