### ISSUE TITLE
transition for dropping element to a new position

### ISSUE THREAD

**Issue by Rezaaa** [clauderic/react-sortable-hoc#199]
It would be good if you add some transition for dropping element to a new position.

**Comment by clauderic** [comment]
Duplicate of #63.

In short, I'd be more than happy to look at a PR that would implement this kind of functionality, but it isn't something I have enough bandwidth to work on myself.

**Comment by davidetruffo** [comment]
@clauderic what about this? #308 
It looks like it addresses this issue :)

(Thanks for the great work, btw! Kudos!)

**Comment by lmenus** [comment]
+1 @clauderic
