### ISSUE TITLE
{withRef: true} results in warning

### ISSUE THREAD

**Issue by alex-vg** [clauderic/react-sortable-hoc#201]
`Warning: Stateless function components cannot be given refs (See ref "wrappedInstance" in StatelessComponent created by [myComponent]). Attempts to access this ref will fail.`

**Comment by aronallen** [comment]
I have the same problem.
```
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
```

**Comment by clauderic** [comment]
As the error states, you can't give refs to stateless functional components. This means you'll need to change your component to use the ES6 class syntax instead.

```js
const MyComponent = () => {
  return <div>Hello world!</div>;
}

class MyComponent extends React.Component {
  render() {
    return <div>Hello world!</div>;
  }
}
```
