### ISSUE TITLE
When dragging, text wraps to two rows

### ISSUE THREAD

**Issue by Torniojaws** [clauderic/react-sortable-hoc#203]
How can you prevent this from happening when the ``<li>`` item has a breakable space in it?
![b21hicnbid](https://cloud.githubusercontent.com/assets/5442750/26348733/530e3bf2-3fb6-11e7-9c61-b21007c7b892.gif)
I would prefer it to remain in one row. I have tried adjusting it with various pieces of CSS, but they all have that behaviour, except for ``min-width: n px`` (the exact value depends on the length of the displayed string).

The styles I use for them currently (Bootstrap):
``<div className="reorder">``
``<ul className="list-inline">``
``<li className="list-group-item reorder-box">`` 

```
div.reorder {
    background-color: #c6c6c6;
    border-radius: 4px;
    > ul {
        padding: 5px 5px 5px 10px;
    }
}
```
```
li.reorder-box {
    background-color: #55ddff;
}
```

**Comment by Torniojaws** [comment]
It is a bit better when forcing:
```
li.reorder-box {
    background-color: #55ddff;
    box-sizing: content-box !important;
}
```
But now it makes the box a bit bigger when dragging. Probably adds the padding in addition to the current size (which already includes the original padding).

**Comment by clauderic** [comment]
Try `box-sizing: border-box;`
