### ISSUE TITLE
Percentage width

### ISSUE THREAD

**Issue by davidworkman9** [clauderic/react-sortable-hoc#204]
I've looked through the source and can't seem to find where it's happening, but it appears as if the width is being rounded. Whenever the width of one of my sortable items has less than a .5 decimal place it ends up having a container with a width rounded down, if it's above .5 it's rounded up. The result looks like this:

less than .5:
<img width="265" alt="screen shot 2017-05-23 at 2 22 34 pm" src="https://cloud.githubusercontent.com/assets/1152186/26369677/605f9096-3fc3-11e7-84ed-2a84ecc0936a.png">

greater than .5:
<img width="253" alt="screen shot 2017-05-23 at 2 23 44 pm" src="https://cloud.githubusercontent.com/assets/1152186/26369697/775e1d80-3fc3-11e7-8b2b-e59c4e71152c.png">

How can I fix this?

**Comment by clauderic** [comment]
Are you able to share a fiddle reproducing the issue? Never seen anything like this myself.
