### ISSUE TITLE
Add support for having the helper stay in the list's bounds

### ISSUE THREAD

**Issue by zaygraveyard** [clauderic/react-sortable-hoc#21]
Currently only it's half is inside the list.

I can submit a PR if needed.

**Comment by clauderic** [comment]
Can you elaborate? Not sure what you're referring to

**Comment by zaygraveyard** [comment]
if you go to the [lock axis demo page](http://clauderic.github.io/react-sortable-hoc/#/advanced/lock-axis?_k=r9v019) and try to drag an item above the list, that item will be half inside and half outside of the list.

**Comment by zaygraveyard** [comment]
Here's a snapshot
![image](https://cloud.githubusercontent.com/assets/603764/16267207/cacc86ac-3888-11e6-99f8-4b5121a27087.png)

**Comment by clauderic** [comment]
This is by design. Why exactly is this a problem?

**Comment by zaygraveyard** [comment]
> This is by design.

That's why this is a feature request and not a bug report ;)

> Why exactly is it a problem? Do you have a use case in mind?

I would like to have the option to restrict the dragging of the items to the strict bounds of their container.

Thank you

**Comment by clauderic** [comment]
Hmm. Fair enough. I'm busy tackling other more urgent bugs, but feel free to submit a PR if you feel strongly about this 👍
