### ISSUE TITLE
Sortable grid first row problem

### ISSUE THREAD

**Issue by konutis** [clauderic/react-sortable-hoc#211]
There is a problem, if you try to drag an item from any row below first row in the first row. If this dragging item goes out of whole container, it is starting to twitch. 
See example - 
![react-sortable-hox-grid-bug](https://cloud.githubusercontent.com/assets/11874495/26674361/e7fb3a8a-46c8-11e7-9b8e-e7427ddc80ce.gif)
I really like this plugin, but this is driving me crazy.

**Comment by alexedev** [comment]
I have the same problem but when dragging to the last row

**Comment by praya** [comment]
Please help, This problem is still not solved

**Comment by clauderic** [comment]
Fixed in Fixed in #479
