### ISSUE TITLE
using different components as SortableElement

### ISSUE THREAD

**Issue by suskind** [clauderic/react-sortable-hoc#216]
I'm not sure if this is an issue or it's my fault, if so, sorry for that

I'm trying to use two different components as SortableElement, one for "fields" and another one for "groups".

I have this 2 jsfiddles: (the differences are in lines 52/53 and 55/56)

1) https://jsfiddle.net/gxun23rr/  -  this one is using a different LI when type is "field" or "group" 

2) https://jsfiddle.net/gxun23rr/1/ - this one is using different components (ItemTypeField or ItemTypeGroup) when type is "field" or "group" 

- 1 is working well

- 2 after drag element "type group" to another position it starts being unstable 

Thank you

**Comment by fvieira** [comment]
It was hell to track this but I got it!
https://jsfiddle.net/fvieira/gxun23rr/2/

I only changed the `key` in line 63 from `index` to `Math.random()`, which prevents React from reusing the components when they are reordered which apparently is what was messing everything up!

The reason why is probably in the link below although I'm too tired to look it up now... xD

https://facebook.github.io/react/docs/reconciliation.html

So yes, it was indeed your fault, but if it's any consolation, this was the most non obvious bug I've seen in a looooong time...
