### ISSUE TITLE
Items being set to visibility: hidden, opacity: 0

### ISSUE THREAD

**Issue by sami616** [clauderic/react-sortable-hoc#220]
Hi folks, i have set up my project following the docs (only executing a console log for the onSortEnd function for now). When i try to drag an item i'm only ever able to grab the first one and the rest disappear. Looking at dev tools, all the other items are given an inline of visibility: hidden, opacity: 0. 

I've seen people have had zindex issues with disappearing elements when using bootstrap but im not :/ 

Have i done something obviously wrong??

Sami.

**Comment by hitman99** [comment]
Hi,
I just had the same problem and resolved it by adding index prop to SortableItem HOC. index prop is required as per docs.

`items.map((item, index) => <SortableItem index={index} />)`

**Comment by clauderic** [comment]
@sami616 I'm not sure what the issue you're describing is, I'd need to see the code. Are you able to share a fiddle?

**Comment by GaurabendwithB** [comment]
hideSortableGhost={false}

**Comment by sunhohong** [comment]
For future reference.
If your item is disappeared when sorting, it is already noted in README

https://github.com/clauderic/react-sortable-hoc#item-disappearing-when-sorting--css-issues

**Comment by rzade** [comment]
![Capture](https://github.com/clauderic/react-sortable-hoc/assets/51227871/1bfb139c-4cf1-4769-9dd1-aac426500b1f)
check our index

**Comment by rzade** [comment]
![image](https://github.com/clauderic/react-sortable-hoc/assets/51227871/d1dbb589-d04c-48e4-ae14-84ec051400dd)
check your index
