### ISSUE TITLE
Working with 'react-virtualized', failed to pass index into each row. (with demo)

### ISSUE THREAD

**Issue by FateRiddle** [clauderic/react-sortable-hoc#225]
https://codesandbox.io/s/qYEvQEl0

I try to render a list of draggables, everything seems fine only that I can't figure out how to pass 'index' into `rowRenderer`

If I do `rowRenderer=props => <Row {...props}/>`, index is passed in sucessfully.
But if I do:
`const SortableRow = SortableElement(Row)`
`rowRenderer=props => <SortableRow {...props}/>` , index is blocked somehow, failed to pass into `<Row/>`

**Comment by FateRiddle** [comment]
Solved, react-sortable-hoc is stripping out the implicit index and key values. I'd rather they just used it without stripping it off props.

**Comment by yashcr07** [comment]
Is there a solution to this ??
