### ISSUE TITLE
Support to tree-views

### ISSUE THREAD

**Issue by jzimermann** [clauderic/react-sortable-hoc#227]
Hi all,

Is there any plan to add the manipulation of tree (as a specialization of list) in the future? 

Problem statement: currently Material UI does not support drag and drop to sort lists. The ```react-sortable-hoc``` does solve the problem but seems to not allow the creation of trees (like the ```nestedItems ``` property of ```ListItem```). 

Thanks for you kind contributions!

**Comment by clauderic** [comment]
Nope, I don't think this isn't something I will ever plan on supporting, but I strongly recommend you check out https://github.com/fritz-c/react-sortable-tree

**Comment by jzimermann** [comment]
Thanks @clauderic!
