### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ricokahler** [clauderic/react-sortable-hoc#231]
```
                                                      
                                                      
                                                      
             +------------------+                     
             | TYPESCRIPT USER  |                     
             |                  |                     
             |                  |                     
             |     +-------------------+              
             |     |            |      |              
             |     | ME ME ME   |      |              
             |     |            |      |              
             +-----|------------+      |              
                   |                   |              
                   |  REACT SORTABLE   |              
                   |  HOC USER         |              
                   |                   |              
                   +-------------------+              




```

This library is already has third party typings but I'd like to bring them in the repository for long term support.

There are two ways to do this:

1. bring the write type declarations in the repository
2. port the whole project to typescript

I'm actually in favor of option 2.

OP, If you're not a typescript user, maybe I can convince you?

Let me know your thoughts! Thanks for the great library 👍 🥇

**Comment by clauderic** [comment]
Hey @ricokahler,

I'd love to look into porting this library to TypeScript, I already use it a fair amount for work related projects.

Having said that, I don't have the bandwidth to convert the library myself. If this is something you feel strongly about, a PR to that effect would be most welcome 👍

**Comment by dlindenkreuz** [comment]
Wow guys, option 2 is quite an endeavour.

TS definition files would be perfectly alright as well, I'm gonna check for myself if this is worth taking a shot.

**Comment by dlindenkreuz** [comment]
Done ✅

This should solve the issue for now. The declaration file is all I needed to work with react-sortable-hoc in a large-scale Typescript project.
