### ISSUE TITLE
Ordering issue

### ISSUE THREAD

**Issue by Vanojx1** [clauderic/react-sortable-hoc#233]
Issue explained in [https://stackoverflow.com/questions/44888603/react-sortable-ordering-issue](this) stackoverflow question.
![reactsortableorderingissue](https://user-images.githubusercontent.com/15717390/27799269-cc62ef7e-6014-11e7-9868-eb7342c4fbb6.gif)

**Comment by clauderic** [comment]
Looks like this was solved.

For reference, solution involved using `getContainer`
```js
<SortableList 
  ....
  getContainer={() => {
    return ReactDOM.findDOMNode(this.refs['menu'])
  }}
/>
```
