### ISSUE TITLE
Error on dragging

### ISSUE THREAD

**Issue by VaskaDogana** [clauderic/react-sortable-hoc#235]
Hi, try use your library with webpack2 and https://luigiplr.github.io/react-router-redux-rxjs-code-splitting/#/
have this error on dragging 
`_baseOrderBy.js:24 Uncaught TypeError: iteratee is not a function
    at _baseOrderBy.js:24
    at arrayMap (_arrayMap.js:16)
    at _baseOrderBy.js:23
    at arrayMap (_baseMap.js:16)
    at baseOrderBy (_baseOrderBy.js:22)
    at sortBy.js:45
    at apply (_apply.js:15)
    at _overRest.js:32
    at Manager.getOrderedRefs (Manager.js:73)
    at _class.animateNodes (index.js:581)`

Google didn't help me.
May be you can help
p.s. I copied your example Drag-handle and then have error above.

**Comment by clauderic** [comment]
I'm not really sure, are you sure all of the dependencies are installed properly? Like lodash for instance

**Comment by harryxu** [comment]
I encountered this issue on `LodashModuleReplacementPlugin` has been used.

**Comment by Wildhoney** [comment]
Me too @harryxu &mdash; thanks!
