### ISSUE TITLE
Overflow bug while dragging an item upwards in a grid

### ISSUE THREAD

**Issue by InterAl** [clauderic/react-sortable-hoc#242]
The bug can be seen in your examples website:

http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=pa2nzs

Try dragging an element from the second row to the first row.

The first row, while dragging into it, contains 4 elements instead of 3.

After dropping, the container re-adjusts and the first line contains 3 elements as before.

![image](https://user-images.githubusercontent.com/8208975/28157159-43427a64-67be-11e7-8dcf-702e4bef7bf2.png)

**Comment by clauderic** [comment]
Fixed in #479
