### ISSUE TITLE
Drag between groups?

### ISSUE THREAD

**Issue by 82rules** [clauderic/react-sortable-hoc#245]
I tried looking thru the docs, but it seems dragging elements is limit to its container, if I have several containers is it possible to drag elements between them. 

My use case is this
```
Level A - Categories List
     Level B - Category - Contains draggable items
             Level C - Individual Draggable Item
             ...
      Level B (2) 
             ....
```

I need to be able to drag a level C element between level B containers.

**Comment by varHarrie** [comment]
see #138
