### ISSUE TITLE
onSortChange hook

### ISSUE THREAD

**Issue by benwiley4000** [clauderic/react-sortable-hoc#251]
Not sure if `onSortChange` is the best name, but I think there should be a hook that gets fired whenever sort order changes (during dragging; *before* `onSortEnd`). It can be useful to update the rest of the UI early. Is there a way to do that currently, which I've missed?

**Comment by pcvandamcb** [comment]
I came here for this. Would be nice to reflect changes in sort order in real time.

**Comment by clauderic** [comment]
Fixed by #278
