### ISSUE TITLE
Handles don't appear in Drag Handle example in IE 11

### ISSUE THREAD

**Issue by mccambridge** [clauderic/react-sortable-hoc#252]
~~I just cloned the repo and updated both my code locally and ran your storybook. In IE 11, items aren't draggable. Please note they _are_ draggable in the default example, but when I run the Drag Handle example, I see the same behavior I'm seeing in my app. Thanks for looking into this. I'll dig further and see what I can figure out, too.~~

Scratch that. The only issue I'm seeing in the Drag Handle example is that the drag handles themselves aren't appearing for me in IE 11.

**Comment by mccambridge** [comment]
Actually, I think the issue in storybook -> Drag Handle is related to the drag handles themselves. Minor bug in your example. I'm not sure the issue I'm seeing, while exhibiting similar behavior, is actually the same issue.

**Comment by susas3** [comment]
I have the same problem - not working in IE11 at all. I have an error in console, even in your examples (http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/basic-usage?_k=2cfxhd).

**Comment by bmueller-sykes** [comment]
I'm experiencing the same thing. In IE11 on the "drag handle" example, I see the following issues:

* The drag handle image does not appear
* mousing over the handle area does show the cursor change
* attempting to drag using the (invisible) handle produces a nasty console error: "Object doesn't support property or method 'from'", which appears to be coming from this line:

`return Array.from(e)}function o(e,t){if(!(e instanceof t))throw new TypeError`

In my own code, I see a slight variation: I do see the drag handle image, but I do *not* see the cursor change on `hover`. I get the same JS error

**Comment by bmueller-sykes** [comment]
Ah, it looks like this may be relatively simple to fix:

https://stackoverflow.com/questions/36622505/typescript-array-from-in-ie11

`Array.from` does not appear to be supported by IE11. So it needs to be polyfilled. It seems like the best strategy is for this to be handled within this library, correct?

It looks like this library is already including this:
https://babeljs.io/docs/usage/polyfill/

...so I'm not 100% sure why it's not just working. It does appear to be the case that the top-level `index.js` file has `import 'babel-polyfill';`, but I don't find that anywhere in the `src` folder, so perhaps that's the issue?
