### ISSUE TITLE
helperClass isn't applied to currently active element in IE

### ISSUE THREAD

**Issue by mccambridge** [clauderic/react-sortable-hoc#254]
The `helperClass` I specified in `SortableList` works great in other browsers. But it's not being applied to the element in IE11.

**Comment by mccambridge** [comment]
Looks like your distributable uses array spread without transpiling to populate the classList string.

```this.helper.classList.add(...helperClass.split(' '));```

So you're taking the helper class string, converting it to an array, and dropping it back into a string via spread?

**Comment by dcorb** [comment]
Same issue here, IE11 doesn't add helperClass to the dragging element

**Comment by dcorb** [comment]
IE11 only loads the first class of helperClass (for example helperClass="foo bar", will load only "foo")

I used create-react-app and copy/pasted this polyfill https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill  to avoid another IE11 error about Array.from not supported

**Comment by decafdennis** [comment]
This is due to `Element.classList.add` not supporting multiple arguments in IE11, as noted in the browser compatibility table here: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

I was able to make v0.8.3 work using [`classlist-polyfill`](https://www.npmjs.com/package/classlist-polyfill).

**Comment by clauderic** [comment]
This is now fixed and no longer requires a polyfill https://github.com/clauderic/react-sortable-hoc/blob/master/src/SortableContainer/index.js#L341
