### ISSUE TITLE
Passive event listeners support

### ISSUE THREAD

**Issue by DimitryDushkin** [clauderic/react-sortable-hoc#257]
I saw https://github.com/clauderic/react-sortable-hoc/issues/210 but actually there is possibility to add support — https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md I believe it will introduce nice performance boost. 

The trick is to add CSS `touch-action: none` to target DOM element.

Passive event listener and `touch-action` are not supported everywhere, but there are tests for them. I think test for passive event listener is enough to be sure that `touch-action` is also supported.

If you do not mind I can make PR for this.

**Comment by clauderic** [comment]
The reason we use `event.preventDefault()` is to prevent scrolling from being triggered on touch devices while sorting.

There are a number of laptops that have touch support as well, so this doesn't only apply to mobile devices.

Therefore the only place where we could benefit from this is on desktop devices where touch isn't enabled.
