### ISSUE TITLE
SortableElement not using provided style

### ISSUE THREAD

**Issue by id0Sch** [clauderic/react-sortable-hoc#259]
Hi,
i'm trying to follow the solution of the z-index issue (https://github.com/clauderic/react-sortable-hoc/issues/87#issuecomment-260335983)
and i have the following component:
``` javascript
const SortableItem = SortableElement(({value}) => <div className="item" >{value}</div>)
const Sortable = SortableContainer(({items}) => {
  return <List className="list">
    {
      items.map((item, index) => <SortableItem key={item} index={index} value={item}
                                               style={{zIndex: 1000000}}/>)
    }
  </List>
})
```
and this is the generated html
![image](https://user-images.githubusercontent.com/5864772/28867880-3e590294-7780-11e7-9cf0-7e1f74579abd.png)

it seems as if the SortableElement is creating another div that is created w/o the provided style.
am I missing anything? 
Thanks.

**Comment by clauderic** [comment]
You're not passing the style attribute down to the `div` itself.

```js
const SortableItem = SortableElement(({value, style}) => 
  <div className="item" style={style}>{value}</div>
)

**Comment by id0Sch** [comment]
weird, setting the `helperClass` didn't work before so i tried the z-index solution.
but it did now..
thanks!

**Comment by SerKnight** [comment]
Yeah I found inline style to be easiest to persist css during drag.

```html
<span style={{fontWeight:'bold', paddingRight: 5}}>{num +1})</span>
    {value}
</span>
```
