### ISSUE TITLE
BUG: `margin`s are not taken into account in the re-positioning of the items

### ISSUE THREAD

**Issue by zaygraveyard** [clauderic/react-sortable-hoc#26]
### How to reproduce
1. Go to the [demo page](http://clauderic.github.io/react-sortable-hoc/)
2. Add `.Showcase__style__stylizedItem {margin-bottom: 10px;}` to the styles.
3. Drag the first item of the list bellow the second and don't release the mouse button.

### What was expected
The second item slides all the way to the top.

### What happens
The second item slides up but not all the way to the top (leaving a margin above it).

### Reason
The items are translated by `dimension` with is either `width` or `height`, [which in turn are `offsetWidth` and `offsetHeight` respectively](https://github.com/clauderic/react-sortable-hoc/blob/master/src/SortableContainer/index.js#L100)
But `offsetWidth` and `offsetHeight` do not include the margins [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight).

### Snapshots
![image](https://cloud.githubusercontent.com/assets/603764/16308831/c8f199e2-3966-11e6-8a62-4a6172e76c34.png)
---
![image](https://cloud.githubusercontent.com/assets/603764/16308869/eda61dda-3966-11e6-9ac2-12f5b19fdef2.png)

**Comment by clauderic** [comment]
Hrmmm. You can always use padding for spacing instead for the time being if this is an issue. I'm a little busy with other projects at the moment, but if you'd like to submit a PR for this, I'll happily accept it

**Comment by zaygraveyard** [comment]
> You can always use padding for spacing instead

This is exactly what I did :)

> If you'd like to submit a PR for this, I'll happily accept it

I'll try but it's not easy to calculate the margins.
AFAIK we need to parse the `margins` computed style property and it might contain `px`, `em`, `%`, .... values, which is not ideal

**Comment by clauderic** [comment]
You can use `window.getComputedStyle(element)` to get the computed `marginTop` and `marginBottom` values

**Comment by zaygraveyard** [comment]
I was talking about them, but I thought they didn't always return the values in `px`.
I juste tried it and found that they do return `px` always.
Thank you
