### ISSUE TITLE
Do not use lodash just because of 2 functions

### ISSUE THREAD

**Issue by huston007** [clauderic/react-sortable-hoc#261]
Hello! 
I think this awesome project can easily get rid of unneeded "lodash" dependency and just implement "random" and "sortBy" functions by itself.

We don't use lodash in our project, but it still gets into codebase just because of this `react-sortable-hoc`.

**Comment by princed** [comment]
We found out that lodash used from this component takes about:
* 104.7 KB raw
* **23.21** KB minified
* **6.79** KB minified+gzipped

Looks like custom functions could take order of magnitude less space. 
What do you think? Would you like to receive a PR?

**Comment by iamrommel** [comment]
I think you can just import the lodash.random (https://www.npmjs.com/package/lodash.random) which is thinner, or lodash.sortBy.

You can actually chopped any modules from lodash and just import that. I think it will consumed less space.

**Comment by fspoettel** [comment]
You could also use `babel-plugin-lodash` to remove unneeded lodash modules since the build process is using babel already.

**Comment by chucksellick** [comment]
Normally you should just do

`import random from 'lodash/random'`

Then you only get the function you need and tree-shaking can eliminate the rest of the library.

**Comment by fspoettel** [comment]
@chucksellick tree-shaking lodash currently does not work as expected with webpack, see: https://github.com/webpack/webpack/issues/1750 and https://github.com/lodash/babel-plugin-lodash

**Comment by shawnphoffman** [comment]
At very least, don't use the shorthands functionality for orderBy so that we can shake out all of the extra lodash dependencies in our own projects. 
See link for more details: https://github.com/lodash/lodash-webpack-plugin/issues/128

**Comment by clauderic** [comment]
Removed lodash dependency in 0.7.0
