### ISSUE TITLE
Drag and sort is not working in IE

### ISSUE THREAD

**Issue by raghav1086** [clauderic/react-sortable-hoc#263]
I have used `react-sortable-hoc` in my project it works well on Chrome, Firefox and Safari but not working on IE. The weird thing is there is no error when I try to drag the element. I tried to test this http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/basic-usage?_k=sx304f on IE but it also doesn't work. Please help how to fix drag and drop sorting issue on IE.

**Comment by Shardendu-kantha** [comment]
I am getting this error in IE console.

> object doesn't support property or method 'from'

I tried using different versions of react-sortable-hoc, also tried some polyfill as well (https://www.npmjs.com/package/array-from).

Does anyone have a solution for this? Not working on IE11

**Comment by Shardendu-kantha** [comment]
@raghav1086 

use https://www.npmjs.com/package/array-from.

> npm i array-from --save-dev

then in your custom js file add 

> if (!Array.from) {
    Array.from = require('array-from');
}

**Comment by raghav1086** [comment]
@Shardendu-kantha Thanks for your suggestion but I updated package with `0.6.6` version and it is working now, in `0.6.3` it was not working even with polyfill.

Note: This issue can be closed now :) 👍 🎉

**Comment by sanalkumarparakkad** [comment]
I was using v0.8.3 and faced the same issue. It seems to be broken in the higher versions. Went back and reffered 0.6.6 and issue got resolved. Thanks
