### ISSUE TITLE
Consider passing `disabled` prop into element wrapped with SortableElement

### ISSUE THREAD

**Issue by shepmaster** [clauderic/react-sortable-hoc#265]
Currently, the [`collection`, `disabled`, and `index` props are removed]( https://github.com/clauderic/react-sortable-hoc/blob/29aa68573b2eb88a794668e860b11ecab48b7639/src/SortableElement/index.js#L89). However, my usage requires knowing if the element is disabled, so I have to pass in a second property with the same logic. 

Since the HOC already "commandeers" any existing `disabled` prop, I don't believe that passing a new prop would cause any issues.

Thank you for the very easy-to-use library!

**Comment by davidesigner** [comment]
Up!

This would be nice to get `disabled` and `index` props into the wrapped element.

For the moment, I have to pass renamed props like that:
```
index={index}
disabled={disabled}
fieldIndex={index}
isDisabled={disabled}
```

Thank you for this awesome library!

**Comment by shepmaster** [comment]
@clauderic does closing this issue without an associated PR mean that you disagree with the idea?

**Comment by agentgonzo** [comment]
I've just come across this. It's better to use composition rather than inheritance for this problem:

```
const SortableItem = SortableElement(({children}) => {
  return (<>{children}</>)
})

const SortableList = () => {
...
return (
  <SortableItem index={sortableIndex} disabled={elementCanBeSorted}>
     <MyComponent index={myComponentIndex} disabled={myComponentIsDisabled} />
     ...
  </SortableItem>
)
```
