### ISSUE TITLE
questions ablut disable drag and SortableHandle

### ISSUE THREAD

**Issue by ahutyaoyj** [clauderic/react-sortable-hoc#269]
questions:
1. SortableElement returned a dragable li, when I set some li to diable, if I drag the blank area, it won't drag, but if I drag the other children elements some thing like text, it will still drag.  The disable attribute can not work when click SortableElement's children element.

2. About SortableHandle, I set a icon as the SortableHandle, but the whole SortableElement still can drag, include the icon and others children

demo: 
```
const DragHanle = SortableHandle(() => <i className="Insight icon-yidong" />);

    const SortableItem = SortableElement((props) => {
      const { value, active, order } = props;

      return (
        <li className="columnFilter__item" disabled={!active}>
          <label>
            <Checkbox
              checked={active}
              onChange={(event) => {
                triggerSingleColumn.bind(this)(order, event.target.checked, document.getElementsByClassName('columnFilter__option')[0].scrollTop);
              }}
            />
            <span>{value}</span>
          </label>
          {
            active && <DragHanle />
          }
        </li>
```

**Comment by veksa** [comment]
for point 2: you should set useDragHandle flag into SortableContainer to use the SortableHandle in the element.
