### ISSUE TITLE
`Cannot read property 'top' of undefined` when creating new item 

### ISSUE THREAD

**Issue by george-norris-salesforce** [clauderic/react-sortable-hoc#270]
When creating new items that collapse / expand I'm getting a `Cannot read property 'top' of undefined` error

[Codepen example of the issue](https://codepen.io/stoplion/pen/QMzpVL?editors=0010).

• add a new item 
• click `click me to close` 
• Try to reorder that item and the other items..

`Cannot read property 'top' of undefined`  appears.

**Comment by pjshy** [comment]
```javascript
<SortableItem 
     key={`item-${index}`} 
     index={index} 
     value={value} 
      handleClose={handleClose}
 />
```
I believe that the `index` variable used for `key` property should be a unique ID that is related to the data itself instead of current index of the data in an array.

for example
```javascript
<SortableItem 
     key={`item-${value.title}`} 
     index={index} 
     value={value} 
      handleClose={handleClose}
 />
```

**Comment by george-norris-salesforce** [comment]
That fixed it. Closing.
