### ISSUE TITLE
Dragging items from one list to another

### ISSUE THREAD

**Issue by chucksellick** [clauderic/react-sortable-hoc#274]
I'm not sure if this example is supposed to do this; if it is it is broken: http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/multiple-lists?_k=gdkuk9

I want to be able to move items not only within the list, but also from one list to another.

**Comment by varHarrie** [comment]
#138 or [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd/issues/2)

**Comment by clauderic** [comment]
No plans on supporting this for the moment, sorry.
