### ISSUE TITLE
Where do I find the source code for the examples?

### ISSUE THREAD

**Issue by chucksellick** [clauderic/react-sortable-hoc#275]
The examples site has many examples:

http://clauderic.github.io/react-sortable-hoc/

But the source code only has 5:

https://github.com/clauderic/react-sortable-hoc/tree/master/examples

Am I missing something? Where can I see the source code used to create these examples? If it exists somewhere, maybe the docs should link to it.

**Comment by raviteja83** [comment]
@clauderic please add the source code for examples

**Comment by chucksellick** [comment]
I found examples in the end, hidden inside the storybook code:

https://github.com/clauderic/react-sortable-hoc/blob/master/src/.stories/index.js

However, I'm unable to get these working on Windows as node-sass refuses to install/compile on Windows!

**Comment by tricoder42** [comment]
@chucksellick Unfortunately, not all examples are there. For example, [Sortable Table Rows](http://clauderic.github.io/react-sortable-hoc/#/react-virtualized/sortable-table-rows?_k=msobgy) is missing and I can't find it anywhere in this repo.

**Comment by pwhipp** [comment]
All the source is there (or you would not be able to run it locally ;).
I think the storybook was added after some of the examples so some code (the stuff you are after) is in react-sortable-hoc/examples/virtual-table-columns.js. When someone has time, links should be added to get to the source throughout the storybook but you can dig it out as needed in the meantime.
