### ISSUE TITLE
How to prevent flicker after drop?

### ISSUE THREAD

**Issue by derwaldgeist** [clauderic/react-sortable-hoc#280]
I am storing the list order in a Redux store instead of this.state. When an item is dropped at a new position, a callback is executed that eventually causes the Redux state to update, which in effect causes the render() function to be called with the new list order. The function that updates the Redux state is called in an async fashion (still on the client, but not in the same javascript tick).

However, this causes some kind of flickering. After I drop an item at its new position, it is displayed for some short time (only some milliseconds) at its old position, until it finally is visible at the new target position. It seems as if react-sortable-hoc makes the old item visible before the new position is being rendered.

Is there any chance to prevent this kind of flickering, i.e. by preventing the item at the "old" position to become visible again? It works if I store the state in this.state, but it doesn't work if state update is done asynchronously.

**Comment by dbknickerbocker** [comment]
@derwaldgeist - Issue two actions from onSortEnd.  First action will move item to new location in your item list store.  Second will be your asynchronous call to update.  If your async call fails, simply move item back to original location.

**Comment by chrismv48** [comment]
I too am having this problem. I've tried a few different approaches including the one suggested by @dbknickerbocker with no success.

**Comment by derwaldgeist** [comment]
I have solved this by using a local component state to cache the updates. This worked, but requires some additional logic to keep local and redux state in sync.

**Comment by chrismv48** [comment]
After some further testing, I don't think that my issue with the flickering is related to redux. Instead it seems to have to do with the semantic UI card component: https://react.semantic-ui.com/views/card. I'm still not sure what the issue is, but will update this if/when I learn anything new.

**Comment by KasperPKOUT** [comment]
I have this issue with no outside state, the only thing that seems to somewhat fixing it is setting a specific height on my container. This however is not a suitable fix as my height must be dynamic.

**Comment by bmelonis** [comment]
Make sure your item keys aren't mapped to the index as described in https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318.  You may see the flicker in that scenario when your list items have a CSS transition property

**Comment by Rob-Page** [comment]
Double check your UI libraries for global css transitions, I am using ant.design and the component had transitions set for all. I was able to resolve the issue by setting transition: none; on the element. Thanks @bmelonis !

**Comment by funwithtriangles** [comment]
Had the same issue because of Redux. Seems that the redux store updates a fraction of a second too late, causing a slight flicker when the component resets for a second. 

Similarly to @derwaldgeist, I solved the issue by using local state with my component. Had to use `getDerivedStateFromProps` with some slightly cumbersome logic. My example is a little specific to me (e.g. `sceneId`)  but perhaps it will help someone else.

```javascript
class SketchesNav extends React.Component {
  state = {
    items: this.props.items,
    sceneId: this.props.sceneId,
  }

  // We update both internal and external state onSortEnd
  handleOnSortEnd = ({ oldIndex, newIndex }) => {
    this.setState(({ items }) => ({
      items: arrayMove(items, oldIndex, newIndex),
    }))
    // This wont affect the rendering of the component but we need to store the state properly in redux!
    this.props.onSortEnd(this.props.sceneId, oldIndex, newIndex)
  }

  // We update the state based on props if the scene has changed or an item has been added/deleted
  // If only the order has changed, it will just use the internal state (stops the flickering)
  static getDerivedStateFromProps (props, state) {
    if (
      (props.sceneId !== state.sceneId) || // has the scene changed?
      (props.items && state.items && props.items.length !== state.items.length) // has an item been added or removed?
    ) {
      return {
        items: props.items,
        sceneId: props.sceneId,
      }
    }
    return null
  }

  render () {
    return <SortableList items={this.state.items} onSortEnd={this.handleOnSortEnd} />
  }
}
```

**Comment by bilobom** [comment]
Make sure that caching is not disabled in ChromeDevTool
![image](https://user-images.githubusercontent.com/19841175/95988268-91a23080-0e20-11eb-8961-acc4a79e86b6.png)
