### ISSUE TITLE
Links displaying inside sortable element not working

### ISSUE THREAD

**Issue by wiredin** [clauderic/react-sortable-hoc#281]
Links displayed inside the sortable element do not work, looks like the default behavior of the `<a href>` is being prevented.

Example
https://jsfiddle.net/6r7r2cva/207/

Thanks!

**Comment by anthonyjonahs** [comment]
@wiredin , I solved this problem with the `pressDelay` prop on my `SortableContainer` element. I went with the recommended 200 ms and it works really well for a click event. 

The `distance` prop also works equally well. It might even be the better option, now that I think of it.

Note that `pressDelay` and `distance` cannot be used together. 

Hope this helps!

**Comment by clauderic** [comment]
You can get around this problem by defining your own implementation of `shouldCancelStart`
