### ISSUE TITLE
Scroll Not working while dragging with the JSFiddle 

### ISSUE THREAD

**Issue by achyutjhunjhunwala** [clauderic/react-sortable-hoc#282]
The JSFiddle Link provided does not have the option of page scrolling when the trying to drag item at 1 st place to 100th place - https://jsfiddle.net/clauderic/6r7r2cva/

But the examples here - http://clauderic.github.io/react-sortable-hoc/#/react-infinite/basic-usage?_k=t5vdof

All support scroll of the container when dragging. Can someone provide update to the fiddle and highlight whats missing

**Comment by achyutjhunjhunwala** [comment]
I realised the parent container was not scrollable hence the issue. I was able to get the scroll using CSS. But the problem is when the scroll starts happening, the Drag's Drop position starts increasing incrementally. Considering my viewport displays 10 items and I have total 100 items. Now when I start dragging item 1 to anywhere within 1-10, the items shift properly wherever my mouse is and I can drop the element. But once the page scroll starts this offset starts increasing. It's like my mouse is over 20th element but the position for drop has been created at 30th element

**Comment by achyutjhunjhunwala** [comment]
Closing issue as issue was purely CSS. The Sortable Container needs to have a height and overflow-y: scroll

**Comment by markau** [comment]
Thanks from the future for the followup comment @achyutjhunjhunwala.

**Comment by stellarbelle** [comment]
@achyutjhunjhunwala Thanks! I needed to add the height, big help :)

**Comment by saba-shaikh** [comment]
How to make this work if using `react-virtualized` list with Autosizer?

**Comment by valentindotxyz** [comment]
Late to the party but any advice to have it worked properly with `AutoSizer` from `react-virtualized` too? 👀

**Comment by de326729** [comment]
> Late to the party but any advice to have it worked properly with `AutoSizer` from `react-virtualized` too? 👀

Stuck in the same scenario...got any solution??
