### ISSUE TITLE
Textareas and inputs inside the SortableItem dont move.

### ISSUE THREAD

**Issue by LSDD** [clauderic/react-sortable-hoc#284]
Hello there,

I am not sure if this is a bug or not but is there a reason that textarea's and input fields inside the sortable item do not move into the new position. 

See example -> https://codepen.io/lsdd/pen/OxpKad
notice the content in the textarea returns to the old once it has been dropped.

Thanks!

**Comment by sebastianoblom** [comment]
change defaultValue to value on your textareas - defaultValue is only for initial load.

**Comment by clauderic** [comment]
As @sebastianoblom, you have to use `value` on your inputs, not `defaultValue`. Closing as this isn't an issue with `react-sortable-hoc` per-se

**Comment by Rachomir** [comment]
what if there is no value or defaultValue set? because I am also having the same issue
```  render () {
    return (
      <div>
        <BroadcastPreferencesForm selectedFanpage={this.props.selectedFanpage}
          addComponent={this.mountComponent} sexFemale={this.sexFemale} sexMale={this.sexMale}
          saveBroadcast={this.saveBroadcast} language={this.chooseLanguage} timezone={this.chooseTimezone}
          date={this.setDate} />
        <SortableList items={this.state.items} onSortEnd={this.onSortEnd}
          unmountComponent={(index) => this.unmountComponent(index)}
          handleTextChange={(text) => this.handleTextChange(text)} />
      </div>
    )
  }
}

export default withRouter(createContainer(props => ({
  ...props
}), BroadcastForm))

const SortableItem = SortableElement(({value, index, unmountComponent, handleTextChange}) => {
  console.log(value, index)
  return <li><BroadcastTextMessageForm unmountComponent={(component) => unmountComponent(component)}
    handleTextChange={(text) => handleTextChange(text)} /></li>
})

const SortableList = SortableContainer(({items, unmountComponent, handleTextChange}) => {
  return (
    <ul>
      {items.map((value, index) => (
        <SortableItem key={`item-${index}`} index={index} value={value}
          unmountComponent={unmountComponent} handleTextChange={handleTextChange}
        />
      ))}
    </ul>
  )
})```

and component with textarea tag code
```
import React from 'react'
import { createContainer } from 'react-meteor-data'
import { withRouter } from 'react-router'
import { BroadcastFormSceleton } from './BroadcastForm'

import './BroadcastTextMessageForm.scss'

export class BroadcastTextMessageForm extends React.Component {
  constructor (props) {
    super(props)
    this.handleChange = this.handleChange.bind(this)
    this.unmountComponent = this.unmountComponent.bind(this, this.props.componentId)
  }

  handleChange (e) {
    console.log(e.target.value)
    this.props.handleTextChange(e.target.value)
  }

  unmountComponent (id) {
    this.props.unmountComponent(id)
  }

  render () {
    const textMessage = this.props.textMessage
    return (
      <BroadcastFormSceleton>
        <div className='textarea-container p-3'>
          <textarea id='broadcast-message' className='form-control' value={textMessage} onChange={this.handleChange} />
        </div>
        <div className='float-right'>
          <button type='button'
            onClick={this.unmountComponent}
            className='btn btn-danger btn-outline-danger button-danger btn-small mr-3 mt-3'>
            DELETE
          </button>
        </div>
      </BroadcastFormSceleton>
    )
  }
}

export default withRouter(createContainer(props => ({
  ...props
}), BroadcastTextMessageForm))
```

**Comment by Rachomir** [comment]
fixed

**Comment by kshitijsharma-kiwi** [comment]
I am also facing same issue. How you got it fixed?

**Comment by matatsuna** [comment]
Me too this issue.
I resolved this problem in the article.
https://stackoverflow.com/questions/44649898/react-sortable-hoc-with-formdata
