### ISSUE TITLE
Opacity on drag

### ISSUE THREAD

**Issue by artooras** [clauderic/react-sortable-hoc#285]
Is the opacity of the SortableElement being altered during the sorting (dragging) action?

I use opacity animation for removing items from the list. However, I get a side-effect of items being animated onSortEnd - seems like the animation of opacity 1 > 0 > 1 - which I don't want.

Can this be overridden?

**Comment by silvenon** [comment]
Does setting `hideSortableGhost` to `false` on the sortable container help?

**Comment by artooras** [comment]
It does actually help. But then... I see the sortable ghost, which I don't want.

**Comment by artooras** [comment]
Also, I have changed the implementation of my animation since the original question and am now using ReactCSSTransitionGroup to handle this, and the problem still persists.

Another strange thing is that this happens only when I drag the item up the list, but not down. It looks like the implementation in both cases is different:
* When an item is being dragged down the list, there IS NOT hide/show animation - the item is neither removed nor added to the array, merely moved.
* When an item is being dragged up the list, there IS hide/show animation - it's as if when dragging up the list the item is actually removed and then added from/to an array.

**Comment by silvenon** [comment]
Could you please create a demo on https://codesandbox.io/?

**Comment by artooras** [comment]
I have since updated my implementation, and I don't see the behaviour I have described previously. I am therefore closing this issue. Thanks!
