### ISSUE TITLE
Cloning Items does not allow for changes in their content

### ISSUE THREAD

**Issue by Goues** [clauderic/react-sortable-hoc#286]
Use case: I have a list of items. My items includes UI for editing them but this UI is rather complex and covers a lot of space. I want to hide it, when user starts dragging and display it when he stops.

I'm using redux in my app, so I dispatch and action in onSortStart event listener.

Probem: Sortable HOC clones the Item before dispatching any events, so my state doesn't get modified and Sortable HOC clones the Item with all of the UI in it.

Solution:
A) Add onBeforeSortStart event that could be used to modify Item before cloning
B) Do not clone nodes as DOM and use props.children with React.cloneElement() to copy Items instead

**Comment by schnubor** [comment]
+1

Having the exact same problem. I can't modify my store using `onSortStart` since it breaks sortable and throws

``` setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the sortableList component.```

**Comment by Goues** [comment]
@schnubor I just used `helperClass` to hide extra elements by CSS, it's ok for now.

**Comment by clauderic** [comment]
You can use the newly introduced `updateBeforeSortStart` prop for this purpose
