### ISSUE TITLE
useWindowAsScrollContainer is not working in ie10&ie11

### ISSUE THREAD

**Issue by thengor** [clauderic/react-sortable-hoc#291]
The useWindowAsScrollContainer prop is useful when the list is large, but it does not work in ie.
 It seems this bug is still not fixed. [#58](https://github.com/clauderic/react-sortable-hoc/issues/58)

**Comment by barry800414** [comment]
Actually it is also not working in chrome

**Comment by clauderic** [comment]
`useWindowAsScrollContainer ` was fixed in `0.7.0` thanks to #306, if you still experience issues with this, feel free to reopen
