### ISSUE TITLE
Not able to select text inside Sortable Items.

### ISSUE THREAD

**Issue by rabishah** [clauderic/react-sortable-hoc#292]
```
const SortableItem = SortableElement(({value}) =>
  <li><p>I wan to select this text.</p></li>
);
```
How can I differentiate between selecting the text inside vs dragging the container?

**Comment by inthedeepend** [comment]
Also trying to figure this out

**Comment by dbknickerbocker** [comment]
See - [#41](https://github.com/clauderic/react-sortable-hoc/issues/41), Set distance={1} on SortableContainer.

**Comment by AnthonyWhitaker** [comment]
Make sure to remove `user-select: none;` from the element you want to be selectable (and all parent elements).

I added a drag handle to ensure the UX worked as expected. ([see demo here](http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/drag-handle?_k=oehid0)) Note that in this demo they're using `user-select: none;` on the sortable item (which will disable text selection).

If you don't want a drag handle, you probably would want `user-select: none;` on the sortable item and add `user-select: auto;` on the child elements that you want to be selectable.

**Comment by clauderic** [comment]
As mentioned by @AnthonyWhitaker, you can add a drag handle so that only the handle is draggable, or you could also use the `pressDelay` prop
