### ISSUE TITLE
Select multiple items for sorting

### ISSUE THREAD

**Issue by modemmute** [clauderic/react-sortable-hoc#296]
An idea that would be helpful - a methodology for selecting multiple items that can be dragged together. Users could click on an item to highlight it, then allowing for shift-click or command/control-click to highlight additional items then drag them with all as a group with handles. Grouping wouldn't be limited to neighbors, as non-contiguous items could be selected too and then those items would land together where the drop event is called.

**Comment by sbr464** [comment]
You can check the source here for similar functionality - https://github.com/reactual/react-multi-sortable-hoc-demo

**Comment by clauderic** [comment]
This is already possible without any changes to the core of `react-sortable-hoc`, and I've now added an example for how to do it, see: https://github.com/clauderic/react-sortable-hoc/tree/master/src/.stories/grouping-items

<img src="https://user-images.githubusercontent.com/1416436/54495093-437d2200-48b7-11e9-885b-05e64c554615.gif" width="400" />

**Comment by lombardo2** [comment]
I'm sorry for commenting on such an old issue, but I think its better than creating a new issue. @clauderic in your example the positioning of items is not correct if the drag is not started with the first item. The library doesn't expose the underlying SortableContainer handle functions, so I can't override them with my own to fix the issue. Any ideas on how I could proceed to fix that?
