### ISSUE TITLE
Use this library without react ?

### ISSUE THREAD

**Issue by Johngtrs** [clauderic/react-sortable-hoc#303]
It's possible to use this sortable list items without using react framework ? I just have JQuery in my project. I like how the drag & drop is smooth

**Comment by mk0x9** [comment]
Check out https://github.com/bevacqua/dragula

**Comment by clauderic** [comment]
You can also check https://github.com/shopify/draggable 😄

**Comment by Johngtrs** [comment]
I ever seen these libraries but the animation isn't smooth is this react library :/
