### ISSUE TITLE
Request: Nested Sortable

### ISSUE THREAD

**Issue by maxsalven** [clauderic/react-sortable-hoc#31]
Fantastic library, thank you. An idea for a potential feature:

A page shows multiple sets of Todos:

TodoList Category A:
- TodoItem A.1
- TodoItem A.2

TodoList Category B:
- TodoItem B.1
- TodoItem B.2

I'd like to be able to:
1. Move a TodoItem from Category A to B
2. Move the entire TodoList Category B above TodoList Category A

Update: Looks like item 2 is almost working perfectly already. I am only running into a bug where a dragHandle on a TodoItem which is disabled is causing the parent TodoList to get dragged.

**Comment by clauderic** [comment]
@maxsalven regarding item 1, I believe that would require a sizeable amount of work. I'd be happy to help / guide you in the right direction if you want to spend time working on a PR for this, but it's not something I currently have time to look into.

As for item 2, can you replicate the behaviour you're seeing with the dragHandle in a jsfiddle? You can fork this [fiddle](https://jsfiddle.net/clauderic/6r7r2cva/)

**Comment by maxsalven** [comment]
@clauderic 
https://jsfiddle.net/aLoyzpgr/1/
Drag handles on items A1 and A2, which are `disabled` cause the entire section to move. Items B1 and B2, which are `not disabled`, work fine.

Re: working on moving items between parent categories, unfortunately I don't have capacity at the moment, sorry.

**Comment by Robinfr** [comment]
I'm pretty sure you can already do item 2 (since I'm doing something similar in a project) and item 1 is being worked on in #138  which I hope will also soon be implemented. :smile:
