### ISSUE TITLE
List Virtualization + Grid layout?

### ISSUE THREAD

**Issue by blord-fullscreen** [clauderic/react-sortable-hoc#315]
I see that there's no demo for this. 😄 

I have dealt with virtualization by grouping `<sortableElement>`s into rows. I can then manage the rows using the standard libraries. So I have something like:

```
<sortableList axis="xy">
   <Row rowindex=0>
      <sortableElement sortableIndex=0 columnIndex=0>
      <sortableElement sortableIndex=1 columnIndex=1>
      <sortableElement sortableIndex=2 columnIndex=3>
   </Row>
   <Row rowindex=1>
      <sortableElement sortableIndex=3 columnIndex=0>
      <sortableElement sortableIndex=4 columnIndex=1>
      <sortableElement sortableIndex=5 columnIndex=3>
   </Row>
```
All elements are the same width and height. I am not explicitly defining `collection`, so all elements are collection `0`.

My problem is that when I drag an item, only its siblings in the same row reflow during drag. If I drag `sortableIndex=4` over `sortableIndex=1`, nothing happens in the first row. The second row reflows down to just two elements.  So I'm stuck. The library appears to require that elements be siblings. But virtualization seems to require grouping Components into rows. Is there any way around this?

Sorry for what may sound like a personal support request, but because this may verge on a feature request I thought it made sense to ask "on the record". Thanks .

**Comment by kraenhansen** [comment]
@blord-fullscreen see my comment on https://github.com/clauderic/react-sortable-hoc/issues/295#issuecomment-344070823

**Comment by blord-fullscreen** [comment]
I solved the main part of this problem by using react-virtualized `<Grid>`, which keeps cells in the grid as absolutely-positioned siblings. However, there is a bug when drag-scrolling down, which I've created a demo of here:

https://github.com/clauderic/react-sortable-hoc/pull/326

which I hope can be separately addressed.

**Comment by chaomao** [comment]
I build an example, react-virtualized grid + sortable hoc based on @blord-fullscreen (thanks), feel free to take it.
https://codesandbox.io/s/chaomao-virtual-grid-drag-q6jku
