### ISSUE TITLE
JSFiddle issue template provided in README is broken

### ISSUE THREAD

**Issue by wiredin** [clauderic/react-sortable-hoc#319]
https://jsfiddle.net/clauderic/6r7r2cva/

![screenshot 2017-11-24 at 2 31 30 pm](https://user-images.githubusercontent.com/1058989/33222315-4f51be4e-d124-11e7-8e32-36891b862733.png)

**Comment by clauderic** [comment]
Thanks for the heads up, I updated the link to CodeSandbox, please fork this sandbox from now on to report issues https://codesandbox.io/s/o104x95y86
