### ISSUE TITLE
Changing cursor to grab/grabbing with dragHandle

### ISSUE THREAD

**Issue by saadq** [clauderic/react-sortable-hoc#328]
If anyone could provide an example with how I can use a `grab` and `grabbing` cursor with a drag handle, that would be great. Right now, no matter what CSS I try to use, the cursor seems to always go to `default` when dragging is active.

Edit: Closing this, I ended up using a workaround where I just applied a class to the whole document body

**Comment by dagadbm** [comment]
for other people who bump in here: https://github.com/clauderic/react-sortable-hoc/issues/253

this issue (and all the links there) can provide you with tips on ways to do this.

**Comment by zackify** [comment]
FYI heres's how i did it:

```js
onSortStart={() => (document.body.style.cursor = 'grabbing')}
onSortEnd={({ newIndex, oldIndex }: any) => {
    document.body.style.cursor = 'default';
...
```
then on your drag handler make sure to put `cursor: grab` on it

**Comment by t3db0t** [comment]
Thank you for this @zackify —I would never have figured this out :( This should be documented somewhere :/

**Comment by zackify** [comment]
Completely agree. I searched forever then figured this out 😂 I don’t like having to call document methods inside react. But oh well!

**Comment by neckro** [comment]
A somewhat improved version of @zackify 's method.  I wanted the cursor to change immediately on click for user feedback.  Still pretty hacky, and there's a cursor flash if you release the mouse button over the drag handle or happen to pass over any elements that change cursor while you're dragging:

```tsx
const GroupDragHandle = SortableHandle((): React.ReactElement => {
  return (
    <DragHandleIcon
      onMouseEnter={ (): void => { if (document.body.style.cursor !== 'grabbing') document.body.style.cursor = 'grab' } }
      onMouseLeave={ (): void => { if (document.body.style.cursor === 'grab') document.body.style.cursor = '' } }
      onMouseDown={ (): void => { document.body.style.cursor = 'grabbing' } }
    />
  );
});
```
...then on the SortableList itself:
```tsx
onSortEnd={ (): void => { document.body.style.cursor = 'default'; } }
```

**Comment by aeh21** [comment]
Thanks @neckro it works the way I need it. Could you tell me please what the void operator does there?

**Comment by uladkasach** [comment]
It is possible to do this with only changing one component:
```ts
  const SortableList = SortableContainer(({ items }: { items: typeof values }) => (
    <div
      className="sortable_list_container" 
      style={{ cursor: 'grab' }}
      onMouseDown={() => document.querySelectorAll('.sortable_list_container').forEach((el) => ((el as HTMLElement).style.cursor = 'grabbing'))}
      onMouseUp={() => document.querySelectorAll('.sortable_list_container').forEach((el) => ((el as HTMLElement).style.cursor = 'grab'))}
    >
      {items.map((item, index) => (
        <SortableItem key={keys[index]} index={index} item={item} />
      ))}
    </div>
  ));
```

Where className is used, instead of id, to support more than one "sortable list" per document.

**Comment by neckro** [comment]
> Thanks @neckro it works the way I need it. Could you tell me please what the void operator does there?

Sorry for not checking my notifications.  That's Typescript -- you can remove the `: void` and the `: React.ReactElement` type hints for plain JS.

**Comment by arosisi** [comment]
> FYI heres's how i did it:
> 
> ```js
> onSortStart={() => (document.body.style.cursor = 'grabbing')}
> onSortEnd={({ newIndex, oldIndex }: any) => {
>     document.body.style.cursor = 'default';
> ...
> ```
> 
> then on your drag handler make sure to put `cursor: grab` on it

Just to add to @zackify 's approach, to make sure that the cursor will not change when you drag over, say a button (it may change to a pointer), you can do this:

```js
onSortStart={() => (document.body.className = 'grabbing')}
onSortEnd={({ newIndex, oldIndex }: any) => {
  document.body.className = '';
...
```

where `grabbing` is

```css
grabbing {
  cursor: grabbing;
}
grabbing * {
  cursor: grabbing;
}
```

**Comment by mpiorowski** [comment]
@arosisi Your solution works like a charm :+1: It should be in the doc. Team Work power, thx guys ;p

**Comment by Chaoste** [comment]
> > FYI heres's how i did it:
> > ```js
> > onSortStart={() => (document.body.style.cursor = 'grabbing')}
> > onSortEnd={({ newIndex, oldIndex }: any) => {
> >     document.body.style.cursor = 'default';
> > ...
> > ```
> 
> Just to add to @zackify 's approach, to make sure that the cursor will not change when you drag over, say a button (it may change to a pointer), you can do this:
> 
> ```js
> onSortStart={() => (document.body.className = 'grabbing')}
> onSortEnd={({ newIndex, oldIndex }: any) => {
>   document.body.className = '';
> ...
> ```
> 
> where `grabbing` is
> 
> ```css
> grabbing {
>   cursor: grabbing;
> }
> grabbing * {
>   cursor: grabbing;
> }
> ```

I would like to add another improvement. This would erase all other classes on the body. Assuming that other features on the webpage might also want to add classes to the body, I recommend using:

```js
onSortStart={() => (document.body.classList.add('grabbing'))}
onSortEnd={({ newIndex, oldIndex }: any) => {
  document.body.classList.remove('grabbing');
})}
```

[Full browser support](https://caniuse.com/?search=classList.add)
