### ISSUE TITLE
Drag preview is broken with react-chart-js

### ISSUE THREAD

**Issue by pritam1994** [clauderic/react-sortable-hoc#330]
react-version : ^15.4.5
react-sortable-hoc-version: ^0.6.8
react-chart-js-version: ^2.5.6

I have few cards in view and each card containing a chart (bar or pie). While dragging chart is getting disappeared.

**Comment by clauderic** [comment]
Fixed in https://github.com/clauderic/react-sortable-hoc/commit/43ad122bbed56b9ece79e48ff2d08d30a6503554
