### ISSUE TITLE
Disable drag option

### ISSUE THREAD

**Issue by Joci933** [clauderic/react-sortable-hoc#331]
Is there any option to disable drag on first, second or X element?

**Comment by deepank411** [comment]
any update on this?

**Comment by benlonsdale** [comment]
You could achieve this using a drag handle, and just not rendering the handle on the ones you want locked

**Comment by clauderic** [comment]
Yes, set the `disabled` prop to true on the `SortableElement`, https://github.com/clauderic/react-sortable-hoc#sortableelement-hoc

**Comment by shadrech** [comment]
Sorry for coming back to this, but small question @clauderic 
If in the Component with the `SortableContainer` I have a state variable which I use to disable/enable drag for all `SortableElements`, and I toggle this state variable using `setState`, is there a way I can do this without making react-sortable-hoc delete the Nodes?
![screenshot 2019-03-04 at 02 45 00 2](https://user-images.githubusercontent.com/6001129/53707768-3b89a080-3e28-11e9-9667-a0187227759b.jpg)
I don't want each draggable item to be deleted as I want to keep each individual local state, but just have the disabled prop updated for each element without deleting the node (which will cause it to be removed from dom and reconstructed). Is there a way to do this?

**Comment by jamesahuang** [comment]
https://github.com/jamesahuang/react-sortable-hoc/commits/disableFirst
![image](https://user-images.githubusercontent.com/44989190/59586502-aaf47900-9115-11e9-9c95-0b408ab8ca6f.png)
