### ISSUE TITLE
windowAsScrollcontainer broken in several browsers

### ISSUE THREAD

**Issue by ambewas** [clauderic/react-sortable-hoc#332]
go to http://clauderic.github.io/react-sortable-hoc/#/advanced/window-as-scroll-container?_k=polrhw

**Expected behaviour:**
list should scroll automatically when dragging & dropping to top or bottom

**observed**:
Not scrolling in chrome / firefox on a mac
Works on safari.

**Comment by skrln** [comment]
I appear to have the same problem on Windows/Chrome and Windows/Firefox.

**Comment by clauderic** [comment]
Fixed in #306
