### ISSUE TITLE
Sortable Transition Conflicts with other transitions

### ISSUE THREAD

**Issue by jacobp100** [clauderic/react-sortable-hoc#334]
Say I have a list, and each item in the list has a `background-color`. The background color can change, so we put a `transition: background 0.5s linear`.

This disables the sortable transition, so we extend this to `transition: background 0.5s linear, transform 0.3s ease`.

However, this transform transition sticks around after the list is reordered. If you take item 2 and drag it into position 2, the following happens:

* Item 2 is given a transform (e.g. `translateY(-20px)`)
* The items in the DOM are re-ordered, and item 2's transform is reset

Because the transform went from `translateY(-20px)` to (effectively) `translate(Y)`, when the items in the DOM are re-ordered, item 2 is initially shifted, and transitions into its normal place.

See below for an example (animations slowed down)

![ezgif-3-4f4925107e](https://user-images.githubusercontent.com/7275322/35037048-271c7d28-fb6e-11e7-9e28-7711416243ef.gif)

Is there a nice way to handle this?

#### Workaround

If I reorder my transition to read `transform 0s ease, background 0.5s linear`, when you set `transition-duration: 300`, it'll update the first transition (but also clear the backgound transition).

**Comment by CyanoFresh** [comment]
bump
material-ui listitem same issue

**Comment by zilahir** [comment]
@jacobp100 hi! just to cause you some nice minutes, thanks for posting this! i was struggling to figure out the problem, and it was a great hint that the transitions might conflicts with other transitions! :) 

so, thanks again! 🤝
