### ISSUE TITLE
Problems when updating state

### ISSUE THREAD

**Issue by voipster** [clauderic/react-sortable-hoc#336]
When updating state to a different list, I was getting errors 'cannot remove child'. Narrowed this down to code like this in my li:

`{(x>0) ? 
<span className="fa fa-user"></span>
: '' }`

so I changed it so that a variable would hold the classnames, and would either be blank, or have the icon classes. So now it's either:

`<span className="fa fa-user"></span>`

or

`<span className=""></span>`

But now, the icon stays static and isn't removed when switching state/lists. Is there a method I can call to force an update?

**Comment by voipster** [comment]
The state is holding the correct details, but the change in state is not being entirely reflected in the sortable element.

**Comment by qheolet** [comment]
I have same issue here., any way to solve? thanks

**Comment by voipster** [comment]
I managed to get round it by specifying the fontawesome code in CSS, instead of in the React code. For some reason this updates correctly.

So I pass the class to the span via a prop:

`<span className={props.source}></span>`

...(for this example, the value is 'mine') and then add the fontawesome code in CSS :after for that class:

```
.mine:after {
  font-family: FontAwesome;
  content: "\f007";
}
```
