### ISSUE TITLE
Can't find react-virtualized Grid layout implementation

### ISSUE THREAD

**Issue by R-iskey** [clauderic/react-sortable-hoc#337]
Hi Guys, I've searched many examples of react-sortable-hoc integration with react-virtualized Grid layout, but can't find any good example.
Maybe someone have a good example or smth. ?

**Comment by Necmttn** [comment]
Duplicate of #295 
check the example https://github.com/clauderic/react-sortable-hoc/issues/295#issuecomment-344070823

**Comment by chaomao** [comment]
I build a example, react-virtualized grid + sortable hoc, feel free to take it.
https://github.com/clauderic/react-sortable-hoc/issues/337
