### ISSUE TITLE
Element looses styling when dragging

### ISSUE THREAD

**Issue by MichaelA59** [clauderic/react-sortable-hoc#338]
I've tried the solutions I have found related to this issue already but nothing is working. Originally, everything disapeared behind a popup modal I had. Then I applied `z-index: 99999999 !important` to the `SortableList helperClass='sortableHelper' ...` which allowed the text to come through but it's acting strange

1) The bullet point for the `li` is visible when dragging
2) All of the styling for the element is lost (no box around the text)

Here's my code

```
import React, { Component, PropTypes } from 'react';
import { SortableContainer, SortableElement, arrayMove } from 'react-sortable-hoc';

const OPTIONS = {
    Experience : 'Experience',
    Affordability: 'Price',
    Closest: 'Proximity',
}

const SortableItem = SortableElement(({value, sortIndex}) =>
  <li>#{sortIndex + 1} - {value}</li>
);

const SortableList = SortableContainer(({items}) => {
  return (
    <ul>
      {items.map((value, index) => (
        <SortableItem
          key={`item-${index}`}
          index={index}
          sortIndex={index}
          value={OPTIONS[value]}
        />
      ))}
    </ul>
  );
});

export default class Sortableist extends Component {
  constructor (props) {
    super(props);
    this.state = {
      items: this.props.data,
    }
    this.onSortEnd = this.onSortEnd.bind(this);
  }

  onSortEnd({oldIndex, newIndex}) {
    this.setState({ items: arrayMove(this.state.items, oldIndex, newIndex) });
    this.props.updateList(this.state.items);
  }

  render() {
    return (
      <SortableList
        helperClass='sortableHelper'
        items={this.state.items}
        onSortEnd={this.onSortEnd}
      />
    );
  }
}
```

and that's all being called from here...

```
<Sortableist
   data={SORTING_OPTIONS}
   updateList={this.updateList}
/>
```

**Comment by MichaelA59** [comment]
I just copied the styling for the `li`s to the new helperClass. The only issue I am having now is getting `list-style: none;` to the parent `<ul>`

**Comment by sifloz** [comment]
@MichaelA59 
Hello, 

I'm quite new to React and to this react-sortable-hoc component, I'm facing the same issue as you did; The bullet point for the li is visible when dragging. I still haven't found a way to make it invisible when dragging. I see some people have donde something like this:

```
// someStyleFile.css
.sortableHelper {
  z-index: 10000 !important;
}

// MyComponent.js
 <SortableItem 
            key={`${index}`} 
            index={index} 
            helperClass='sortableHelper'
/>
```

However, this way doesn't work for me, I still see the bullet on each <li> when dragging. Could you please explain with code what you did in order to solve this? 

Thank you for taking the time to read me.

**Comment by RageOfJustice** [comment]
@sifloz make sure you have `list-style: none;` on the `li` item. I mean literally on the **list item** and not the list. 
The library create clone of the sortable item outside of the list. If you have structure like `ui>li` you need to set the css rule to avoid appearing a dot
