### ISSUE TITLE
Needed Help to Make Redux-Form Field Arrays Sortable

### ISSUE THREAD

**Issue by navotaras** [clauderic/react-sortable-hoc#340]
Hello, I am trying to wire up redux-form array fields ( see example below ) and make it sortable using react-sortable-hoc components. I am not able to make any progress.  Need help and guidance.

https://redux-form.com/7.2.3/examples/fieldarrays/

**Comment by navotaras** [comment]
`import React, { Component } from 'react';
import { Field, FieldArray, reduxForm } from 'redux-form';
import {
	SortableContainer,
	SortableElement,
	arrayMove
} from 'react-sortable-hoc';

const renderField = ({ input, label, type, meta: { touched, error } }) => (
	<div>
		<label>{label}</label>
		<div>
			<input {...input} type={type} placeholder={label} />
			{touched && error && <span>{error}</span>}
		</div>
	</div>
);

const SortableItem = SortableElement(({member, fields, index}) => (
	<li key={index}>
		<button
			type="button"
			title="Remove Member"
			onClick={() => fields.remove(index)}
		/>
		{console.log('The member name is ', member)}
		{console.log('the value of the index is ', index)}

		<h4>Member #{index + 1}</h4>
		<Field
			name={`${member}.firstName`}
			type="text"
			component={renderField}
			label="First Name"
		/>
		<Field
			name={`${member}.lastName`}
			type="text"
			component={renderField}
			label="Last Name"
		/>
	</li>
));

const renderMembers = SortableContainer(
	({ fields, meta: { error, submitFailed } }) => (
		<ul>
			<li>
				<button type="button" onClick={() => fields.push({})}>
					Add Member
				</button>
				{submitFailed && error && <span>{error}</span>}
			</li>
			{fields.map((member, index, fields) => {
				console.log(member, index, fields);
				return <SortableItem key={`item-${index}`} index={index} fields={fields} member={member} />;
			})}
		</ul>
	)
);

const SortableFieldArraysForm = props => {
	const { handleSubmit, pristine, reset, submitting } = props;
	return (
		<form onSubmit={handleSubmit}>
			<Field
				name="clubName"
				type="text"
				component={renderField}
				label="Club Name"
			/>
			<FieldArray name="members" component={renderMembers} />
			<div>
				<button type="submit" disabled={submitting}>
					Submit
				</button>
				<button type="button" disabled={pristine || submitting} onClick={reset}>
					Clear Values
				</button>
			</div>
		</form>
	);
};

export default reduxForm({
	form: 'fieldArraysSortable' // a unique identifier for this form
})(SortableFieldArraysForm);
`

**Comment by navotaras** [comment]
![image](https://user-images.githubusercontent.com/34484150/35900704-5bb3479a-0ba1-11e8-8793-69e10e3989b1.png)

The first one shows the picture of how the array fields are rendering fine. 
The below picture shows that when I click on something to move everything vanishes. I have given the code below for both my component and store initialization

![image](https://user-images.githubusercontent.com/34484150/35900734-82c769b0-0ba1-11e8-876e-3e95c2de5753.png)

import React, { Component } from 'react';
import { Field, FieldArray, reduxForm } from 'redux-form';
import {
	SortableContainer,
	SortableElement,
	arrayMove
} from 'react-sortable-hoc';

const renderField = ({ input, label, type, meta: { touched, error } }) => (
	<div>
		<label>{label}</label>
		<div>
			<input {...input} type={type} placeholder={label} />
			{touched && error && <span>{error}</span>}
		</div>
	</div>
);

const SortableItem = SortableElement(({member, fields, itr:index}) => {
	return (
	<li key={index}>
		<button
			type="button"
			title="Remove Member"
			onClick={() => fields.remove(index)}
		/>
		{console.log('The member name is ', member)}
		{console.log('the value of the index is ', index)}

		<h4>Member #{index + 1}</h4>
		<Field
			name={`${member}.firstName`}
			type="text"
			component={renderField}
			label="First Name"
		/>
		<Field
			name={`${member}.lastName`}
			type="text"
			component={renderField}
			label="Last Name"
		/>
	</li>
)});

const AmpedSortableItem = WrappedSortableItemComponent => {
	return ({ member, fields, itr }) => <div>
			<WrappedSortableItemComponent {...{ member, fields, itr }} />
		</div>;
};

export const NewSortableItem = AmpedSortableItem(SortableItem);

const renderMembers = SortableContainer(
	({ fields, onSortEnd, meta: { error, submitFailed } }) => {
			
		onSortEnd = ({ oldIndex, newIndex }) => {
				arrayMove(fields, oldIndex, newIndex)
		};

		return (
		<ul>
			<li>
				<button type="button" onClick={() => fields.push({})}>
					Add Member
				</button>
				{submitFailed && error && <span>{error}</span>}
			</li>
			{fields.map((member, index, fields) => {
				console.log(member, index, fields);
				return <NewSortableItem key={`item-${index}`} itr={index} fields={fields} member={member} />;
			})}
		</ul>
	)}
);

const SortableFieldArraysForm = props => {
	const { handleSubmit, pristine, reset, submitting } = props;
	return (
		<form onSubmit={handleSubmit}>
			<Field
				name="clubName"
				type="text"
				component={renderField}
				label="Club Name"
			/>
			<FieldArray name="members" component={renderMembers} />
			<div>
				<button type="submit" disabled={submitting}>
					Submit
				</button>
				<button type="button" disabled={pristine || submitting} onClick={reset}>
					Clear Values
				</button>
			</div>
		</form>
	);
};

export default reduxForm({
	form: 'fieldArraysSortable' // a unique identifier for this form
})(SortableFieldArraysForm);


----------------------------------------------------------
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { Values } from 'redux-form-website-template';
import store from './playground/store';
import showResults from './playground/showResults';
import SortableFieldArraysForm from './playground/sortablelistwithreduxform'
import registerServiceWorker from './registerServiceWorker';

// Playground Examples
import { RenderFields, NewRenderFields } from './playground/hocexample';
const rootEl = document.getElementById('root');

ReactDOM.render(
	<Provider store={store}>
		<div style={{ padding: 15 }}>
			<SortableFieldArraysForm onSubmit={showResults} />
			<Values form="fieldArraysSortable" />
		</div>
	</Provider>,
	rootEl
);

registerServiceWorker();

**Comment by mrchief** [comment]
Maybe you can adapt from here: https://codesandbox.io/s/6zxjpv31pn
