### ISSUE TITLE
Problem with grid sorting 

### ISSUE THREAD

**Issue by fakob** [clauderic/react-sortable-hoc#346]
First thanks for this sortable component. It was just what I had needed. 
But somehow I am having trouble getting the grid sorting to work properly. I am not sure what I am doing wrong, but I can't seem to get the stability you show in your example.

When I move an item to a new spot, it seems that only temporarily the other items move out of the way. But then they ignore the own dragged, which results in that it usually jumps to the end. 
Any idea what I am doing wrong?

Here is how it looks:
![react-sortable-hoc-problem](https://user-images.githubusercontent.com/4619772/36693410-7f9fcbfc-1b3b-11e8-805c-da5affbfc92c.gif)

**Comment by fakob** [comment]
Seems that as my SortableContainer was somewhere nested further down in the DOM, setting
`useWindowAsScrollContainer=true` fixed the issue.

**Comment by lacymorrow** [comment]
I spend weeks on this undocumented feature, I finally found a working answer here: https://codesandbox.io/embed/0nnq0kv2l
