### ISSUE TITLE
Request: Don't start dragging unless cursor been dragged x pixels.

### ISSUE THREAD

**Issue by tornstrom** [clauderic/react-sortable-hoc#35]
I ran into an issue where I have items that expand when clicked. When making them sortable they no longer respond to a click, instead they become dragged immediately. I can get around this by setting the "pressDelay" but then you have to wait for the delay before it's draggable which I noticed that people tend not to do.
I'd like a way to not start the sorting unless you have actually dragged the cursor for say 5px.

**Comment by NeXTs** [comment]
Yes, I guess it will be much more evident to users than "pressDelay" option
Really looking forward to this feature too

**Comment by bvaughn** [comment]
I encountered a similar issue with sortable `FlexTable` rows. My table contained `<input>` tags which stopped working when I made the whole row draggable. (Clicks on the `<input>` would just start a drag.) I ended up using the drag-handle approach, which works pretty well. But if there was some sort of threshold it might be nicer still.

This might still lead to edge-cases when it comes to things like text-selection so maybe some way to cancel/block a drag (eg #36) might also be nice.

**Comment by clauderic** [comment]
Just published `0.0.8` with this feature. Just pass in a `distance` prop to your `SortableContainer`.

Alternatively, you may also use `shouldCancelStart`, which was just released today as well. This function gets invoked before sorting begins and can be used to programatically cancel sorting before it begins.

Here's the default implementation:
```js
function shouldCancelStart(e) {
    // Cancel sorting if the event target is an `input`, `textarea`, `select` or `option`
    if (['input', 'textarea', 'select', 'option'].indexOf(e.target.tagName.toLowerCase()) !== -1) {
        return true; // Return true to cancel sorting
    }
}
```

**Comment by NeXTs** [comment]
aww yeah!

**Comment by tornstrom** [comment]
Sweet, thanks @clauderic!
