### ISSUE TITLE
Publish the react 16 compatible version to NPM

### ISSUE THREAD

**Issue by sedge** [clauderic/react-sortable-hoc#351]
Hi @clauderic! 

I see you've [updated this library's](https://github.com/clauderic/react-sortable-hoc/commit/719778dd766674bede3bf53b2592f28c728ceda5) `peerDeps` to be compatible with react 16. Can you publish a version containing that change to NPM?

**Comment by bigSiebs** [comment]
+1

**Comment by sedge** [comment]
For those interested, I've published it myself as the package `amo-react-sortable`.

**Comment by cyrus-za** [comment]
@sedge  I just installed your package but it has a peer dependency of react 0.14

**Comment by sedge** [comment]
@cyrus-za You're mistaken. Perhaps you installed the wrong version? A fresh install of `npm install amo-react-sortable` has this in the `package.json`:

```js
  "peerDependencies": {
    "react": "^0.14.0 || ^15.0.0 || ^16.0.0",
    "react-dom": "^0.14.0 || ^15.0.0 || ^16.0.0"
  },
```

Let me know if I've overlooked something.

**Comment by cyrus-za** [comment]
It was due to not uninstalling react-sortable-hoc yet. All good here
