### ISSUE TITLE
Pass oldIndex and newIndex in onSortMove, just like for onSortEnd

### ISSUE THREAD

**Issue by meglio** [clauderic/react-sortable-hoc#354]
When drag&dropping, it might be useful to know both `oldIndex` and `newIndex`. For example, when working with trees represented as lists with indented items, one will want to automatically change the indent in the item being dragged depending on where in the list it currently shown (i.e. at which position, or what is the current `newIndex` value). May you please pass on these values to the {{onSortMove}} handler.

**Comment by clauderic** [comment]
Fixed in #278
