### ISSUE TITLE
pressDelay setting seems to affects buttons placed inside the sortable item

### ISSUE THREAD

**Issue by reichertm** [clauderic/react-sortable-hoc#368]
Each of my sortable items have a 'delete' button shown in a corner of each. So the user can drag to reorder but also click on the button to delete particular item. The `pressDelay` set to `100` works nicely to avoid unintentional reordering when scrolling on a touch device. 

However, when using the 'delete' button you have to click it very quickly for it to work. When you press the mouse button and hold for just a moment, the click event is not getting triggered. This is to the point where some users (those with a 'long click' pattern;) think the button is not working.

**Comment by aradnom** [comment]
Ran into this as well.  For the moment I've just set pressDelay to something fairly high (500) so rows can reliably be deleted with a typical tap/click.

**Comment by clauderic** [comment]
The best user experience on desktop in my opinion is to use the `distance` prop and set it to a fairly low value (for instance, `distance={1}` would prevent sorting from being triggered unless the item is moved at least 1 px.

Doing so avoids any kind of issues with clickable elements such as buttons or anchor tags. If you insist on using `pressDelay`, then make sure you set it to a higher value, I would recommend `250` ms as a safe value
