### ISSUE TITLE
drag item and let container  scroll automatically？

### ISSUE THREAD

**Issue by zhujunwei** [clauderic/react-sortable-hoc#372]
If the container is scrollable , when I drag to the edge of container, can container scroll up or down automatically?

**Comment by qwlong** [comment]
same question

**Comment by Vishvadeep93** [comment]
facing this issue

**Comment by qwlong** [comment]
I found the method to do it

just like this
<SortableList
getContainer={() => document.getElementById('setting-right-panel')}
/>
