### ISSUE TITLE
Request: drag item out of container to remove item

### ISSUE THREAD

**Issue by kayazinc** [clauderic/react-sortable-hoc#38]
hi, nice library, is it possible to detect the item is drag out of container and remove the item from container when mouse is released?

Thanks man!

**Comment by clauderic** [comment]
Not currently, no. This library is not intended to be a Drag & Drop library, it's meant to be a simple, drop-in sortable solution. There are already a number of great libraries out there that solve these kinds of concerns, such as `react-dnd`, so this isn't something that's currently planned.
