### ISSUE TITLE
SortableContainer parent to render the SortableElements

### ISSUE THREAD

**Issue by nuthinking** [clauderic/react-sortable-hoc#381]
Hopefully not a silly question. I've a pretty long component which is  managing grand grand children. Is it possible some-how to use this library in a declarative way so that a SortableContainer is not encapsulated but its parent can, for instance, render directly the SortableElements? I'm finding myself passing too many things to the list which then passes it to the items. Thanks!

**Comment by clauderic** [comment]
Can you share a snippet of code to illustrate? Your question is a bit unclear

**Comment by nuthinking** [comment]
Ops, sorry I missed this. I think it was a silly question. Sortable containers are too dynamic for allowing the grand parents of sortable elements to declare them.
