### ISSUE TITLE
Safari: Can't find variable: TouchEvent

### ISSUE THREAD

**Issue by gpoitch** [clauderic/react-sortable-hoc#382]
This recent commit broke usage in Safari (11.1):
https://github.com/clauderic/react-sortable-hoc/commit/106727d79b558df4f21e5d42212b0663f3440d83

https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent

**Comment by clauderic** [comment]
Fixed in `0.8.2`, thanks for the report 👍

**Comment by qwerwsad** [comment]
Hello, has the issue of "touchenvent" been resolved? I have encountered the same problem now, and I would like to ask you how to solve it!
