### ISSUE TITLE
Bug -  Drag functionality doesn't work in Firefox and Safari

### ISSUE THREAD

**Issue by AlekzandrG** [clauderic/react-sortable-hoc#383]
In Chrome the basic example is working well, but in other browsers when I try to drag the SortableElement the console shows the following messages:

- Firefox: TypeError: invalid 'instanceof' operand window.TouchEvent[Learn More] ...
- Safari: TypeError Right hand side of instanceof is not an object...

Previously the console used to show the message: TouchEvent is undefinded

You can check this behavior in this codesandbox https://codesandbox.io/s/lp80jz8887

**Comment by clauderic** [comment]
Fixed in `0.8.3`
