### ISSUE TITLE
react-virtualized example

### ISSUE THREAD

**Issue by hyperknot** [clauderic/react-sortable-hoc#385]
I started out from the official example of this repo, but as soon as I tried to modify it I run into different errors with missing keys, index and styles.

I've also looked at the presentation by @bvaughn on https://bvaughn.github.io/forward-js-2017/#/27/5 and try to mix the two. The one I created works well and is using AutoSizer. 

Does this look reasonable to you? Is there anything you'd recommend changing?

// it's using mobx instead of setState but it shouldn't make a difference

```
import { observer } from 'mobx-react'
import React, { Component } from 'react'
import { SortableContainer, SortableElement } from 'react-sortable-hoc'
import { AutoSizer, List } from 'react-virtualized'

@observer
export class ItemTree extends React.Component {
  render() {
    return (
      <div id="panel-items-list">
        <AutoSizer>
          {({ height, width }) => (
            <SortableList
              ref={instance => {
                this.SortableList = instance
              }}
              width={width}
              height={height}
              // onSortEnd=...
            />
          )}
        </AutoSizer>
      </div>
    )
  }
}

@observer
class VirtualList extends Component {
  rowRenderer = function({ index, key, style }) {
    const feature = featureStore.featureArray[index]
    return <SortableItem key={key} index={index} style={style} feature={feature} />
  }

  render() {
    const { width, height } = this.props

    return (
      <List
        ref={instance => {
          this.List = instance
        }}
        rowHeight={31}
        rowRenderer={this.rowRenderer}
        rowCount={featureStore.count}
        width={width}
        height={height}
        scrollToIndex={mapUIStore.scrollToIndex}
      />
    )
  }
}

const SortableItem = SortableElement(({ feature, style }) => (
  <ItemTreeRow style={style} feature={feature} />
))

const SortableList = SortableContainer(VirtualList, { withRef: true })

class ItemTreeRow extends Component {
  render() {
    const { feature, style } = this.props
    return <div style={style}>{feature.title}</div>
  }
}
```

**Comment by hyperknot** [comment]
What confuses me is this part in react-virtualized's readme:
https://github.com/bvaughn/react-virtualized/blob/master/README.md#pure-components

It says if possible I should use passThrough props. I've done like that, using a large random integer to trigger updates after reordering.

This means, that non of `withRef`, `this.List`, `this.SortableList`, `forceUpdate`, `forceUpdateGrid`, `recomputeHeights` is needed, just a simple random integer as a dummy prop.

Why are none of the examples using just a dummy prop? It seems way more reliable then trying to force an update. https://github.com/bvaughn/react-virtualized/blob/master/README.md#pure-components

**Comment by SkunSHD** [comment]
> Why are none of the examples using just a dummy prop?
Just like that?

```
    <AutoSizer 
      renderTrigger={list.length}
    >
      {({ height, width }) => (
        <List
          width={width}
          height={height}
          rowRenderer={rowRenderer}
        />
      )}
    </AutoSizer>

```
https://codesandbox.io/s/1qrj104914
