### ISSUE TITLE
Issue: Sorting items with different parent (same collection)

### ISSUE THREAD

**Issue by robvree** [clauderic/react-sortable-hoc#387]
In our app we use a custom virtualized list that pages items. Often times, items from the same collection end up with different parent containers and it seems like react-sortable-hoc won't allow us to sort items between parents. Can anyone suggest something that might get us past this issue?

Our layout is something like this.

```
<SortableContainer>
     <VirtualPage>
          <SortableItem collection="A" />
          <SortableItem collection="A" />
          <SortableItem collection="A" />          
     </VirtualPage>
     <VirtualPage>
          <SortableItem collection="A" />
          <SortableItem collection="B" />
          <SortableItem collection="B" />          
     </VirtualPage>
</SortableContainer>
```

**Comment by iOiurson** [comment]
I have something similar here: my "parents" are dates, that can hold multiple "events", and i want to drag one event from one date to another.
I'm not sure this is possible with this library.

**Comment by YannickAWE** [comment]
Same for me, did you succeed to drag&drop items from different lists ?

**Comment by clauderic** [comment]
No plans on supporting this type of functionality for the moment, sorry.
