### ISSUE TITLE
Adding event listener on <SortableElement />

### ISSUE THREAD

**Issue by therealedsheenan** [clauderic/react-sortable-hoc#394]
Is there any way to add an event listener like `click` or hover on the `<SortableElement />`?

This doesn't seem to work.
```
SortableElement({ value, reOrder }) => (
  <li>
     <div onClick={() => /* event here */}>Click me</div>
  </li>
)
```

It works on buttons only.
```
SortableElement({ value, reOrder }) => (
  <li>
     <button onClick={() => /* event here */}>Click me</button>
  </li>
)
```

**Comment by delgiudices** [comment]
I can't even add an `onClick` handler for buttons

**Comment by therealedsheenan** [comment]
My problem with buttons earlier was just the `z-index`. It might be your problem as wel.. @delgiudices

**Comment by vince1995** [comment]
https://github.com/clauderic/react-sortable-hoc#click-events-being-swallowed

**Comment by edgardleal** [comment]
@therealedsheenan , this issue could be closed ?

**Comment by AnoushSim** [comment]
Hi. onClick works in my code. But every time when I click on one of the elements of SortableContainer, it calls onClick handler function for all elements. Can someone help?
