### ISSUE TITLE
Multiple lists code example

### ISSUE THREAD

**Issue by huhuhong** [clauderic/react-sortable-hoc#397]
Hi guys,

http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/multiple-lists?_k=15dzja

Can anyone provide sample code of multiple list in codepen or codesandbox link?

Thanks

**Comment by brendandestefano** [comment]
any update here? looking for this exact same thing. thanks

**Comment by smtaydemir** [comment]
+1

**Comment by clauderic** [comment]
https://codesandbox.io/s/81v9lxk392

**Comment by ashwinnaidu** [comment]
Example for moving items from one list to another ?

**Comment by rashmimh** [comment]
I am also looking for moving items from one list to another.
following: https://github.com/clauderic/react-sortable-hoc/pull/138

**Comment by Shen120** [comment]
https://github.com/clauderic/react-sortable-hoc/blob/master/examples/collections.js

This is the example

**Comment by wilckerson** [comment]
I know this is an old thread, but I got into the same problem. So, I have created this implementation based on other solutions I have seen around. I hope this is helpful: https://codesandbox.io/p/sandbox/react-sortable-hoc-2-lists-forked-7qfkfv
