### ISSUE TITLE
when i select slide element after scrolling ,the scroll is coming to top when i use these sortable -hoc in my application

### ISSUE THREAD

**Issue by narevit** [clauderic/react-sortable-hoc#399]
May i know why these issue is coming?

**Comment by averyga** [comment]
I have the same issue, is there any solution? I've found out it is because on every action sortable -hoc rerenders.

**Comment by dungcodelynx** [comment]
The problem is that the cloned node does not contain the information of scrolling position. I wonder there is a js function to do this.

**Comment by clauderic** [comment]
Would you mind providing a CodeSandbox example reproducing the issue? Not sure I understand. Closing the issue until a repro case is submitted

**Comment by akashxyz** [comment]
Facing the same issue.

**Comment by akashxyz** [comment]
Check if you're giving the element some id/for attribute combination which is repeating, maybe via some loop or other render process and remove it completely. It worked for me.
