### ISSUE TITLE
Layout changes upon drag

### ISSUE THREAD

**Issue by AdamBCo** [clauderic/react-sortable-hoc#40]
At the moment I have a SortableElement that contains an input textfield and a textarea. When I click to drag the component to a desired location the layout of the SortableElement changes. What extra steps do I need to do to address this issue? Thanks for the help.

<img width="841" alt="before" src="https://cloud.githubusercontent.com/assets/4572275/17738634/f5dddc08-6446-11e6-925d-ca28bc551615.png">
<img width="746" alt="after" src="https://cloud.githubusercontent.com/assets/4572275/17738633/f5db6e5a-6446-11e6-9440-c216c311da1c.png">

**Comment by clauderic** [comment]
You most likely have some over-qualified css selectors targeting your elements. 

Upon sorting, `react-sortable-hoc` appends your element to the body (for a number of reasons that have been discussed in https://github.com/clauderic/react-sortable-hoc/issues/20), so you'll either need to update the css of your SortableHelper to re-apply those styles or just make sure your css selectors for your SortableElements are not dependent on parent>children relationship.

**Comment by AdamBCo** [comment]
@clauderic Thanks for the response. Would you mind posting an example?

**Comment by clauderic** [comment]
Actually if you don't mind, it would be a lot easier for me to help if instead if you could share your code in some way or another (either git repo, or forking this [jsfiddle](https://jsfiddle.net/clauderic/6r7r2cva/))
