### ISSUE TITLE
Updating state in "item"

### ISSUE THREAD

**Issue by oznekenzo** [clauderic/react-sortable-hoc#400]
Super awesome package!

My "item" has grown in complexity to the point of integrating state/props.
Is there any way an "item" in react-sortable-hoc can receive props/state?

Thank you!

**Comment by nickvruiz** [comment]
@oznekenzo, if I understand your question correctly then you need to pass the props down from the container. The same way you pass a value to the Sortable Item:

`
// Sortable item, notice 'someProp' in the arguments
const SortableItem = SortableElement(({ someProp }) => <div>{ someProp }</div>);

// SortableContainer, notice 'someProp' in the arguments
const SortableList = SortableContainer(({ items, someProp }) => (
    { items.map(item, index) =>
        {*/ Pass the prop to the item */}
        <SortableItem
            key={index}
            index={index}
            someProp={someProp}
        />
    }
);

<SortableList
    items={this.state.items}
    someProp={this.state.someValue}
/>
`
