### ISSUE TITLE
Add link for examples code

### ISSUE THREAD

**Issue by O4epegb** [clauderic/react-sortable-hoc#402]
Right now I can't find code for examples from repo description (http://clauderic.github.io/react-sortable-hoc)
Examples folder in this repo has fewer and different examples compared to website.
Does anybody know where code for website examples is located? Maybe we should add link to it in readme.

**Comment by krvajal** [comment]
I think this is what you are looking for
https://github.com/clauderic/react-sortable-hoc/blob/master/src/.stories/index.js
