### ISSUE TITLE
collapsed list items when dragging

### ISSUE THREAD

**Issue by elirangold** [clauderic/react-sortable-hoc#405]
Hello there,
so I have been working with the react-sortable-hoc in my project for a while but I've encountered a major difficulty. 
I'm trying to make all of the items collapse (mainly to change their height) when dragging starts with no success. It seems that the height calculations are happening before the "onSortStart" event is called and that there is no way of doing it. 
Does anyone have an idea?

**Comment by clauderic** [comment]
This is possible using the `updateBeforeSortStart` prop

**Comment by rashmimh** [comment]
@elirangold Can you please share a piece of code. I am also stuck with issue dragging vertical list of collapses using ANT Design.
