### ISSUE TITLE
Custom events inside sortables

### ISSUE THREAD

**Issue by brusherru** [clauderic/react-sortable-hoc#41]
Hi there!
I need to use custom events on elements inside SelectableElement. But Selectable blocks onClick events (I just can bind onMouseDown / onMouseMove and etc, but not onMouseUp or onClick).
Is there any easy way to solve it?

Thanks!

**Comment by clauderic** [comment]
Hey @brusherru, `SortableElement` doesn't block onClick events *per se*, it simply responds before your onClick events get a chance to fire since it listens to `onMouseDown / onTouchDown`. 

You can either set a `pressDelay` or use a `SortableHandle` to work around this.

**Comment by brusherru** [comment]
@clauderic,
It's a dirty and unhandy hack.
Take a look at your chrome tabs: you can drag it even you move a mouse over it (without any stop) and you can switch it by clicking (mouse up). I need to do the same thing.

**Comment by clauderic** [comment]
> It's a dirty and unhandy hack.
I'm happy to review any alternative solutions you can come up with but I can't think of any.

**Comment by clauderic** [comment]
FYI, just published `0.0.8` to npm with support for `distance` and `shouldCancelStart`. I believe both of these should help in solving the use case you had in mind. You can either pass in a minimum drag distance of `1` or selectively prevent dragging with `shouldCancelStart` if the `event.target` matches an element you want to prevent from being sorted.

**Comment by jimenmar** [comment]
Hello I have been looking for a solution to fire an onChange event for a checkBox that is inside SortableElement.
I tried using pressDelay and shouldCancelStart but none of help me to trigger my event.
Does anyone has experienced same issue?
Any help will be appreciate it
