### ISSUE TITLE
Cannot read property 'left' of undefined with react-virtualized Grid

### ISSUE THREAD

**Issue by superandrew213** [clauderic/react-sortable-hoc#412]
Integration with `react-virtualized` Grid seems to work pretty smooth for me.

However an error occurs when you drag and scroll an item. The nodes are being unmounted and there is no `prevNode` when scrolling down.

Changing this:
```js
translate.x = prevNode.edgeOffset.left - edgeOffset.left;
translate.y = prevNode.edgeOffset.top - edgeOffset.top;
```
https://github.com/clauderic/react-sortable-hoc/blob/master/src/SortableContainer/index.js#L637-L638

to this:
```js
if (prevNode) {
  translate.x = prevNode.edgeOffset.left - edgeOffset.left;
  translate.y = prevNode.edgeOffset.top - edgeOffset.top;
}
```

and for scrolling up look for `nextNode` and change it to this:
```js
if (nextNode) {
  translate.x = nextNode.edgeOffset.left - edgeOffset.left;
  translate.y = nextNode.edgeOffset.top - edgeOffset.top;
}
```

fixes the issue. Animation doesn't seem to be affected.

Maybe there is a better fix but at least `react-sortable-hoc` is working with `react-virtualized` Grid and +1000 items ✌️

I will dig further into this to figure out why the Grid is causing this issue and the List doesn't.

@clauderic if you have any ideas or can point me in the right direction that would be great.

Seems to be the same as this https://github.com/clauderic/react-sortable-hoc/pull/326.

If anyone wants to test it, use my fork:
https://github.com/superandrew213/react-sortable-hoc/tree/fix-react-virtualized-grid-with-dist

**Comment by hubdrpl** [comment]
Hey @clauderic could you take a look at this issue again? I think it does solve the problem.

**Comment by chaomao** [comment]
@superandrew213 
Hi, I try to integrate `react-sortable-hoc` with `react-virtualized  Grid` but I failed, do you mind if you can share basic code of the integration of `react-sortable-hoc` and `react-virtualized Grid`
Many Many Thanks :)
