### ISSUE TITLE
Properly positioning element on previous row in xy axis

### ISSUE THREAD

**Issue by Tauka** [clauderic/react-sortable-hoc#413]
Hi, thank you for your great library!

However, I found an issue when dragging various width elements into the next row in both axis mode, they can improperly position themselves into the previous row, and the space for dragged element is also calculated inaccurately. You can see it below

![react-sortable-enhancement](https://user-images.githubusercontent.com/15087247/44002993-6acbaf60-9e6d-11e8-8a4f-61c8a2da6b34.gif)

I've been digging into the codebase to solve this issue, and would appreciate any guidance on where to start and how to approach this problem. Thanks!

**Comment by clauderic** [comment]
As mentioned in the docs, grid sorting is currently limited to items of equal widths and heights (see https://github.com/clauderic/react-sortable-hoc#grid-support)

PRs are welcome if you want to improve this
