### ISSUE TITLE
Having to drag too far 

### ISSUE THREAD

**Issue by conradkay** [clauderic/react-sortable-hoc#419]
I have a component and trying to drag it requires me to drag too far, video: https://vimeo.com/285899639
source code: https://github.com/conradkay/todo-app-jest-flow-router-react-redux

**Comment by ohtanya** [comment]
Were you able to solve this? I'm having the same problem.

**Comment by conradkay** [comment]
I have since stopped using react-sortable-hoc, so no :(

**Comment by adamryvola** [comment]
Same problem, do you have solution?

**Comment by adamryvola** [comment]
@naamagr YEAAAH! It works, you saved me a lot of time, thanks!

**Comment by mistadikay** [comment]
> I had the same issue. It was caused by wrong calculation of the edgeOffset, when the SortableElement is nested inside another wrapper element, and so `offsetTop` is multiplied (see here: https://github.com/clauderic/react-sortable-hoc/blob/master/src/utils.js#L121)
> to fix it, I've set `position: relative` to the wrapper element, so that the `offsetTop` of the SortableElement will be zero.

In my case I just got rid of a wrapper element which helped. Thanks a lot for the tip!
