### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'array.length')

### ISSUE THREAD

**Issue by AdamBCo** [clauderic/react-sortable-hoc#42]
Unfortunately, I keep getting the following error when trying to sort an array of custom objects:

    TypeError: undefined is not an object (evaluating 'array.length')

This error happens after successfully dragging and dropping 1 time. After that, the error appears and I am unable to move any of the sortableItems.

I know the problem lies in the chunk of code:

<img width="488" alt="screenshot 2016-08-25 06 10 11" src="https://cloud.githubusercontent.com/assets/4572275/17970255/af70e0e0-6a8a-11e6-8ede-c2921ceb1aaf.png">

I have also included the code for my sortable component:

<img width="1054" alt="screenshot 2016-08-25 06 10 23" src="https://cloud.githubusercontent.com/assets/4572275/17970282/c99018e2-6a8a-11e6-82ec-4f254d456bcb.png">

**Comment by clauderic** [comment]
Judging by the error you're getting, this means that your `terms` prop is undefined. Would you mind sharing the entire code? This excerpt is incomplete so it's difficult for me to help out

**Comment by clauderic** [comment]
Going to assume you've solved this since I haven't heard back. Feel free to re-open if not, ideally with a jsfiddle or a gist somewhere so that I'm better equipped to help you out.
