### ISSUE TITLE
Where is the source code for the grid?

### ISSUE THREAD

**Issue by hayk94** [clauderic/react-sortable-hoc#420]
http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=t5xcdq

Where can I find the source code of this?

**Comment by stevenanthonyrevo** [comment]
@hayk94 
I was looking for the same thing, best I could find was.
https://codesandbox.io/s/vm917ww2z3

It doesn't allow for multiple props on the gridItem, anyone know how to add more additional props to this example? The documentation does have much on grids...

**Comment by hayk94** [comment]
@stevenanthonyrevo maybe you can pass the `value` as component and pass props to it?

**Comment by stevenanthonyrevo** [comment]
@hayk94  Thanks for the help! 

I also noticed the documentation doesn't have anything relating to persistent ordering of the grid. 

For example, the user can drag the boxes around however the boxes are based on the mapped array order not persistent to db or localstorage. These draggable items don't stay around when user refreshes page. Any thoughts or references for dealing with this?

**Comment by hayk94** [comment]
You can call your function which saves the state in `onSortEnd` method

**Comment by edorivai** [comment]
@hayk94 To answer your original question: https://github.com/clauderic/react-sortable-hoc/blob/master/src/.stories/index.js#L393-L406

**Comment by ralexrdz** [comment]
I wish everybody answered my issue questions like this one... I guess he got the #420 wish... lucky bstrd
Thanks everybody

**Comment by lacymorrow** [comment]
https://codesandbox.io/embed/0nnq0kv2l  I also found this...

**Comment by li305263** [comment]
> @ hayk94
> 我一直在寻找相同的东西，最好的发现是。
> https://codesandbox.io/s/vm917ww2z3
> 
> 它不允许在gridItem上使用多个道具，有人知道如何在此示例中添加更多其他道具吗？该文档确实在网格上有很多...

thanks,
