### ISSUE TITLE
Is it possible to use "Sortable Table Columns" with a MultiGrid?

### ISSUE THREAD

**Issue by Shaked** [clauderic/react-sortable-hoc#426]
Is it possible to use "Sortable Table Columns" with a MultiGrid?

I hope it's ok to ask these type of questions in here. If not, please accept my apologies.
Thank you
Shaked

**Comment by rajjejosefsson** [comment]
Hey @Shaked I started working on the same idea and here is what I currently have https://codesandbox.io/s/llw45l9m6m

**Comment by Shaked** [comment]
@rajjejosefsson thank you. Looking good, I will try it. Any known issues that you have encountered so far?

**Comment by clauderic** [comment]
Thanks for sharing @rajjejosefsson
