### ISSUE TITLE
 I want to manage the component via shouldComponentUpdate ().

### ISSUE THREAD

**Issue by biosina1** [clauderic/react-sortable-hoc#427]
I want to manage the SortableItem and SortableList components using shouldComponentUpdate (). This is because as the number of components increases, the speed decreases significantly. Is there any way?

Is it possible to replace a functional component with a class-based component? I wonder how it is possible if possible.

```
const SortableItem = SortableElement(({ value, onRemove, onStateChange, onIsCheckToggle }) => {
    return (
        <div className='SortableElement'>
                items..........
        </div>
    );
});

const SortableList = SortableContainer(({ items, onRemove, onStateChange, onIsCheckToggle }) => {
    return (
        <div className='SortableContainer'>
            {items.map((value, index) => (
                <SortableIte />
            ))}
        </div>
    );
});
```

**Comment by rohanrana** [comment]
you have closed the issue did you  found the solution for that if yes then i want to know that
