### ISSUE TITLE
Can't find code example for Horizontal sort 

### ISSUE THREAD

**Issue by nchorniiNetls** [clauderic/react-sortable-hoc#429]
Hi, Cannot find source code for [this](http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/horizontal?_k=3i1u1a) example. Can somebody help?

**Comment by nchorniiNetls** [comment]
I figure this out. Sorry

**Comment by cstroked** [comment]
haven't been able to get anywhere with this - is there example code? setting `axis="x"` doesn't seem to do the trick. thank you

**Comment by qpixHassaballah** [comment]
Can some one please re open this issue ?

**Comment by qpixHassaballah** [comment]
The X-Axis props works all you have to do is follow the same styling rules in the example you can take a look at the css file and mimic the class names that are responsible for your list
