### ISSUE TITLE
Which types to use?

### ISSUE THREAD

**Issue by DylanSp** [clauderic/react-sortable-hoc#433]
It looks like this library [bundles Typescript types](https://github.com/clauderic/react-sortable-hoc/blob/master/types/index.d.ts) with it, but there are also types [on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-sortable-hoc). Which type definitions are more up-to-date?

**Comment by clauderic** [comment]
The ones bundled with this library are the most up to date, I manually maintain them. Eventually, this library will be migrated to TypeScript, and they will be auto-generated from the library.
