### ISSUE TITLE
How to disable drag drog when click on element in SortableElement?

### ISSUE THREAD

**Issue by pvtran1995** [clauderic/react-sortable-hoc#437]
I render select tag in SortableElement, I can not catch on change event of select tag.
Can I disable drag drop event only on child element in SortableElement?

Thank you for your help!

![image](https://user-images.githubusercontent.com/43138633/47695825-79867600-dc36-11e8-8e80-7ca6474b808a.png)

**Comment by zfeed** [comment]
Have you tried using **shouldCancelStart** property?

**Comment by clauderic** [comment]
As mentioned by @zfeed, try using `shouldCancelStart`

**Comment by burnEAx** [comment]
Same issue. Please show how use `shouldCancelStart` prop.

**Comment by burnEAx** [comment]
@pvtran1995 please update, had your problem been solved?

**Comment by asmakhalfallah2018** [comment]
how to use it please ? no documentation found
