### ISSUE TITLE
Adding and Removing items

### ISSUE THREAD

**Issue by PaulDevI** [clauderic/react-sortable-hoc#44]
I'm trying to add and remove items from the lists, using onClick on buttons. Doing Add was easy using the SortableComponent, but I don't know how to use  remove because SortableList and SortableItem are functions not classes to add a method(code below and attached file).  I'm just starting working, with React ES6, maybe is something that I don't understand.

Thanks. 

```
const SortableList = SortableContainer(({items}) => {
    return (
        <table>
            {items.map((value, index) =>
            <tr>
                <td>
                <SortableItem key={`item-${index}`} index={index} value={value} />
                    </td>
                    <td>
                    <button>Remove{index}</button>
                </td>
             </tr>
            )}
        </table>
    );
});

class SortableComponent extends React.Component{
     constructor(props) {
         super(props);
         this.state = {items: [1, 2, 3, 4]};
         this.onSortEnd = this.onSortEnd.bind(this);
         this.add = this.add.bind(this);
     }


    onSortEnd({oldIndex, newIndex}) {
        this.setState({items: arrayMove(this.state.items, oldIndex, newIndex)});
    }


    add() {
        const items = this.state.items;
        let new_item = this.state.items.length+1;
        items.push(new_item);
        this.setState({items : items})
        console.log(new_item);
    }

    render() {
        return (
            <div>
                <SortableList items={this.state.items} onSortEnd={this.onSortEnd} />
                <button onClick={this.add}>Add Document</button>
            </div>
        );
    }
}
```
![example](https://cloud.githubusercontent.com/assets/20904337/18200014/851da3dc-710b-11e6-99dd-bacb2cb17b4d.PNG)

**Comment by clauderic** [comment]
Hey @PaulDevI, I'm not sure I follow what you're trying to achieve, but from what I understand, here's how I would implement it:

```js
import {SortableContainer, SortableElement, arrayMove} from 'react-sortable-hoc';

const SortableItem = SortableElement(({index, onRemove, value}) => {
    return (
        <tr>
            <td>
                <File onDrop={/* Not sure how you have this implemented */} />
            </td>
            <td>
                <button onClick={() => onRemove(index)}>Remove{index}</button>
            </td>
         </tr>
    )
})
const SortableList = SortableContainer(({items, onRemove}) => {
    return (
        <table>
            {items.map((value, index) =>
                <SortableItem key={`item-${index}`} index={index} value={value} onRemove={onRemove} />
            )}
        </table>
    );
});

class SortableComponent extends React.Component{
    constructor(props) {
        super(props);
        this.state = {items: [1, 2, 3, 4]};
        this.onSortEnd = this.onSortEnd.bind(this);
        this.add = this.add.bind(this);
    }
    onSortEnd({oldIndex, newIndex}) {
        this.setState({items: arrayMove(this.state.items, oldIndex, newIndex)});
    }
    add() {
        const items = this.state.items;
        let new_item = this.state.items.length+1;
        items.push(new_item);
        this.setState({items : items})
        console.log(new_item);
    }
    remove(index) {
        const items = this.state.items;
        items.splice(index, 1);
        
        this.setState({items : items})
    }
    render() {
        return (
            <div>
                <SortableList items={this.state.items} onSortEnd={this.onSortEnd} onRemove={onRemove} />
                <button onClick={this.add}>Add Document</button>
            </div>
        );
    }
}
```

**Comment by PaulDevI** [comment]
Thanks, sorry for so late reply. I tried your code and is not working, removing the input element.

What I'm trying to achieve, is to add/remove documents and sort them thru drag and drop.  

1) At the beginning the user has only one file input available(browser) to add a document.
2) If the user wants to add another document click the Add document button, and a new input file element appears, to add anew document.
3) If the user change his mind, and don't want to upload one of the documents, click the Remove button near/corresponding to the file input.
4) If a user doesn't like the order of documents(they will appear on the front end) he change thru sort able drag and drop.

I know how to do it without the sorting part, but I can't figure out how to use it with your plugin, because in my implementation of components was different. Please help.

**Comment by clauderic** [comment]
Hey @PaulDevI, the code I submitted should work, you just needed to implement the file input yourself. Here's a [jsfiddle](https://jsfiddle.net/czr9ma1u/1/) with it working

**Comment by PaulDevI** [comment]
Hi, sorry from adding again to the closed issue, I used for continuity.

I uploaded 3 files(see initial-state):

![initial-state](https://cloud.githubusercontent.com/assets/20904337/18754673/2cc5dfa0-80f2-11e6-823d-74dad5b739fb.PNG)

If I remove the first one , Desert.jpeg, it is actually removed the last one Hyadrangeas.jpg. 

![remove-hydrageneas](https://cloud.githubusercontent.com/assets/20904337/18754771/848fda10-80f2-11e6-9555-3b5bf9c4c7f4.PNG)

When I'm drag and drop, and try to replace the first desert.jpeg with Jellyfish.jpg, it is trying,but after drop desert.jpg remains first.

At this moment I don't know, if just the file names (visually) needs to be update or ia problem with the real files also. As back-end I use python, but it seems, that the files are not sent correctly to it.

Can you please give me some ideas/code ?
Thanks.

**Comment by clauderic** [comment]
Hey @PaulDevI, it has to do with the react `key` property of your SortableItems. You need to pass in a predictable `key` to uniquely identify each child (see https://facebook.github.io/react/docs/multiple-components.html#dynamic-children) 

Check out this excerpt from the [jsfiddle](https://jsfiddle.net/czr9ma1u/3/) I sent you:

```jsx
const SortableList = SortableContainer(({items, onDrop, onRemove}) => {
    return (
        <ul className="SortableList">
            {items.map((value, index) =>
                <SortableItem 
                	key={`item-${value}`} // This part is where you would pass in a predictable, consistent key for each child
                        {...}
                />
            )}
        </ul>
    );
}
```

**Comment by badaljain** [comment]
HI @clauderic , the `index` in my onRemove function is always undefined
`<button onClick={() => onRemove(index)}>Remove{index}</button>`

could you please help?
```import React, { Component } from 'react'
import {SortableContainer, SortableElement, arrayMove} from 'react-sortable-hoc'
import { Panel, Glyphicon, Well, Button } from 'react-bootstrap'
import styles from './style.css'

const SortableItem = SortableElement(({index, value, onRemove}) =>
    <li className={styles.SortableItem}>
        {value}
        <button key={`input-${value}`} onClick={() => onRemove(index)}> Remove </button>
    </li>
)

const SortableList = SortableContainer(({items, onRemove}) => {
    return (
        <ul className={styles.SortableList}>
            {items.map((value, index) => 
                <SortableItem 
                    key={`item-${index}`} 
                    index={index} 
                    value={value} 
                    onRemove={onRemove} 
                />
            )}
        </ul>
    )
})

class SortableTileContainer extends Component {
    constructor (props) {
        super(props)
        this.shouldCancelStart = this.shouldCancelStart.bind(this)
    }
    
    onSortEnd = ({oldIndex, newIndex}) => {
        const updatedList = arrayMove(this.props.selectedTiles, oldIndex, newIndex)
        this.props.updateSelectedSort(updatedList)
    }

    shouldCancelStart(e) {
        // Prevent sorting from being triggered if target is input or button
		if (['input', 'button'].indexOf(e.target.tagName.toLowerCase()) !== -1) {
			return true; // Return true to cancel sorting
        }
    }
    
    remove (index) {
        console.log(index)
    }

    render () {
        return (
            <div className={styles.container}>
                <SortableList 
                    items={this.props.selectedTiles} 
                    onSortEnd={this.onSortEnd} 
                    axis='x' 
                    helperClass={styles.SortableHelper}
                    onRemove={(index) => this.remove(index)}
                    shouldCancelStart={this.shouldCancelStart} />
            </div>
        )
    }
}
export default SortableTileContainer```

**Comment by deesx** [comment]
@badaljain encountered the very same problem, solved it by specifying another 'index' prop :

```
const SortableItem = SortableElement(({idx, node, onRemove}) =>
  <li onClick={() => onRemove(idx)}>
    <DragHandle />
    {node.title}{idx}
  </li>
);
const SortableList = SortableContainer(({items, onRemove}) => {
  return (
    <ul>
      {items.map( function(node, index){
        console.log(index)
        return(<SortableItem key={`item-${index}`} index={index} idx={index} node={node} onRemove={onRemove} />)
      })}
    </ul>
  );
});
```

**Comment by ljcl** [comment]
FWIW looks like [the omit function is removing it](https://github.com/clauderic/react-sortable-hoc/blob/84bfae8595f7be49357cc464b51954c92f4bd549/src/SortableElement/index.js#L89).

**Comment by Rachomir** [comment]
Hey guys I have got similar problem, what I am trying to achieve is to remove the LI item but from clicking the "delete button" from inside the component and pass this information via props. Is it possible to do? 

`export class BroadcastForm extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      items: [],
      sex: 'both',
      sexMale: true,
      sexFemale: true,
      language: 'all',
      timezone: 'all',
      startDate: moment()
    }
    this.onSortEnd = this.onSortEnd.bind(this)
    this.mountComponent = this.mountComponent.bind(this)
    this.sexFemale = this.sexFemale.bind(this)
    this.sexMale = this.sexMale.bind(this)
    this.saveBroadcast = this.saveBroadcast.bind(this)
    this.chooseLanguage = this.chooseLanguage.bind(this)
    this.chooseTimezone = this.chooseTimezone.bind(this)
    this.setDate = this.setDate.bind(this)
  }

  onSortEnd ({oldIndex, newIndex}) {
    this.setState({
      items: arrayMove(this.state.items, oldIndex, newIndex)
    })
  }

  mountComponent () {
    const items = this.state.items
    let newItem = this.state.items.length + 1
    items.push(newItem)
    this.setState({items: items})
  }

  unmountComponent (index) {
    const items = this.state.items
    items.splice(index, 1)
    this.setState({items: items})
  }

  sexFemale () {
    this.setState({sexFemale: !this.state.sexFemale})
  }

  sexMale () {
    this.setState({sexMale: !this.state.sexMale})
  }

  chooseLanguage (language) {
    this.setState({language: language})
  }

  chooseTimezone (timezone) {
    this.setState({language: timezone})
  }

  setDate (startDate) {
    this.setState({startDate})
  }

  saveBroadcast () {
    if (this.state.sexMale && this.state.sexFemale) {
      this.state.sex = 'both'
    } else if (!this.state.sexMale && this.state.sexFemale) {
      this.state.sex = 'female'
    } else {
      this.state.sex = 'male'
    }
    const id = new Date().valueOf()
    const fanpage = this.props.selectedFanpage
    const language = this.state.language
    const timezone = this.state.timezone
    const sex = this.state.sex
    const date = this.state.startDate
    const startDate = date._d
    Meteor.call('saveBroadcast', id, fanpage, language, timezone, sex, startDate, (err) => {
      if (err) {
        console.log(err)
      } else {
        this.props.history.push('/archive')
      }
    })
  }

  render () {
    return (
      <div>
        <BroadcastPreferencesForm selectedFanpage={this.props.selectedFanpage}
          addComponent={this.mountComponent} sexFemale={this.sexFemale} sexMale={this.sexMale}
          saveBroadcast={this.saveBroadcast} language={this.chooseLanguage} timezone={this.chooseTimezone}
          date={this.setDate} />
        <SortableList items={this.state.items} onSortEnd={this.onSortEnd}
          unmountComponent={(index) => this.unmountComponent(index)} />
      </div>
    )
  }
}

export default withRouter(createContainer(props => ({
  ...props
}), BroadcastForm))

const SortableItem = SortableElement((index, unmountComponent) => {
  return <li><BroadcastTextMessageForm dismissComponent={() => this.unmountComponent(index)} /></li>
})

const SortableList = SortableContainer(({items, unmountComponent}) => {
  return (
    <ul>
      {items.map((value, index) => (
        <SortableItem key={`item-${index}`} index={index} value={value}
          dismissComponent={this.unmountComponent}
        />
      ))}
    </ul>
  )
})`

**Comment by Rachomir** [comment]
Hey guys I have got similar problem, what I am trying to achieve is to remove the LI item but from clicking the "delete button" from inside the component and pass this information via props. Is it possible to do?

```export class BroadcastForm extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      items: [],
      sex: 'both',
      sexMale: true,
      sexFemale: true,
      language: 'all',
      timezone: 'all',
      startDate: moment()
    }
    this.onSortEnd = this.onSortEnd.bind(this)
    this.mountComponent = this.mountComponent.bind(this)
    this.sexFemale = this.sexFemale.bind(this)
    this.sexMale = this.sexMale.bind(this)
    this.saveBroadcast = this.saveBroadcast.bind(this)
    this.chooseLanguage = this.chooseLanguage.bind(this)
    this.chooseTimezone = this.chooseTimezone.bind(this)
    this.setDate = this.setDate.bind(this)
  }

  onSortEnd ({oldIndex, newIndex}) {
    this.setState({
      items: arrayMove(this.state.items, oldIndex, newIndex)
    })
  }

  mountComponent () {
    const items = this.state.items
    let newItem = this.state.items.length + 1
    items.push(newItem)
    this.setState({items: items})
  }

  unmountComponent (index) {
    const items = this.state.items
    items.splice(index, 1)
    this.setState({items: items})
  }

  sexFemale () {
    this.setState({sexFemale: !this.state.sexFemale})
  }

  sexMale () {
    this.setState({sexMale: !this.state.sexMale})
  }

  chooseLanguage (language) {
    this.setState({language: language})
  }

  chooseTimezone (timezone) {
    this.setState({language: timezone})
  }

  setDate (startDate) {
    this.setState({startDate})
  }

  saveBroadcast () {
    if (this.state.sexMale && this.state.sexFemale) {
      this.state.sex = 'both'
    } else if (!this.state.sexMale && this.state.sexFemale) {
      this.state.sex = 'female'
    } else {
      this.state.sex = 'male'
    }
    const id = new Date().valueOf()
    const fanpage = this.props.selectedFanpage
    const language = this.state.language
    const timezone = this.state.timezone
    const sex = this.state.sex
    const date = this.state.startDate
    const startDate = date._d
    Meteor.call('saveBroadcast', id, fanpage, language, timezone, sex, startDate, (err) => {
      if (err) {
        console.log(err)
      } else {
        this.props.history.push('/archive')
      }
    })
  }

  render () {
    return (
      <div>
        <BroadcastPreferencesForm selectedFanpage={this.props.selectedFanpage}
          addComponent={this.mountComponent} sexFemale={this.sexFemale} sexMale={this.sexMale}
          saveBroadcast={this.saveBroadcast} language={this.chooseLanguage} timezone={this.chooseTimezone}
          date={this.setDate} />
        <SortableList items={this.state.items} onSortEnd={this.onSortEnd}
          unmountComponent={(index) => this.unmountComponent(index)} />
      </div>
    )
  }
}

export default withRouter(createContainer(props => ({
  ...props
}), BroadcastForm))

const SortableItem = SortableElement((index, unmountComponent) => {
  return <li><BroadcastTextMessageForm dismissComponent={() => this.unmountComponent(index)} /></li>
})

const SortableList = SortableContainer(({items, unmountComponent}) => {
  return (
    <ul>
      {items.map((value, index) => (
        <SortableItem key={`item-${index}`} index={index} value={value}
          dismissComponent={this.unmountComponent}
        />
      ))}
    </ul>
  )
})```
