### ISSUE TITLE
Sort columns with auto height

### ISSUE THREAD

**Issue by OriAmir** [clauderic/react-sortable-hoc#443]
Hi, I use materialize-css grid with Row and Cols to create gallery , I have const width for cols and height auto. so I arrgend it as cols display:
![image](https://user-images.githubusercontent.com/17565646/48757497-9fd38a80-eca5-11e8-952b-dab1f385adb9.png)

My question if I can use this library to sort my gallery ? or all the cols height and width must be equal like in grid ? 

Thanks for great library!

**Comment by clauderic** [comment]
As mentioned in the docs, grid sorting is currently limited to items of equal widths and heights (see https://github.com/clauderic/react-sortable-hoc#grid-support)

PRs are welcome if you want to improve this
