### ISSUE TITLE
Ghost element resizing

### ISSUE THREAD

**Issue by marcselman** [clauderic/react-sortable-hoc#446]
This is probably a very specific use-case issue, but maybe also easily solved.
I've recorded a video to explain it visually: https://www.screencast.com/t/Ui9H6iSNyh3

The short explaination is, I'm resizing the element of which the ghost element gets cloned off so the ghost element records it's size during the resizing animation. The easiest fix would probably be to add a property to set a fixed ghost element size.
Another idea could be to have the ghost element check it's size every couple of milliseconds or to delay the the measuring of the ghost element a couple of milliseconds.

Hope you can help me.
Thank for the awesome library!

Marc

**Comment by clauderic** [comment]
Have you looked at `updateBeforeSortStart` or `getHelperDimensions`? Seems like either or would solve your issue, unless I'm misunderstanding
