### ISSUE TITLE
Wrong translate3d values, when dragging item.

### ISSUE THREAD

**Issue by dimitriskot** [clauderic/react-sortable-hoc#449]
List items begin randomly jumping, when starting drag one of them.
Didn't find similar issue anywhere..

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30633226/48913982-24cbc900-ee8b-11e8-8928-ab940cb629fb.gif)

Did anybody faced with it?

**Comment by dimitriskot** [comment]
Items' styles, when try to drag first item between second (red) and third (blue):
![1](https://user-images.githubusercontent.com/30633226/48914630-226a6e80-ee8d-11e8-9d34-4be3cc61d9ff.png)
.. and that's seems ok.

And items' styles, when try to drag third item after second (red):
![2](https://user-images.githubusercontent.com/30633226/48914703-5180e000-ee8d-11e8-8a96-2183b1c33c0c.png)
... and that's seems not ok =)

**Comment by clauderic** [comment]
Please provide a CodeSandbox example replicating the issue if you'd like me to look at this
