### ISSUE TITLE
Don't require global babelHelpers in ES6 build

### ISSUE THREAD

**Issue by Kovensky** [clauderic/react-sortable-hoc#45]
If the user of the library doesn't happen to use the babel helpers transform and the global helpers runtime, there will be a lot of `ReferenceError: babelHelpers is not defined` that cannot be fixed other than by providing the global helpers.

**Comment by siriwatknp** [comment]
I have this problem ReferenceError: babelHelpers is not defined, do you know how to solve this?

**Comment by clauderic** [comment]
Just published v0.0.11 to npm, which should address this. Give it a spin and let me know if you run into any issues.

**Comment by siriwatknp** [comment]
Yeah! Now it works, thanks @clauderic

**Comment by Kovensky** [comment]
@clauderic yeah, this works, but runtime helpers has a different, unfortunate, issue :/

If you are already using `babel-polyfill`, the runtime helpers will effectively include a second copy of `core-js`, because while the inline helpers will use globals and assume that you have polyfilled them, `babel-runtime`'s helpers always require the ones from core-js's library mode.

As a workaround, I have a `'react-sortable-hoc': 'react-sortable-hoc/dist/commonjs'` alias in the webpack config. This is a really hard problem to solve while making everyone happy; your solution is perfectly fine for people that don't want to ship a full polyfill.
