### ISSUE TITLE
Handle is not working in IE11 browser 

### ISSUE THREAD

**Issue by SanthoshTillid** [clauderic/react-sortable-hoc#450]
I have used react-sortable-hoc in my project it works well on Chrome, Firefox and Safari but not working on IE. I have used the 0.8.3 version. Also tried different versions but no luck. When I dig into the IE developer tools I can see the below error. Please advise.

Object doesn't support property or method 'find'

**Comment by xhesh** [comment]
Workaround it by adding polyfills for both find and from functions of Array. Basically add the code in the two links below to be executed in your componentDidMount either at your parent component or in the component where you plan to use react-sortable-hoc.

Array.find: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill

Array.from: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill

**Comment by kumarharsh** [comment]
You should polyfill your code for older browsers, including IE11. Use the `babel-polyfill` and browserslist to target your browsers and polyfill only what's needed, or use polyfill.io for supporting IE11.

**Comment by clauderic** [comment]
As mentioned by others, you'll need to include polyfills in your project to support older browsers
