### ISSUE TITLE
How to auto scroll on mobile while constraining the container?

### ISSUE THREAD

**Issue by tgj** [clauderic/react-sortable-hoc#452]
Hi guys, I'm trying to scroll on mobile with the following:

`<SortableList
   {...props}
   lockToContainerEdges={true}
/>`

Any thoughts?

**Comment by clauderic** [comment]
Auto-scroll should work on both desktop and mobile, provided your `SortableContainer` element is the scrollable element. If you would like to use a different container, use the `getContainer` prop or if the container is the window, set the `useWindowAsScrollContainer` prop to `true`
