### ISSUE TITLE
Need example of Elements varying heights

### ISSUE THREAD

**Issue by ArifShaikh2611** [clauderic/react-sortable-hoc#456]
Hi,
I am trying to implement drag and drop on elements having different height and width, please provide a example for this.

Thanks,
Arif

**Comment by galtenberg** [comment]
The storybook http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/elements-of-varying-heights?_k=ufejei has an example (source: https://github.com/clauderic/react-sortable-hoc/blob/master/src/.stories/index.js#L355).

You can parameterize width in the exact same way.
