### ISSUE TITLE
onClick event listener

### ISSUE THREAD

**Issue by AnoushSim** [clauderic/react-sortable-hoc#461]
Hi Clauderic! I am trying to add onClick on SortableElement , but it does not work. I understand why it does not work: when dragging, it has already being clicked , but  when I don't want to drag, how can I fix onClick event!

**Comment by heineiuo** [comment]
@AnoushSim  You can set `distance` to 1 (or another value greater then 0)

**Comment by MistrySaurabh** [comment]
> @AnoushSim You can set `distance` to 1 (or another value greater then 0)

@heineiuo , please add some example , it is very helpful to understand .

**Comment by MistrySaurabh** [comment]
created sample demo :

```
import React, { Component } from 'react'
import {SortableContainer, SortableElement, arrayMove} from 'react-sortable-hoc';

const SortableItem = SortableElement(({value}) => {
   
    return (<li style={StyleLi} onClick={()=>{handleClick(value)}}>{value}</li>)
});

const SortableList = SortableContainer(({items}) => {
  return (
    <ul>
      {items.map((value, index) => (
        <SortableItem key={`item-${index}`} index={index} value={value} />
      ))}
    </ul>
  );
});

function handleClick(value){
    console.log('value===',value);
    alert('value='+value);
 }


const StyleLi={
    padding:'8px',
    margin:'5px',
    border : '1px solid red'
}



class AppReactSortableHOC extends Component {
    constructor(){
        super();
        this.state = {
            items: ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5', 'Item 6'],
          };
    }

  
     
    onSortEnd = ({oldIndex, newIndex}) => {
    this.setState({
        items: arrayMove(this.state.items, oldIndex, newIndex),
    });
    };

   
  render() {
        return (<SortableList items={this.state.items} onSortEnd={this.onSortEnd} distance={1} lockAxis="y"></SortableList>);
  }
}

export default AppReactSortableHOC;
```

**Comment by AnoushSim** [comment]
Thanks, it works

**Comment by huykon** [comment]
@MistrySaurabh how to make handleClick inside class component to change another state of component?

**Comment by laclance** [comment]
solution did not work for me

**Comment by shmdt** [comment]
@huykon 
I'm not sure about this solution is the best, but it works for me well:

```javascript
import React, {Component} from "react";
import Sortable from "./UI/Sortable";

class Edit extends Component {
    state = {
        items: []
    };

    onDeleteHandler = (data) => {
        console.log(data);
    };

    render() {
        return (
            <Sortable
                onDeleteHandler={data => this.onDeleteHandler(data)}
                items={this.state.items}/>
        );
    }
}

export default Edit;
```


```javascript
import React, {Component} from "react";
import {SortableContainer, SortableElement} from "react-sortable-hoc";
import arrayMove from 'array-move';

import "./SortableComponent.css";

const SortableItem = SortableElement(({value, sortIndex, onDeleteHandler}) => (
        <span className="sortableImageBlock">
            <span className="sortableImageDelete" onClick={() => onDeleteHandler(value)}>
                <i className="far fa-times-circle fa-2x"></i>
            </span>
            <span className="sortableImagePosition">
                {1 + sortIndex}
            </span>
            <img src={value.image}/>
        </span>
    )
);

const SortableList = SortableContainer(({items, onDeleteHandler}) => {
    return (
        <div>
            {items.map((value, index) => (
                <SortableItem
                    key={`item-${value.id}`}
                    index={index}
                    value={value}
                    sortIndex={index}
                    onDeleteHandler={onDeleteHandler}/>
            ))}
        </div>
    );
});

class Sortable extends Component {
    state = {
        items: this.props.items,
    };

    onDeleteHandler = (data) => {
        this.props.onDeleteHandler(data);
    };

    onSortEnd = ({oldIndex, newIndex}) => {
        this.setState(({items}) => ({
            items: arrayMove(items, oldIndex, newIndex),
        }));
    };

    render() {
        return (
            <div>
                <SortableList
                    axis="xy"
                    items={this.state.items}
                    distance={1}
                    onSortEnd={this.onSortEnd}
                    onDeleteHandler={this.onDeleteHandler}/>
            </div>
        );
    }
}

export default Sortable;
```

**Comment by jedierikb** [comment]
Sometimes, with a quick click and drag, `distance={1}` or even '10` my elements are moving before they get a mouseDown event.  Suggestions?

**Comment by linxianxi** [comment]
> 有时，通过快速单击和拖动，`distance={1}`甚至“10”，我的元素在获得 mouseDown 事件之前就会移动。建议？

@clauderic   Same question. Is there any way to solve it？

**Comment by aunruh** [comment]
short answer: dont use distance={1} but use shouldCancelStart

`function shouldCancelStart(event: SortEventWithTag) {
    let targetEl = event
	if ( targetEl.target.tagName === 'SPAN' ) {
		return true
	}
	return false
}`

sortable item:
`const SortableItem = SortableElement(( {value, sortIndex}: {value: Array<any>, sortIndex: any} ) => {
	let iconClass = value[0].visible ? 'dashicons-visibility' : 'dashicons-hidden'
	let even = sortIndex % 2 === 0 ? 'even' : 'odd'
	return <div className={'lay-sortable-list-item ' + even}>{value[0].name} <span onClick={ () => handleVisibilityClick(value) } className={'lay-item-visibility-button dashicons ' + iconClass}></span></div>
})`

in component:

`<SortableList shouldCancelStart={shouldCancelStart} lockOffset={['0%', '0%']} lockToContainerEdges={true} axis={'y'} lockAxis={'y'} items={this.state.config.sortedTags} onSortEnd={this.onTagsSortEnd} /> `

i just pasted my code that i use in my js app here, so there are a few things you probably won't need.
but the main thing is you disable clicking by using shouldCancelStart={shouldCancelStart} 
and in the shouldCancelStart function you see if the element you clicked on was a span, and then return false to disable the dragging. then in your SortableElement you use a click handler for that span, just like in the previous example.

**Comment by Nabintech** [comment]
better solution ,

"use client";
import React, { useState, useRef } from 'react';
import { SortableContainer, SortableElement } from 'react-sortable-hoc';
import { arrayMoveImmutable } from 'array-move';
import { EditIcon } from "@/assets/icons";

// Define the sortable item component
const SortableItem = SortableElement(({ value, setDragDisable }) => (
    <div className="col-6" style={{ height: '150px', background: '#eee', border: '1px solid #ddd', position: 'relative' }}>
        {value}
        <button
            onClick={(e) => {
                e.stopPropagation();
                console.log('Edit clicked:', value);
            }}
            onMouseEnter={() => {
                setDragDisable(true)
            }}
            onMouseLeave={() => {
                setDragDisable(false)
            }}
            style={{ position: 'absolute', top: '10px', right: '10px' }}
        >
            <EditIcon />
        </button>
    </div>
));

const ImageContainer = SortableContainer(({ children }) => {
    return <div className="grid grid-cols-3 gap-5">{children}</div>;
});

const Page = () => {
    const [items, setItems] = useState(['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5', 'Item 6']);
    const [dragDisable, setDragDisable] = useState(false)

    // Define the sort end handler
    const onSortEnd = ({ oldIndex, newIndex }) => {
        const newArray = arrayMoveImmutable(items, oldIndex, newIndex);
        setItems(newArray);
    };



    return (
        <div className="container">
            <ImageContainer onSortEnd={onSortEnd} axis="xy" useDragHandle={dragDisable}>
                {items.map((value, index) => (
                    <SortableItem
                        key={`item-${index}`}
                        index={index}
                        value={value}
                        setDragDisable={setDragDisable}
                    />
                ))}
            </ImageContainer>
        </div>
    );
};

export default Page;

user onMouseEnter and onMouseLeave
