### ISSUE TITLE
Non responsive after setState

### ISSUE THREAD

**Issue by botoxparty** [clauderic/react-sortable-hoc#465]
Hey,

My sortable list becomes non responsive after i call setState on the first event of sortEnd.

There are no errors or warnings on the console, and the rest of the React app works fine.

Any ideas? 🙃

**Comment by clauderic** [comment]
Closing this unless you can provide a snippet of code / CodeSandbox reproducing the issue.

**Comment by botoxparty** [comment]
No problem here you go:

https://codesandbox.io/s/zkvkjpknwp

I was able to fix this by changing lines 30 and 31 in `'/pages/index.js'`

from 
```
const SortableItem = SortableElement(({ value }) => (
<article key={value.id} className="playlist-item">
```

to 

```
const SortableItem = SortableElement(({ value }, index) => (
<article key={index} className="playlist-item">
```

`value.id` is definitely valid, check the JSON object. Not sure what causes this.
