### ISSUE TITLE
Re Render when press

### ISSUE THREAD

**Issue by lindemann18** [clauderic/react-sortable-hoc#468]
Hello!!!
Is an amazing plugin for drag and drop tables!

The only issue that I have found, that when I add a button and I press it, it does the entire re render cycle again, so I am not able to trigger any event without re rendering the entire thing and simulates like if all the rows han been click at the same time.

Greetings!

**Comment by clauderic** [comment]
This sounds like more of an issue with React than with `react-sortable-hoc`, closing unless you can provide more details as to how this relates to this library

**Comment by zsl1549** [comment]
@lindemann18 大佬怎么解决呢
