### ISSUE TITLE
Request: HOC to prevent drag from starting on given element

### ISSUE THREAD

**Issue by Kovensky** [clauderic/react-sortable-hoc#47]
The use case would be a non-draggable button nested inside a draggable list item.

Right now, the workarounds are to either attach native click events to the button (requiring a ref and extra lifecycle handlers), or to add a delay and hope the users click the button faster than the delay (but that reduces drag responsiveness). Otherwise, the dragging event takes precedence and blocks clicks to any clickable thing inside the SortableElement.

SortableHandle could also be a workaround, but that comes at the expense of being able to drag the SortableElement by dragging its background.

**Comment by burtyish** [comment]
I ran into this problem too. I have a list of draggable items with inputs inside. Using the inputs is impossible since a click on an input is caught by SortableElement.
I've fallen back to using a drag handle in each item.

**Comment by Kovensky** [comment]
The best workaround I've found so far is to directly attach DOM handlers on
the interactable elements for both mousedown and touchstart, and just
calling stopPropagation on the event (definitely don't return false).

This prevents the event from bubbling to the container's handler that then
prevents the default.

**Comment by zaygraveyard** [comment]
I think the best solution would be to add a `shouldSortStart` prop on `SortableContainer`.
That gets called before starting to drag and gets passed the event, the drag starts only if it returns `true`.
Which could render the handle useless.

I can work on a PR if needed.

**Comment by clauderic** [comment]
There are indeed a number of ways to approach this, between a `cancel` function as described by @zaygraveyard, another HOC, or a data-attribute.

I'm still debating which would be the most practical, though I think the HOC approach would be cumbersome so that approach is my least favourite. Would love to hear more people's thoughts / if you can think of other approaches

**Comment by clauderic** [comment]
Just published `0.0.8` to npm with support for `shouldCancelStart`, which should solve most use cases.

Default implementation:
```js
function (e) {
    // Cancel sorting if the event target is an `input`, `textarea`, `select` or `option`
    if (['input', 'textarea', 'select', 'option'].indexOf(e.target.tagName.toLowerCase()) !== -1) {
        return true; // Return true to cancel sorting
    }
}
```

**Comment by Kovensky** [comment]
Nice, will try to use this.

I can't use the default implementation as-is, though, as my interactable element is a `button`.

**Comment by clauderic** [comment]
Should be pretty straightforward, let me know if you run into any issues.

**Comment by Kovensky** [comment]
@clauderic after trying to actually adapt this to work for my use case, it does seem like a pass-through wrapping component would be best...

That the element inside the `SortableElement` instance is non-draggable is a property of the item, not of the `SortableContainer` instance; it's just that the Container should have a way to deal with it. Right now, this requires writing a contrived check inside the Container.

A pass-through wrapper (something used like `<SortableClickable><Children/></SortableClickable>`) would allow for easily indicating which portion of the tree should be clickable. It seems to me that `SortableHandle` is _almost_ like this, but instead of rendering `React.Children.only(this.props.children)` it requires a function to tell it which component to render.

Supporting a `button` (like in my use case) also gets complicated when you actually have elements inside the button. This is the implementation I would end up having to use:

```js
// same as the default whitelist in 0.0.8
// eslint-disable-next-line react/sort-comp
static whitelist = new Set(['input', 'textarea', 'select', 'option'])
handleCancelStart (e) {
  // default behavior
  if (ClassName.whitelist.has(e.target.tagName.toLowerCase())) {
    return true
  }
  for (let target = e.target; target !== this.contentDiv; target = target.parentElement) {
    if (target.tagName.toLowerCase() === 'button') {
      return true
    }
  }
}
```

This requires saving an additional `ref` to the `div` that contains the `SortableContainer` instance (could be done with `withRef`, but requiring one to begin with is the problem) to know where to stop looking. `shouldCancelStart` also runs afoul of `react/jsx-handler-names`.

PS: A lot of the props given to a `SortableContainer` instance look like they should be given to the `SortableContainer` constructor instead (like `helperClass`, `lockAxis`, `useDragHandle`; having to specify them where the instance is used is leaking internals, unless the resulting component takes in `children` instead of rendering the `SortableElement` instance itself like in the examples).

**Comment by clauderic** [comment]
@Kovensky I'm not discarding the idea of a HOC to achieve this. As I mentioned, as a starting point, `shouldCancelStart` should cover most use cases.

As for naming conventions, since this is *not* an event handler per-se, I don't see anything wrong with it. A function name should convey meaning, and I found `shouldCancelStart` to be a lot more meaningful than `handleStart`.

> Supporting a button (like in my use case) also gets complicated when you actually have elements inside the button.

Agreed, a HOC would certainly hide this complexity, which is why it's not out of the cards. That said, looking at the code, it doesn't look all that complicated.

> PS: A lot of the props given to a SortableContainer instance look like they should be given to the SortableContainer constructor instead (like helperClass, lockAxis, useDragHandle; having to specify them where the instance is used is leaking internals

I disagree. All of those props are specific to each instance. Say you want to render two `SortableContainer`s on the page, one using the `x` axis and one using the `y` axis, you'd need to have two different enhanced `SortableContainer` constructors. This also gives you the ability to change these properties on the fly.

**Comment by KrzysztofMaly** [comment]
In my case the solution appeared to be much simpler than all that.
I just used onMouseDown event instead of onClick.
