### ISSUE TITLE
UglifyJS breaks in production builds

### ISSUE THREAD

**Issue by pdooner** [clauderic/react-sortable-hoc#474]
A bump to 1.0.0 resulted in exceptions from UglifyJS during webpack's bundling process.
error message was ...
_ERROR in client.js from UglifyJS
Unexpected token: keyword (const)_

using webpack 4.0
isolated issue to bumping the react-sortable-hoc package to 1.0.0

**Comment by clauderic** [comment]
Could you try using `react-sortable-hoc@1.3.1`? Should hopefully be fixed.

**Comment by pdooner** [comment]
Yes, I am still seeing it in 1.3.1
In troubleshooting the cause, I narrowed it down to the update to 1.0.0, but it has been happening in the versions since then as well.
(thanks for the quick response)

**Comment by shepmaster** [comment]
There's no git tag for 1.3.1, but I don't see any [changes to master](https://github.com/clauderic/react-sortable-hoc/compare/v1.3.0...master) that involve `babel-plugin-transform-async-to-promise`, as the CHANGELOG states. It's only a version bump and the CHANGELOG text. Perhaps a commit got lost somewhere?

**Comment by clauderic** [comment]
Could you try using a build created from this branch https://github.com/clauderic/react-sortable-hoc/pull/477?  Recently switched to `microbundle`, which uses Buble to compile the bundles, and I suspect that might be the issue.

This PR reverts back to using Babel and rollup

**Comment by pdooner** [comment]
Yeah, I ran a build from that branch ([477](https://github.com/clauderic/react-sortable-hoc/pull/477)) and it resolved the issue in my bundling step.
Merci!

**Comment by clauderic** [comment]
Alright, glad to hear. Will release a new version soon and post back here. Sorry for the headaches this may have caused you 😅

**Comment by pdooner** [comment]
np - I can manage with the pre 1.0.0 until you get that package updated.
Thanks for the responsiveness on this one.

**Comment by clauderic** [comment]
@pdooner Just published 1.4.0, which should hopefully resolve all the issues you were facing. If not, let me know and we can re-open this issue.

note: The CommonJS and ES Module builds now use `@babel/babel-transform-runtime`, so `@babel/runtime` has been added as a dependency.

**Comment by pdooner** [comment]
@clauderic - I've bumped to 1.4.0, and the issue is resolved with that version. 
Thanks again for the responsiveness (and for the note - appreciate it)!
