### ISSUE TITLE
helperContainer prop cannot be used to support FullScreen API

### ISSUE THREAD

**Issue by garth** [clauderic/react-sortable-hoc#476]
PR #434 was closed without a working solution.

The helperContainer prop needs accept a function that is then evaluated when the drag begins to be sure that the current full screen status (not the full screen status at the time that the component was created) can be evaluated.

**Comment by clauderic** [comment]
Actually I do believe there is a working solution with the recently introduced `updateBeforeSortStart` prop. Something along these lines (untested) should probably work:

```jsx
class App extends React.Component {
  state = {
    helperContainer: null, // or docucument.body for example
  };

  render() {
    return (
      <SortableContainer
        helperContainer={this.state.helperContainer}
        updateBeforeSortStart={() => new Promise(resolve => {
          const helperContainer = (
            document.fullscreenElement ||
            document.webkitFullscreenElement ||
            document.mozFullScreenElement ||
            document.msFullscreenElement ||
            document.body
          );

          this.setState({helperContainer}, resolve);
        })}
      />
    )
  }
}
```

As mentioned in #434, I'm not completely opposed to supporting this natively, but I'm not sure how common of a use-case this is.

**Comment by garth** [comment]
Not really a good solution, since this will force an unnecessary additional render, it also requires the use of class components (until hooks arrive).
