### ISSUE TITLE
Css artifacts on the clicked item

### ISSUE THREAD

**Issue by MatteoGioioso** [clauderic/react-sortable-hoc#478]
This video shows the current behavior. Even though the `Icon` is unmounted, it still shows up there. It is like it's printed. This happens only on the clicked item

![screencast-localhost-3000-2019 01 10-14-12-36](https://user-images.githubusercontent.com/43592430/50952185-35d7a480-14e2-11e9-87b9-5fb85b1faaf9.gif)

My implementation is very simple, I have a function which set a `isSortable` state to `true`
```
onSortStart() {
    this.setState({isSortable: true})
  }
```

if `isSortable` is true that my component will not render the clickable icon

```
{
    !isSortable &&
    <ButtonIconSmart handleClick={() => handleDelete(id)}/>

}
```

**Comment by clauderic** [comment]
That's because there's a race condition between your `this.setState` call, which is asynchronous, and the logic in `onSortStart`. You need to use the `updateBeforeSortStart` prop instead.

Something like this should do the trick:

```jsx
<SortableContainer updateBeforeSortStart={() => {
  return new Promise((resolve) => 
    this.setState({isSorting: true}, resolve)
  );
}} />

**Comment by MatteoGioioso** [comment]
Any update on this? `updateBeforeSortStart` is not working
https://codesandbox.io/s/pmk3z4y4mm
