### ISSUE TITLE
Can nested list also be drag&droppable

### ISSUE THREAD

**Issue by AnoushSim** [clauderic/react-sortable-hoc#480]
I just wonder, can I make nested list also drag&droppable.... I have a drag&droppable list, which has listitems which on their own have nested lists...can I make that nested list drag&droppable too?

**Comment by AnoushSim** [comment]
Okay, I found a solution. If anybody is interested about it, feel free to ask. I'll show!
Thanks!!

**Comment by tanmaiaccion** [comment]
@AnoushSim having the same problem. Can you provide an example please?

**Comment by rohan51** [comment]
@AnoushSim Your example would be most helpful!
