### ISSUE TITLE
Large Data

### ISSUE THREAD

**Issue by VikrantShirvankar** [clauderic/react-sortable-hoc#483]
Sorting items in grid with large data (more than 500 items) makes drag and drop operation very slow

**Comment by clauderic** [comment]
The DOM is slow, if you're trying to add sorting to a list of 500+ items, you should try using virtualization (for example, [react-tiny-virtual-list](https://github.com/clauderic/react-tiny-virtual-list), [react-virtualized](https://github.com/bvaughn/react-virtualized), [react-window](https://github.com/bvaughn/react-window)). See https://github.com/clauderic/react-sortable-hoc/blob/master/examples/react-virtualized.js

**Comment by VikrantShirvankar** [comment]
is there any example of virtualization with grid?

**Comment by nicoandresr** [comment]
I just have the same problem with large data, and the react-infinity was the best solution for me, here a link of an example with more of 3000 items, point_right: https://codesandbox.io/s/exciting-snow-uehlk

**Comment by tarunrathore123** [comment]
I want to apply for a grid that means both directions x and y.
not only for rows, So how can we virtualize or use infinity here?
