### ISSUE TITLE
Handle the dragging item with an unmount SortItemList

### ISSUE THREAD

**Issue by HuuDuc** [clauderic/react-sortable-hoc#486]
Hi there,

I have an issue when the parent Component re-render, the SortableListContainer is still active when I am dragging an item.

**How to reproduce**
1. Drag an item from the SortableListContainer and keep it.
2. Run somehow something to re render the parent Component
3. Drop the dragging item.

![image](https://user-images.githubusercontent.com/3121689/51352844-adb64980-1a63-11e9-9ca4-8c5e9f62cb9e.png)

**Comment by clauderic** [comment]
Hi @HuuDu,

Could you please share a sandbox on CodeSandbox reproducing the issue? Until then, I'm going to close this issue as it sounds like an issue in your code.

Make sure you are not using any of the higher-order components exported by `react-sortable-hoc` in the render method of your components, as that could cause the issue you described above (see
