### ISSUE TITLE
cannot use with react-dropzone

### ISSUE THREAD

**Issue by geminiyellow** [clauderic/react-sortable-hoc#488]
hi @clauderic thanks for your great job.
but when i try to use it with react-dropzone, it not working,
all action in react-dropzone not working, 
maybe drop handle is stop by this hoc, 
could you tell me how to solve it?

**Comment by iamacatperson** [comment]
@geminiyellow I am having the same issue. `React-dropzone` is working but `react-sortable-hoc` becomes clunky if I have them both on the same page. Did you find resolution for this issue?
