### ISSUE TITLE
Clickable links inside items

### ISSUE THREAD

**Issue by lambdazen** [clauderic/react-sortable-hoc#49]
What is the best way to support links inside sortable items? 

Here's a JSFiddle showing the issue: https://jsfiddle.net/lambdazen/6r7r2cva/7/  -- you can try clicking the links once the page has loaded. It doesn't work. However, a right-click followed by "Open in a new tab" works as expected. 

My current workaround is to attach onMouseDown to a call to window.open. Is there a better way? 

Thanks in advance! Love your library.

**Comment by clauderic** [comment]
Hey @lambdazen, thanks for the kind words and for providing a fiddle :)

To answer your question, there is a better way. As of `0.0.8`, you can pass in a `shouldCancelStart` function to your enhanced SortableContainer to programatically cancel sorting from triggering based on the event. The [default implementation](https://github.com/clauderic/react-sortable-hoc/blob/master/src/SortableContainer/index.js#L34) prevent's sorting from being triggered on `input`, `textearea` and `select` elements. Here's an example to prevent links from triggering sorting:

```js
function shouldCancelStart(e) {
	// Cancel sorting if the event target is an anchor tag (`a`)
	if (e.target.tagName.toLowerCase() === 'a') {
		return true; // Return true to cancel sorting
	}
}
```

You can extend this function any way you see fit to match your use-case :)

**Comment by lambdazen** [comment]
Thanks!

**Comment by aleksanderaleksic** [comment]
A bit late, but i solved the click swallowing by doing this:

`class Something extends Component {
click = false;

onSortEnd = ({oldIndex, newIndex}) => {
        if(this.click){
            console.log('CLICK')
        }else{
            console.log('NO CLICK')
        }
        this.click = false;
    };

    onSortStart = ({node, index, collection}, event) => {
        this.click = true;
    };

    onSortMove = (event) => {
        this.click = false;
    };
} `
