### ISSUE TITLE
Release 1.5.0 npm package needs build?

### ISSUE THREAD

**Issue by garth** [clauderic/react-sortable-hoc#490]
@clauderic thanks for adding support for helperContainer functions. Just wanted to test, but it seems that the npm publish does not have the latest build?

**Comment by clauderic** [comment]
Try upgrading straight to 1.5.2

**Comment by garth** [comment]
Thanks @clauderic, I've tested the latest release and it works with fullscreen apps now. I will updated the docs for my fork and deprecate accordingly.
