### ISSUE TITLE
Is it possible to use SortableElement as children of another component together with siblings?

### ISSUE THREAD

**Issue by MatteoGioioso** [clauderic/react-sortable-hoc#495]
I have prepared a Codesandbox to explain better the situation.
https://codesandbox.io/s/pmk3z4y4mm

Seems like there is a misbehavior when using SortableElement not as direct child of SortableContainer. 
This behavior happens only in case there is another sibling element that takes space.

Sorry if it sounds convoluted, I hope the sandbox will clarify it :smile:

**Comment by clauderic** [comment]
This isn't supported, no. What you're describing is drag and drop functionality, not sorting. Try using `react-dnd`

**Comment by MatteoGioioso** [comment]
I don't know what you mean, but that's not drag and drop. Did you check the codesandbox?
