### ISSUE TITLE
Why does the list scroll to the top when I move the element?

### ISSUE THREAD

**Issue by Aililyer** [clauderic/react-sortable-hoc#499]
Why does the list scroll to the top when I move the element?

**Comment by aswinckr** [comment]
Facing the same issue. Any solution?

**Comment by aswinckr** [comment]
I figured out my issue. It wasn't with `react-sortable-hoc` but with `react-router-dom`. 

The problem was I generated routes dynamically on every state change. Apparently this doesn't retain last scroll locations and refreshes on each.

**Comment by clauderic** [comment]
Resolved by #484
