### ISSUE TITLE
If VirtualScroll is wrapped inside AutoSize dragging an item doesn't trigger scroll

### ISSUE THREAD

**Issue by ahmedelgabri** [clauderic/react-sortable-hoc#5]
Awesome job @clauderic 👍 

I'm having a huge list that I'm using `react-virtualized` but if I want the width to be dynamic, for this I must wrap it with [`AutoSize`](https://github.com/bvaughn/react-virtualized/issues/229) _You should already know this_ 😊 

```js
class VirtualList extends Component {
  render() {
    const { items } = this.props;

    return (
      <AutoSizer disableHeight>
        {({ width }) => (
          <VirtualScroll
            ref="VirtualScroll"
            estimatedRowSize={70}
            rowHeight={70}
            rowRenderer={({ index }) => {
              const { product } = items[index];
              return <SortableItem index={index} product={product} />;
            }}
            rowCount={items.length}
            width={width}
            height={500}
          />
        )}
      </AutoSizer>
    );
  }
}
```

So when I do, I lose the ability to scroll while dragging & item, any hints how to fix this?

**Comment by ahmedelgabri** [comment]
Managed to solve it by wrapping the `<Sortablelist>` itself with `<AutoSizer/>` and passing the width to the `<VirtualScroll />`

```js
<AutoSizer disableHeight>
  {({ width }) => (
    <SortableList ref="SortableList" items={items} width={width} onSortEnd={this.onSortEnd} />
  )}
</AutoSizer>
```

```js
class VirtualList extends Component {
  render() {
    const { items, width } = this.props;

    return (
          <VirtualScroll
            ref="VirtualScroll"
            estimatedRowSize={70}
            rowHeight={70}
            rowRenderer={({ index }) => {
              const { product } = items[index];
              return <SortableItem index={index} product={product} />;
            }}
            rowCount={items.length}
            width={width}
            height={500}
          />
    );
  }
}
```

**Comment by clauderic** [comment]
Sounds like you've solved this :)

**Comment by burtyish** [comment]
Hi @ahmedelgabri, it may be the late hour but I can't seem to wrap my mind around your solution.
There's the `Autosizer`'d `SortableList` and you have the `VirtualScroll`. 
How is the end result composed?
I know this ticket is pretty stale, but would you (or anyone else for that matter) mind expanding on your answer?

Thanks!

**Comment by ahmedelgabri** [comment]
Simply the hierarchy for the solution looks like this and width is getting passed from top to bottom, I hope it makes sense.

```
AutoSizer                 
|__SortableList         
     |__ VirtualList
```

**Comment by burtyish** [comment]
Ah, thanks @ahmedelgabri, I really appreciate your quick answer. I was missing that you apparently also had: 
```js
const SortableList = SortableContainer(VirtualList, {withRef: true});
```

Unfortunately, after following the pattern you described, I still have two big problems:

1. `this.refs.SortableList` is undefined
1. I still can't get autoscroll to work

**Comment by mitchellwarr** [comment]
Thank you for this Issue thread, it fixed my issue. I suggest adding this to the docs somewhere as I only found this fix thanks to Google after reading through the docs and examples.
