### ISSUE TITLE
UMD build doesn't work in a browser because of using the process variable

### ISSUE THREAD

**Issue by Finesse** [clauderic/react-sortable-hoc#503]
There is `process.env.NODE_ENV` expression in the bundle. It fails because the `process` variable is available in a Node environment but not in a browser.

Also the bundle requires the PropTypes package which is not a peer dependency and therefore should be included to the UMD bundle during bundling.

Here is a demo: https://codepen.io/TheFinesse/pen/aXxrWb?editors=1011

The latest version with a working UMD bundle is 0.9.0-beta 🙁

**Comment by clauderic** [comment]
Should be fixed in the next release with this commit: https://github.com/clauderic/react-sortable-hoc/commit/16135dfe66604e6dabb570ecc1ef4a8758de7775

**Comment by clauderic** [comment]
Please re-open this issue if you still see issues with this with version `1.8.2` and higher, going to close it for now as it should be fixed in those versions
