### ISSUE TITLE
Firefox dirtying

### ISSUE THREAD

**Issue by lcfumes** [clauderic/react-sortable-hoc#51]
When the component is moved out of the context, In Firefox, it dirty the page.

Se the images
![dirtying](https://cloud.githubusercontent.com/assets/3665280/18391676/26c93330-7685-11e6-9b3f-3485a676a465.png)

![dirtyin2](https://cloud.githubusercontent.com/assets/3665280/18396691/5b5b1a94-769b-11e6-8516-58e817d3019c.png)

![dirtying3](https://cloud.githubusercontent.com/assets/3665280/18396692/5b5b681e-769b-11e6-9235-b22366803993.png)

Firefox version: 48.0

**Comment by clauderic** [comment]
Would you mind providing more details? What OS are you using? This isn't something I've been able to replicate on Firefox for Mac

**Comment by lcfumes** [comment]
Hey @clauderic, thanks for response.
I'm using ubuntu 16.04 and Firefox 49.0 (now)

Do you want some more informations or some print?

But now we're sure that the problem is on Firefox for Linux.

**Comment by clauderic** [comment]
Ahhhh... I didn't test on Firefox Linux 😅 I'll take a look and get back to you

**Comment by lcfumes** [comment]
Thank you man! :)

**Comment by clauderic** [comment]
Alright, so after a lot of digging, I think I've got a solution. As far as I'm aware, this isn't so much an issue with `react-sortable-hoc` as much as it is an issue with Firefox.

For me, adding `backface-visibility: hidden` to the SortableElement styles fixed the visual glitches. Can you confirm it fixes it on your end as well?

If not, this thread had a lot of other suggestions as well: http://stackoverflow.com/questions/30411909/css-transition-flickering-in-firefox

**Comment by clauderic** [comment]
Going to close this out due to inactivity. Let me know if the proposed fix solved the issue on your end, and if not, feel free to re-open the issue. 

Cheers
