### ISSUE TITLE
Drag helper in wrong styling context

### ISSUE THREAD

**Issue by bradwestfall** [clauderic/react-sortable-hoc#52]
Since the "drag helper" (the new DOM node added to the end of the `<body>` which is the actual element being dragged) is not within the same parent element as the source being dragged, styles have a strong potential of getting messed up on the helper (which may rely on parent context). In other words if I have:

```html
<body>
  <div class="user-list">
    <div class="user">Draggable User</div>
    <div class="user">Draggable User</div>
  </div>
</body>
```

I might depend (in CSS) on a `.user-list > .user` relationship for styling the `<div class="user">`. But when the drag starts, we essentially get...

```html
<body>
  <div class="user-list">
    <div class="user" style="visibility-hidden">Draggable User</div>
    <div class="user">Draggable User</div>
  </div>

  <!-- Helper (the thing being dragged)-->
  <div class="user" style=" ... ">Draggable User</div>
</body>
```

This can be fixed if it is possible to put the _drag-helper_ node as a sibling to the original thing being dragged instead of at the end of the body. Thoughts?

**Comment by bradwestfall** [comment]
I see also that this is related to #40, although I don't think _all uses_ of `.parent > .child` selectors would qualify as "over selecting". I realize there are methodologies out there like BEM which don't encourage any parent-child selectors, and many do inline-styles with React. But there are still many who don't do either of those and there are _lots_ of CSS methodologies in which one uses parent-child selectors in a non-overselecting manner. 

If it is possible to place the _drag helper_ somewhere else, you wouldn't have to impose a CSS methodology opinion on a nice JS tool. Or at least make a mention of it in the docs somewhere. Once I realized what the issue was, it was an easy fix, but it did take a while to find the issue.

Also, GREAT JOB on this tool, I love it

**Comment by clauderic** [comment]
Hey @bradwestfall, first off, thanks for the kind words, it's always nice to hear.

A few of the reasons why I originally chose this approach this decision were discussed in #20, though I'd say the main reason was to minimize the chance of conflicts with other libraries. 

Having said that, you do raise valid points. I'd be willing to at least entertain the idea of having a configurable parent element for the helper node. Conflicts could still arise though, so it would be a _use at your own risk_ kind of feature and most likely.

**Comment by bradwestfall** [comment]
Thanks @clauderic. Yea now that I think about it, I can see the potential conflicts with, not only other tools, but what if the developer wants to count DOM nodes in their container, or is using `:last-child` CSS and now your _drag handle_ is messing with that because it's mixed into the same parent context.

I appreciate the suggestion and you're awesome for wanting to update the API to accomodate edge cases. But honestly, I don't see a lot of value in the configurable parent element helper because it would maybe help for some CSS selectors but not all. I think this is actually more of a general problem of all draggable APIs. Maybe just some mention in the documentation. I probably wouldn't have read it if it weren't smack in the middle of main README (because who reads _all_ the docs before using a tool right), but at least some people will see it and prevent the headache.

**Comment by clauderic** [comment]
Hey @bradwestfall, going to close this one out as I don't want people to think this is a behavior I intend to change, at least for the foreseeable future, and it is now something that is covered in the common pitfalls section thanks to your PR 👍
