### ISSUE TITLE
Chrome warning "Deceptive site ahead"

### ISSUE THREAD

**Issue by srinivasdamam** [clauderic/react-sortable-hoc#534]
May be you know this or happening only to me. 

<img width="1117" alt="Screenshot 2019-04-29 at 1 52 02 PM" src="https://user-images.githubusercontent.com/13461208/56884049-317dca00-6a86-11e9-857b-f00192d6c1a9.png">

**Comment by clauderic** [comment]
Fixed, thanks for the report
