### ISSUE TITLE
Feature request: include prop-types into the UMD build

### ISSUE THREAD

**Issue by Finesse** [clauderic/react-sortable-hoc#537]
The `prop-types` package [should not be a peer dependency](https://github.com/facebook/prop-types#how-to-depend-on-this-package). Also it's very small (1.7KB minified). Therefore it's better to include it into the UMD build than make browsers make an extra HTTP request for the `prop-types` JS file.

**Comment by dominic-p** [comment]
Maybe I'm missing something, but doesn't the documentation you link to specifically suggest that you __don't__ include prop-types in UMD builds?

> For UMD bundles of your components, make sure you don’t include PropTypes in the build.

**Comment by Finesse** [comment]
You are right, my bad. Anyway the `prop-types` requirement for the UMD bundle is a big downside of this library for my project.
