### ISSUE TITLE
Incorrect item positioning in multiline horizontal list

### ISSUE THREAD

**Issue by h15ter** [clauderic/react-sortable-hoc#551]
Hi Guys,
I'm trying to use react-sortable-hoc with multiline horizontal lists. It works perfectly well when items are of the same size, but it totally fails to position items properly if they are different:

Screen recording:
https://i.imgur.com/oYTuiZ0.gifv

Simple demo:
https://codesandbox.io/embed/flamboyant-hawking-vwlbq

What do I do wrong? How to fix it?
Tnx!

**Comment by knarkunas** [comment]
I am pretty sure it is known issue as their demo works in same way (regarding boundaries):

![image_sort_bug_known](https://user-images.githubusercontent.com/37063113/61510155-69980780-a9fa-11e9-934c-1862edbc76f6.gif)
