### ISSUE TITLE
Sortable Item doesn't wrap inside the sortable container

### ISSUE THREAD

**Issue by suryarsp** [clauderic/react-sortable-hoc#554]
const SortableList = SortableContainer((props: {
     folderLink: IFolderLink,
     selectedKey: string,
     onFolderExpandCollapseIconClick(folderLink: IFolderLink)
     onDirectoryDrop(folderLink: IFolderLink, directory: IDirectory)
     onFolderClick(e: any, folderLink: IFolderLink)
     onSortEndCallBack(indexInfo: any, folderLink: IFolderLink)
     onSortStart(e: SortStart)
     onDragStart(e: any, folderLink: IFolderLink)
     onDragEnter(e: any, folderLink: IFolderLink)
     onDragOver(e: any, folderLink: IFolderLink)
     onDragEnd(e: any)
     onFolderliDrop(folderLink: IFolderLink)
     onDrop(link: IFolderLink, files: any[])
     isCustomSortEnabled: boolean;
}) => {
     return (
          <ul className={props.folderLink.isExpanded ? styles.show : ""}>
               {props.folderLink.links.map((link, index) => {
                    return <SortableItem
                         key={"item-" + link.key}
                         index={index}
                         selectedKey={props.selectedKey}
                         folderLink={link}
                         onDirectoryDrop={props.onDirectoryDrop.bind(this)}
                         onFolderClick={props.onFolderClick.bind(this)}
                         onFolderExpandCollapseIconClick={props.onFolderExpandCollapseIconClick.bind(this)}
                         onSortEndCallBack={props.onSortEndCallBack.bind(this)}
                         onDragStart={props.onDragStart.bind(this)}
                         onDragEnter={props.onDragEnter.bind(this)}
                         onDragOver={props.onDragOver.bind(this)}
                         onDragEnd={props.onDragEnd.bind(this)}
                         onFolderliDrop={props.onFolderliDrop.bind(this)}
                         onDrop={props.onDrop.bind(this)}
                         isCustomSortEnabled={props.isCustomSortEnabled}
                    />;
               })}
          </ul>
     );
});
![sorting_issue](https://user-images.githubusercontent.com/21018485/59035997-14f65e00-888c-11e9-9ba1-90fc86cbfb6e.png)

**Comment by suryarsp** [comment]
There is no property to set the width. If it resizes automatically it would be great because of a sortable item with no props to handle its width. kindly help on this issue

**Comment by clauderic** [comment]
You can use the `getHelperDimensions` prop, see the default implementation here: https://github.com/clauderic/react-sortable-hoc/blob/master/src/SortableContainer/defaultGetHelperDimensions.js
