### ISSUE TITLE
SortableContainer inner props (such as axis, lockAxis and others) passed to inner component

### ISSUE THREAD

**Issue by epotockiy** [clauderic/react-sortable-hoc#555]
Yesterday I updated ``react-sortable-hoc`` to the latest version and got a lot of warning that all SortableContainer props attached to dom element component, my component looks like this
```
...
const SortableList = SortableContainer(({items, ...otherProps}) => {
  return (
    <MyCustomComponent {...otherProps}>
      {items.map((value, index) => (
        <SortableItem key={`item-${index}`} index={index} value={value} />
      ))}
    </MyCustomComponent>
  );
});
...
```
I analyzed issue and figure out that in commit https://github.com/clauderic/react-sortable-hoc/commit/9da38750f5dd6d1f689788dfd023a818670f6f94 changed calling of omit util in all component
Previously it look like this
``omit(props, 'propToOmit1', 'propToOmit2', ...)`` ,
now it looks like this
``omit(props, arrayOfPropsToOmit)``
but implementation of util didn't changed and looks like this
```
...
export function omit(obj, ...keysToOmit) {
  return Object.keys(obj).reduce((acc, key) => {
    if (keysToOmit.indexOf(key) === -1) {
      acc[key] = obj[key];
    }

    return acc;
  }, {});
}
...
```
This is the reason of my warnings

It's simple issue, for this reason i wasn't creating PR

**Comment by justinneff** [comment]
Hi, thanks for the awesome library. When would a release be available that contains this fix?
