### ISSUE TITLE
how to style the dragging item

### ISSUE THREAD

**Issue by geminiyellow** [clauderic/react-sortable-hoc#56]
hi @clauderic , thank you for your nice job. it is really helpful.
and, could you tell me how to style the dragging item?
e.g. opacity

**Comment by clauderic** [comment]
Hey @geminiyellow, you can pass in a `helperClass` prop to your enhanced SortableContainer component and then simply style it with css. For example:

```jsx
<SortableContainer helperClass="SortableHelper" />
```
And then in your css:
```css
.SortableHelper {
  opacity: 0.9;
}
```
