### ISSUE TITLE
Drag-handle problems cross-browser

### ISSUE THREAD

**Issue by stahlmanDesign** [clauderic/react-sortable-hoc#57]
A few things I noticed:

Firefox:
The drag handle in your demo page does not show up, but it works.
In some projects (not your demo), as you drag to sort elements, it selects the text on the page (also in IE11)
![firefox-ie11-drag-selects-text](https://cloud.githubusercontent.com/assets/972804/18756814/52049758-80bf-11e6-8311-f0e75ee853c5.gif)

Safari: when using an image as a drag-handle (not background-image), set the image attribute draggable='false' or else it will try to drag the image as if dragging a copy to the desktop.
![safari-drag-image](https://cloud.githubusercontent.com/assets/972804/18756837/64f9501a-80bf-11e6-83bf-3e64d8f5b711.gif)

Chrome: does not work in the responsive simulator
![chrome-touch-simulator-dnd](https://cloud.githubusercontent.com/assets/972804/18756842/686d9ac6-80bf-11e6-914a-8ead50e8261c.gif)

**Comment by clauderic** [comment]
Hey @stahlmanDesign, I think there are multiple things going on here.

Regarding the drag handle on the demo page, thanks for pointing that out. That's simply an issue with the drag handle css styling of the demo site. `react-sortable-hoc` does not provide any styles out of the box, so this isn't really an issue with the library itself.

As for text-selection in certain browsers, you can override this behaviour using `user-select: none;` in css (https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)

Regarding the drag handle issue you were experiencing, again, this is something that is kind of specific to your own implementation, though it might be a good thing to note in the [common pitfalls](https://github.com/clauderic/react-sortable-hoc#common-pitfalls) section of the Readme.

And finally, re: chrome simulator --> It works fine for me on the demo site. By the looks of it, you're also using a pull-to-refresh component. I can only imagine it is also listening to touch events. I believe you simply need to stopPropagation on the `touchstart` event on the `DragHandle`.
