### ISSUE TITLE
Dynamic adding items to a list breaks drag UX

### ISSUE THREAD

**Issue by elrapha** [clauderic/react-sortable-hoc#570]
So so far I am able to add elements to my list
But drag and drop only works if there is initially at least one element already in the list. 

if i start adding from an empty list, the drag fails. So in otherwords, the drag functionality is broken if the list is dynamic and initially empty.

Any help?

**Comment by knarkunas** [comment]
Everything works for me when following best practises with React, could you provide an example of your code that breaks? Could make really thin component structure with fake data to show what is wrong.

**Comment by clauderic** [comment]
Please set up a CodeSandbox replicating the issue if you think this is a bug with react-sortable-hoc. You can do so by forking this sandbox https://codesandbox.io/s/o104x95y86.

Otherwise, the best place to ask for help is StackOverflow
