### ISSUE TITLE
dragHandle issue on mobile

### ISSUE THREAD

**Issue by epap-zenfolio** [clauderic/react-sortable-hoc#578]
Hi. I'm trying to implement React-Sortable-hoc on a proyect and i'm facing a problem on mobile when i combine a grid setup with dragHangle (the small cross arrows in the upper left corner). 

The element dragged get fixed and not follow the mouse. Also there's no way to end the drag. This is working just fine on desktop. Can anubody help me please?
I leave a gif video of the issue
Thanks!
![ReactSorteableHoc](https://user-images.githubusercontent.com/49990055/61962410-cfa70080-af9f-11e9-95b5-0d0395ae13ee.gif)

**Comment by epap-zenfolio** [comment]
I also see that the dynamic created LI at the bottom of the body, does not get the transform css style, so that's why is not following the mouse pointer.

**Comment by benwigley** [comment]
I am getting the same issue

**Comment by epap-zenfolio** [comment]
ok. Temporarly, I found a fix for this. 
1) Go to node_modules folder inside you project and copy the file sortable-hoc.js into you project.
2) Find this line of code:
_this.listenerNode = event.touches ? node : _this.contentWindow;
and replaceit with this:
_this.listenerNode = event.touches ? event.target : _this.contentWindow;
3) When you import SortableContainer into your component (and only this one) should be referenced from this new file in your project and not from "plugins/sortable-hoc"
Regards

**Comment by benwigley** [comment]
Thank you @epap-zenfolio
