### ISSUE TITLE
useWindowAsScrollContainer not working in ie & Firefox

### ISSUE THREAD

**Issue by kapiljugnu** [clauderic/react-sortable-hoc#58]
ie version - 11.0.9600.18426
Firefox Version - 45.2.0

https://jsfiddle.net/vhcd9us3/1/

**Comment by lapetr** [comment]
Firefox version 49.0 (Linux Ubuntu)

- http://clauderic.github.io/react-sortable-hoc/#/advanced/window-as-scroll-container
 - No auto-scroll on drag
 - bad sorting after drag e.g. "Item 1" and scrolling with mouse-wheel to next page
  - ![firefox49-bad-sort](https://cloud.githubusercontent.com/assets/9628720/19680032/635f5f3e-9aa4-11e6-9fb1-629b65f6f5a9.png)


(Chromium v. 53.0 Linux Ubuntu is OK )

**Comment by asafigan** [comment]
It no longer works in chrome either

**Comment by jimyaghi** [comment]
Strangely, only the delay 20ms example works in Chrome (ubuntu) when dragging into scroll overflow.

**Comment by ThanosDi** [comment]
Any info on this? Also why and how is it only working on the 200ms example? 
http://clauderic.github.io/react-sortable-hoc/#/advanced/activate-onpress-200ms?_k=su6f6i

**Comment by jimyaghi** [comment]
i've done pull request that sorts out all of these. can you take a look and see if it sorts out the problem for ya.

**Comment by clauderic** [comment]
`useWindowAsScrollContainer ` was fixed in `0.7.0` thanks to #306, if you still experience issues with this, feel free to reopen
