### ISSUE TITLE
React 15

### ISSUE THREAD

**Issue by JensC** [clauderic/react-sortable-hoc#580]
Hi all,

I am having a hard time to get react-sortable-hoc to work with React 15.6.x. I used the Drag Handle example (without any changes) and was hoping to get an unstyles list that has the drag and drop functionality. However that does not work at all, no dragging possible. All dependencies seemed to be met and the FF debugger console does not show any error. I must do something stupidly wrong. Any ideas what it could be?

Thanks and sorry if this is the wrong place to ask that.
Jens

**Comment by clauderic** [comment]
Please set up a CodeSandbox replicating the issue if you think this is a bug with `react-sortable-hoc`. You can do so by forking this sandbox https://codesandbox.io/s/o104x95y86.

Otherwise, the best place to ask for help is StackOverflow
