### ISSUE TITLE
Saving list order on Firestore

### ISSUE THREAD

**Issue by edoplaza** [clauderic/react-sortable-hoc#582]
Hello, 

I am having trouble trying to update my Firestore collection after reordering the items. I am using React useState and useEffect hooks on my app. The issue is that I don't know when or how to update the data (wondering it I have to first update the state and then post or first post and then update the state).  I am using Firebase onSnapshot for this.
Any help will be appreciated.

**Comment by clauderic** [comment]
Please use StackOverflow to ask questions, issues should only be used to report bugs or feature requests with the library. Thanks!
