### ISSUE TITLE
Make key to start dragging configurable

### ISSUE THREAD

**Issue by pimterry** [clauderic/react-sortable-hoc#584]
Right now, space starts dragging & escape stops.

That's ok, but in much of the rest of my application I use 'enter' to activate most controls.

It'd improve my app UX to be able to use that here, or to potentially allow either. Assuming that that's not popular as a default for everybody, I'd like to be able to configure a list of keycodes that should be used to activate dragging.

**Comment by clauderic** [comment]
This is a good suggestion, if you have time to put together a PR, I'd be happy to review it. Otherwise I'll try to get to this at some point
