### ISSUE TITLE
Can't drag after removing row

### ISSUE THREAD

**Issue by Sorgrum** [clauderic/react-sortable-hoc#6]
I'm using Redux to manage the state of my app, and after I dispatch an action to remove a specific row, I can only drag from the rows above the ones I deleted. I'm including some gifs to help with the visualization: [here](https://gyazo.com/50cb6355991df0c9e8c6f63b739f5cbe) and [here](https://gyazo.com/01599c807cfabe6ce12b1ae1a7761f18).

I'm not using the arrayMove function described in the sample code because I was planning on writing out the logic for that myself using Redux, but I fear that may be the issue.

**Comment by clauderic** [comment]
It's hard to say without seeing some sample code. What I can however tell you is that this library is built to handle elements being dynamically added / removed :p (see react-virtualized / react-infinite demos). 

Make sure your elements are calling `componentWillUnmount()` when you delete them. Also, can I see your implementation of `arrayMove`? And finally, what's the pattern for your item `key`s?

**Comment by Sorgrum** [comment]
Sorry to have interrupted your vacation. I figured it out and it was a pretty stupid mistake on my part. I had mistakenly used the ID property of my rows, which are UUID's instead of using the index of the array.
I just changed my TableRow from `<TableRow key={data.id}}>` to `<TableRow key={index}}>`

**Comment by marcus-nascimento** [comment]
Sorgrum: can you show me your delete code?
