### ISSUE TITLE
Jquery Portability 

### ISSUE THREAD

**Issue by minedun6** [clauderic/react-sortable-hoc#60]
Is there a way to get this on Jquery ? I was trying to read the source code but no idea how react system works so I was hoping that this can get ported to jQuery or native js.

**Comment by clauderic** [comment]
Most likely, yes, assuming you know what you're doing. Most of the animations are implemented using vanilla JS, so you should be able to extract that logic and re-use it. `react-sortable-hoc` uses a Manager to keep track of the various collections and the indexes of the elements in them. Using jQuery, you'll probably be relying on the DOM instead.

Going to close this out as I can't say this is something I ever plan on working on, but I'm happy to answer questions you may have if you choose to go down this path.
