### ISSUE TITLE
performance issues on big lists with collections

### ISSUE THREAD

**Issue by oreporan** [clauderic/react-sortable-hoc#608]
Hey, using this sandbox example - https://codesandbox.io/s/81v9lxk392

I see that for  lists with length > 150 performance drops and there is a lag when dragging. 

I see that `onSortStart` is called immediately.

The weird part is, when I flatten out my collections to one list (so the final length is the same) - I don't run into performance issues

**Comment by clauderic** [comment]
If you're attempting to make a list of 100+ items sortable, I strongly recommend that you look at virtualization to reduce the amount of items rendered in the DOM. `react-sortable-hoc` supports pretty much all virtualization libraries out of the box, https://github.com/clauderic/react-sortable-hoc/blob/master/examples/react-virtualized.js for example
