### ISSUE TITLE
Drag reordering animation jittery and unstable using Tables as rows (unorthodox implementation)

### ISSUE THREAD

**Issue by nathanhere** [clauderic/react-sortable-hoc#615]
I'm opening and closing this issue only for the benefit of others who might have this same issue now or in the future. I encountered a strange drag animation behavior when I was used an unorthodox approach to using react-sortable-hoc with a table as each row (for reasons I won't get into here). I found that the drag reordering animation triggers would get really jittery and unstable when there was more content above the sortable list. The solution was to use the option **`useWindowAsScrollContainer`** within the  **`<SortableContainer>`** component:
```
<SortableContainer useWindowAsScrollContainer> ... </SortableContainer>
```

**Comment by Hildemir** [comment]
I got exactly the same problem and indeed it worked! Thank you so much!
Would you know why this fixed the problem?

**Comment by nathanhere** [comment]
@Hildemir as much as I strive for root cause analysis for every problem, I unfortunately couldn't spare the bandwidth to do so in this situation :( But it's a solution that's still going strong for me! Great to hear that it worked for you too! :)
