### ISSUE TITLE
Prevent item sort on specific items

### ISSUE THREAD

**Issue by joelgb2194** [clauderic/react-sortable-hoc#625]
I am trying to use this library to sort out the priority order of my user roles. I want to restrict users from moving a role above the admin role kind of like how discord handles their roles. example gif https://gyazo.com/db204bcb3bfdd7f2de2d625ef7625a15

How can I restrict the sorting of my admin item? 

Side note how do I add the underlay to show the placement of the new index as shown in the same gif above?

**Comment by clauderic** [comment]
To achieve the same behaviour as the gif posted above, just make sure the first item is not wrapped in `SortableElement`. For example:

https://codesandbox.io/s/react-sortable-hoc-starter-vs9jt
