### ISSUE TITLE
2 Column container problem

### ISSUE THREAD

**Issue by ditorojuan** [clauderic/react-sortable-hoc#626]
Hi guys, first of all, I want to congratulate you for such a good library.

I've encountered a bug on the library, working with 2 columns `SortableContainer`'s,  it has a weird animation when dragging some components.

To reproduce this problem just go to http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=8abqva and edit the width of the div with the classes `Showcase__style__list Showcase__style__stylizedList Showcase__style__grid`  to `width: 350px`
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22530892/67627610-541e4f00-f82d-11e9-90db-8322523b81c0.gif)

**Comment by chaomao** [comment]
I think it is solved in https://github.com/clauderic/react-sortable-hoc/issues/617
