### ISSUE TITLE
Smooth animation on drop item

### ISSUE THREAD

**Issue by NgKhanh** [clauderic/react-sortable-hoc#63]
I love this one and using on my project, but I hope you can add smooth animation when we drop item, like this one. 
http://chenglou.github.io/react-motion/demos/demo8-draggable-list/

Regards!

**Comment by clauderic** [comment]
I'm going to close this issue as I don't have any plans to work on this in the near future, as I think it would be quite challenging to implement given the current implementation. If you feel strongly about this, PRs are welcome!

**Comment by chrisdrackett** [comment]
aw, I just came here to make the same request. Sad panda.
