### ISSUE TITLE
Ability to change handle/card styling onClick

### ISSUE THREAD

**Issue by laytong** [clauderic/react-sortable-hoc#64]
When using the html5 DND api and a handle I can benefit from the :active pseudo class. Since we are creating a copy we don't have an ability to do that. Ideally i'd be able to add some kind of `-selected` class to my handle or have the :active working on the handle

To give an example of my use case: 
My item has a handle and on click + drag the handle changes colour.

**Comment by clauderic** [comment]
If I'm understanding correctly, you can use the `helperClass` prop to achieve this functionality. Check out the docs for it and let me know if it fits your use-case

**Comment by laytong** [comment]
Ok, I see now. Can I recommend either a better name if it's specifically for during a selection? Additionally there could be an example using it?

Thanks
