### ISSUE TITLE
Where is the source code of demo grid ?

### ISSUE THREAD

**Issue by yuexianqiang** [clauderic/react-sortable-hoc#659]
http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=lgth92 #658

**Comment by abinayakumaran** [comment]
i too need the source code of the grid

**Comment by pjw9195** [comment]
i too need the source code of the grid!

**Comment by geraudi** [comment]
Hi,
The source code of the examples are in the folder src/.stories
For grid: https://github.com/clauderic/react-sortable-hoc/blob/35996f5c120d4518005ef0f93689ece9aef5c42d/src/.stories/index.js#L516

**Comment by yuexianqiang** [comment]
> https://codesandbox.io/s/vm917ww2z3

**Comment by yuexianqiang** [comment]
> https://codesandbox.io/s/vm917ww2z3

the demo use display: grid,  but the http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=lgth92 #658 grid demo use float,  i want to use float
