### ISSUE TITLE
Button inside SortableContainer.

### ISSUE THREAD

**Issue by ashishtechuz** [clauderic/react-sortable-hoc#660]
Is it possible to allow button to click inside SortableContainer? like  I have a list of products which can be sorted. but the button inside div should be clickable as I'm opening popover of tags of that particular product.

**Comment by walid-mokrani** [comment]
Just use `shouldCancelStart` and return true when the event target is of type button or whatever

**Comment by pjw9195** [comment]
@walid-mokrani 
Show me example used shouldCancelStart?

**Comment by ashishtechuz** [comment]
@walid-mokrani I've set

**Comment by yairopro** [comment]
@ashishtechuz you rock !

**Comment by pauloalozen** [comment]
Two days lost searching on this, and @ashishtechuz solve in one line...thanks man!

**Comment by Motoxpro** [comment]
Here is another solution that doesnt use distance. `distance` was causing a bug for me.

```
/**
 * Function to see if a target or any of it's parents have a property
 */
export const targetHasProp = (
  target: Element | null,
  hasProp: (target: Element) => boolean,
): boolean => {
  while (target) {
    if (hasProp(target)) {
      return true;
    }
    // eslint-disable-next-line no-param-reassign
    target = target.parentElement;
  }
  return false;
};
```

```
 const shouldCancelSortStart = (coach: SortEvent | SortEventWithTag): boolean => {
    // Cancel sort if a user is interacting with a given element
    return targetHasProp(coach.target as Element, (el) => {
      return ['button'].includes(el.tagName.toLowerCase());
    });
  };
```

```
<SortContainer
      ...
      shouldCancelStart={shouldCancelSortStart}
    >
...

**Comment by ciprian-shoreline** [comment]
> Here is another solution that doesnt use distance. `distance` was causing a bug for me.
> 
> ```
> /**
>  * Function to see if a target or any of it's parents have a property
>  */
> export const targetHasProp = (
>   target: Element | null,
>   hasProp: (target: Element) => boolean,
> ): boolean => {
>   while (target) {
>     if (hasProp(target)) {
>       return true;
>     }
>     // eslint-disable-next-line no-param-reassign
>     target = target.parentElement;
>   }
>   return false;
> };
> ```
> 
> ```
>  const shouldCancelSortStart = (coach: SortEvent | SortEventWithTag): boolean => {
>     // Cancel sort if a user is interacting with a given element
>     return targetHasProp(coach.target as Element, (el) => {
>       return ['button'].includes(el.tagName.toLowerCase());
>     });
>   };
> ```
> 
> ```
> <SortContainer
>       ...
>       shouldCancelStart={shouldCancelSortStart}
>     >
> ...
> ```

You can also use ids for elements and can adapt the @Motoxpro's solution.
