### ISSUE TITLE
Width of items with padding/border changes

### ISSUE THREAD

**Issue by Philipp91** [clauderic/react-sortable-hoc#67]
Because react-sortable-hoc uses offsetWidth (see https://github.com/clauderic/react-sortable-hoc/blob/2e96f2b31e33b1befcb49c9a71cd365c43a6d8d2/src/SortableContainer/index.js#L161), which includes borders and paddings (see https://developer.mozilla.org/de/docs/Web/API/HTMLElement/offsetWidth), as the width of the helper, it is too wide. This results in visual "jump" when dragging items.

Possible solutions:
- always set "box-sizing: border-box" on the helper
- use clientWidth instead.

Workaround:
- set "box-sizing: border-box" on your SortableElements manually.

**Comment by clauderic** [comment]
Both `clientWidth` and `offsetWidth` include padding, so I opted for the forced `box-sizing: border-box` on the helper approach. Thanks!
