### ISSUE TITLE
我想要改变拖动元素的样式,

### ISSUE THREAD

**Issue by 18355166248** [clauderic/react-sortable-hoc#673]
我想要改变拖动元素的样式, 就是默认添加到body上的那个拖拽元素的样式 怎么动态修改

**Comment by clauderic** [comment]
使用`helperClass` 属性将自定义类名称应用于当前被拖动的元素

**Comment by 18355166248** [comment]
已经实现了 谢谢

**Comment by answer33** [comment]
> 已经实现了 谢谢

怎么实现的，可以贴下相关代码么。🙏

**Comment by dwb1994** [comment]
helperClass an be achieved, but the classname did not show in class props of dom, it's strange 😰

**Comment by ggyuer** [comment]
怎么实现的呢？
