### ISSUE TITLE
ReactCSSTransitionGroup when removing/adding items to sortable not working

### ISSUE THREAD

**Issue by lecap** [clauderic/react-sortable-hoc#68]
I tried using the ReactCSSTransitionGroup element with your great sortable and can make the sortable animate on initial mount (although looks jerky for some reason). But was unable to make it able to animate the adding/removing of individual items to a sortable. Similar code does work for normal object lists where you remove/add to them. Do you have any examples or ideas why it isn't working with a Sortable? I forked another fiddle to show what I mean https://jsfiddle.net/r2LpL7be/

And here is an example of a standard array with splice + animation: http://codepen.io/agrewell/pen/ZYdGOJ

**Comment by clauderic** [comment]
Try this https://jsfiddle.net/fvg54zfr/4/
