### ISSUE TITLE
Erratic behaviour in Firefox (mac)

### ISSUE THREAD

**Issue by mesh-newbie** [clauderic/react-sortable-hoc#689]
Hi, I've noticed that react-sortable-hoc behaves erratically on firefox (works perfectly on chrome/safari).
The ghosted object often won't drag and the actual drag position (i.e where clicked/mouse-down) is different. Best explained in this video
![firefox](https://user-images.githubusercontent.com/8045203/79922561-73fa9c80-8477-11ea-8bd7-d37d56392994.gif)
To reproduce: go [here](https://css-tricks.com/draggin-and-droppin-in-react/) 

Granted that the demo is a 9months old (different rsh version?)... but the behaviour is similar to what I'm seeing in my code.

Thanks :-)

**Comment by bogdansoare** [comment]
Also having this issue, it's almost unusable on firefox

**Comment by mesh-newbie** [comment]
Hey guys... has this issue been resolved?

**Comment by 311289189** [comment]
This repository is no longer being maintained

**Comment by mesh-newbie** [comment]
@311289189 is that the official status of the repo now? (no longer maintained)

**Comment by marcin-piela-sf** [comment]
It's not a problem with library, you have to turn off default firefox behavior on image https://www.redips.net/firefox/disable-image-dragging/

In react:
```
onMouseDown={(e: MouseEvent) => {
    // https://www.redips.net/firefox/disable-image-dragging/
    e.preventDefault();
}}
```

**Comment by nbhaohao** [comment]
> It's not a problem with library, you have to turn off default firefox behavior on image https://www.redips.net/firefox/disable-image-dragging/
> 
> In react:
> 
> ```
> onMouseDown={(e: MouseEvent) => {
>     // https://www.redips.net/firefox/disable-image-dragging/
>     e.preventDefault();
> }}
> ```

save my time, Thank you
