### ISSUE TITLE
example for writing test suite 

### ISSUE THREAD

**Issue by sagar-gavhane** [clauderic/react-sortable-hoc#694]
Hey, you're really doing an awesome job. I really like this library and recommended to everyone who wants to implement drag and drop list. In this issue, I just want to ask you that "Do we've any example for writing a test suite for SortableComponent?".

**Comment by sagar-gavhane** [comment]
@clauderic any updates?

**Comment by anton6** [comment]
I am using react-testing-library and haven't found a way to simulate drag and drop tests. So only wrote tests to make sure items get rendered correctly.

**Comment by VanTigranyan** [comment]
> I am using react-testing-library and haven't found a way to simulate drag and drop tests. So only wrote tests to make sure items get rendered correctly. If anyone can share example of simulating drag and drop component test that would be great.

That's a limitation of jest(jsdom) itself. It is not loading styles, meaning your elements doesn't have neither width nor height, which in turn means it cannot be dragged and dropped. So the way to test d&d is usually use smth like Cypress, which has an actual browser environment. Meanwhile you can just mock HOCs.
