### ISSUE TITLE
Example only work ie11 +

### ISSUE THREAD

**Issue by suhaotian** [clauderic/react-sortable-hoc#7]
What about ie10 and below..

**Comment by clauderic** [comment]
Not sure why Its not working in IE10, must be a fairly simple fix. Feel free to submit a PR :) otherwise I'll take a look at this in about a week

**Comment by dmiller9911** [comment]
Looks like the issue was doing an uppercase on the ms prefix.  I put in a pr here:  https://github.com/clauderic/react-sortable-hoc/pull/10

**Comment by clauderic** [comment]
It should work in IE10 now in the `0.0.2` release, though the performance wasn't great on my VM. Not sure if it'll be better on an actual machine. It will also work in IE9, though IE9 does not support css transitions, so no animations.
