### ISSUE TITLE
Since when can you set initial state like this?

### ISSUE THREAD

**Issue by jharrowmortelliti** [clauderic/react-sortable-hoc#70]
```
class SortableComponent extends Component {
    state = {
        items: ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5', 'Item 6']
    }

```

Not working when I try to compile it.  I thought you had to set initial state in the constructor.

**Comment by clauderic** [comment]
You need to use `babel-stage-2` if you want to use that syntax. You can read more about class properties here: http://babeljs.io/docs/plugins/transform-class-properties/
