### ISSUE TITLE
How to get new array after drag and drop

### ISSUE THREAD

**Issue by Jonofat** [clauderic/react-sortable-hoc#702]
Apologies if this already has an answer somewhere but I couldn't find it. 

Once dragging and dropping I want to save the changes to the database, but I need the new array order to do that. I have changed this into a functional component like this:

```
  const onSortEnd = ({ oldIndex, newIndex }) => {
    setItems((items) => arrayMove(items, oldIndex, newIndex));
    console.log(items);
  };
```

I thought that the console.log(items) at this point would give me the new array with new order but it is still giving me the old order from state. How can I get the new order to send to the database?

**Comment by emersonthis** [comment]
The `index` prop is intentionally _not_ inherited by the wrapped item, but you can pass it yourself.

The way to do this is demonstrated under the FAQs: https://github.com/clauderic/react-sortable-hoc#wrapper-props-not-passed-down-to-wrapped-component

**Comment by Jonofat** [comment]
I managed to get it like so:

`const newArray = arrayMove(items, oldIndex, newIndex);`

**Comment by emersonthis** [comment]
Great. If your issue is resolved, remember to close it.
