### ISSUE TITLE
Please tell me where to view the code in grid?

### ISSUE THREAD

**Issue by sinevitch** [clauderic/react-sortable-hoc#704]
Why can't I view the source on the tab Grid?

![image](https://user-images.githubusercontent.com/35930695/83429606-f003df00-a43c-11ea-8fd9-f0a557643910.png)

**Comment by sinevitch** [comment]
I would like to do the same as in the example? Please tell me where to view the source code?

**Comment by dev-assassin** [comment]
@sinevitch 
Also I'd like to view that code.
so did you find it?
