### ISSUE TITLE
react-sortable-hoc causes Input to loses focus when onChange is called

### ISSUE THREAD

**Issue by eakl** [clauderic/react-sortable-hoc#729]
CodeSandox **with** React-Sortable-HOC: https://codesandbox.io/s/with-react-sortable-hoc-0jcw7
CodeSandox **without** React-Sortable-HOC: https://codesandbox.io/s/without-react-sortable-hoc-xlfsi

Input wrapped in react-sortable-hoc loses focus when onChange is fired

**Steps to reproduce**
Focus on any row of Column 2 with onChange prop, type a 2-digit number (e.g. '23') on it and then lose focus after the 1st digit (e.g. after '2')

**What is expected?**
That the InputNumber don't lose focus after the 1st digit is entered (e.g. after '2'). Allowing for multi-digit input (e.g. '2345')

**What is actually happening?**
After the 1st digit is entered, InputNumber loses focus 

**Hypothesis**
The component is being mounter at every re-render?

**Comment by mattford** [comment]
@eakl I think it's because you're defining these components inside your main component:
```
// React Sortable HOC
  const SortableRow = (props) => {
    const index = data.findIndex((x) => x.index === props["data-row-key"]);
    return <RowComponent index={index} {...props} />;
  };

  const SortableBodyWrapper = (props) => {
    return (
      <BodyWrapperComponent
        helperClass="row-dragging"
        useDragHandle={true}
        onSortEnd={handleSortEnd}
        {...props}
      />
    );
  };
```

which will mean every time your main component renders, those child components will be completely rerendered even if none of their props have changed

**Comment by foreverpinetree** [comment]
@mattford Thanks!!! Your example help me solve my problem :)

**Comment by alihesari** [comment]
I found another solution: https://github.com/clauderic/react-sortable-hoc/issues/120#issuecomment-274082422

**Comment by mattford** [comment]
> I found another solution: [#120 (comment)](https://github.com/clauderic/react-sortable-hoc/issues/120#issuecomment-274082422)

That's actually the same solution 👍

**Comment by tinyzh** [comment]
My solution 
> Update SortableItem only when sorting

[code sandbox](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-x6frl?file=/App.tsx)

**Comment by ZmSama** [comment]
@tinyzh Great, 95% of the problem was solved. Sure enough, the Chinese didn't cheat the Chinese

**Comment by 321802282** [comment]
> My solution
> 
> > Update SortableItem only when sorting
> 
> [code sandbox](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-x6frl?file=/App.tsx)

thank you, this helped me a lot

**Comment by scplay** [comment]
> My solution
> 
> > Update SortableItem only when sorting
> 
> [code sandbox](https://codesandbox.io/s/shi-shi-bao-cun-de-bian-ji-biao-ge-forked-x6frl?file=/App.tsx)

Thx a lot. Even though this works well, but this work around seems sort of weird. We must separate the denpendency from dataSource to dataRef and an increment remark(such as date updated after sorted). LOL really a burden for maintainence
