### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by roeycohen** [clauderic/react-sortable-hoc#764]
No commits or pull requests were merged for almost a year now... some PR are important and great.
Is that mean the project is dead?

@clauderic, do you recommend another project instead? do you need help managing this project?

**Comment by ncpope** [comment]
I just found this project and noticed that it hasn't been updated in almost a year. My use case is pretty simple so I might just fork it and move forward.

**Comment by TrejGun** [comment]
guys you can try this lib https://github.com/atlassian/react-beautiful-dnd

**Comment by roeycohen** [comment]
@TrejGun it also dead.. no commits for almost a year now..

**Comment by clauderic** [comment]
This project is not officially dead, and is used in production by millions of consumers on many high-profile websites such as the Shopify admin. I intend to maintain it in terms of fixing critical bugs, but no new features will be added.

Development efforts are being redirected towards this project https://github.com/clauderic/dnd-kit, which is intended to be the successor to this library. It supports all of the features of `react-sortable-hoc`, but with a much more modern, extensible and sustainable architecture.

**Comment by TrejGun** [comment]
@clauderic typical programmer :) 
end users don't care about how extensible and shiny your code is
but oly about critical bugs such as this one https://github.com/clauderic/react-sortable-hoc/issues/523
which exists for about 2 years and made me migrate from this lib

**Comment by clauderic** [comment]
Grid support for `react-sortable-hoc` was always experimental, and never labeled as a stable core feature; I'm sorry if you've had issues with it.

Having said that, perhaps you misunderstand the nature of open source projects. The code is provided as is, without guarantees. You're free to fork it, modify it, and use it commercially, profit from it, all without giving any credit or compensation to the original author. The least you could do is be polite.

**Comment by roeycohen** [comment]
> This project is not officially dead, and is used in production by millions of consumers on many high-profile websites such as the Shopify admin. I intend to maintain it in terms of fixing critical bugs, but no new features will be added.
> 
> Development efforts are being redirected towards this project https://github.com/clauderic/dnd-kit, which is intended to be the successor to this library. It supports all of the features of `react-sortable-hoc`, but with a much more modern, extensible and sustainable architecture.

10q @clauderic ❤

**Comment by roeycohen** [comment]
wow, dnd-kit looks a-m-a-z-i-n-g!!

**Comment by yuri-scarbaci-lenio** [comment]
@clauderic  ty a lot, we were planning to take over this and re-do it from scratch for a more modern approach and we recently found out your dnd-kit which was what we were looking for! can't wait to migrate to dnd-kit! 

Once again, thanks a lot for all your amazing work!

**Comment by clauderic** [comment]
I've added a notice for new (and existing) consumers which should help clarify the state of the project and why development efforts have been redirected towards `@dnd-kit` rather than trying to re-invest in `react-sortable-hoc`.

In future versions of React, the findDOMNode method will be deprecated. This method is a critical piece of the architecture of react-sortable-hoc, and it's unlikely that the library could continue to exist with its current architecture once this method is deprecated.

https://github.com/clauderic/react-sortable-hoc#%EF%B8%8F-important-notice-for-new-consumers
