### ISSUE TITLE
react17.01 peer dependency warning

### ISSUE THREAD

**Issue by freedyc** [clauderic/react-sortable-hoc#769]
warning " > react-sortable-hoc@1.11.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-sortable-hoc@1.11.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".

**Comment by Develliot** [comment]
Just adding that I'm using it with react 17 and I haven't noticed any issues

**Comment by freedyc** [comment]
So please change peerDependencies, Avoid download dependency alerts

**Comment by freedyc** [comment]
I changed the title, and I can close it when it's published
