### ISSUE TITLE
Feature Request: Keyboard navigation

### ISSUE THREAD

**Issue by jbovenschen** [clauderic/react-sortable-hoc#77]
First of all, thanks for this amazing helper library to support drag and drop within list.

The feature request: Be able to drag and drop within list by using the keyboard.
This can be implemented using by a combination of the **Shift + Arrow keys** or **CMD / CTRL + Arrow keys**.

In my mind there are 2 possible behaviours for this feature. 
- On key press the active item will move the list item every 1 ms 1px further.
- On key down the active item will move to the next position in the given direction.

I would be happy to help / or implement this feature.

**Comment by clauderic** [comment]
Hmmm. I'm open to keyboard support, but I'm not sure I would handle it the way you describe. Do you have examples of how other libraries handle this?

I'd be more inclined to have a more primitive version of keyboard sorting with tabindex support and up/down arrows simply trigger the focused item to shift up or down.

**Comment by jbovenschen** [comment]
Hmm, guess you're right with the more primitive version, people who depend on "alternative" navigation does not likely need feedback as in with touch / pointer navigation. 

As an example I found [this](https://www.sitepoint.com/accessible-drag-drop/). You just select the items you want to move tab through the whole list and press space to swap the items, didn't found any examples which have a solid solution for this.

**Comment by clauderic** [comment]
Closing this as I don't really have any intention on working on this for the moment, but happy to keep discussing here.

**Comment by yashv26** [comment]
Lifting an item is done only with spacebar right now. Enter key can be added as well to lift an item if possible.
