### ISSUE TITLE
Is there way to lock draggable area to parent container

### ISSUE THREAD

**Issue by volle241** [clauderic/react-sortable-hoc#771]
Hi!

I use `lockAxis="y"` and i can't drag item lefter or righter. And it's ok. But also I need to prevent drag the component outside of the parent up and down.

**Comment by sivanesh-12** [comment]
I too face the same issue here

**Comment by clauderic** [comment]
Have you tried the `lockToContainerEdges` prop?

**Comment by 86driver** [comment]
> Have you tried the `lockToContainerEdges` prop?
lockToContainerEdges not effect in version 2 have you solve this problem yet ?
