### ISSUE TITLE
Weird dragging behavior when wrapping SortableItem inside a div element

### ISSUE THREAD

**Issue by VnVentX** [clauderic/react-sortable-hoc#772]
It is hard to swap the item when it is wrapped inside another div.
I have been trying many different ways but still can't solve the problem. Is there any workaround?
I have a demo here: https://codesandbox.io/s/swap-game-jgqm4

**Comment by clauderic** [comment]
This type of multi-row per column based markup isn't well supported by `react-sortable-hoc`, try re-implementing it with [`@dnd-kit`](https://github.com/clauderic/dnd-kit) and see if you have better luck.
