### ISSUE TITLE
Is it possible to sort a responsive element and keep its size?

### ISSUE THREAD

**Issue by JohnB** [clauderic/react-sortable-hoc#773]
I haven't found any issues that address my problem - apologies if someone has already asked it.

I have a set of sortable images whose size adjusts as the window (and surrounding containers) is resized. For example, its width property is something like `calc((100% - 10px)/2)` so I don't know the current size in pixels.

Now when I try to drag the image, it seems to disappear - I believe because `100%` becomes `0px`. Forcing a `min-width` and `min-height` allows it to be visible and draggable, but its size is completely different from the size of the original item being dragged. Any suggestions on how to solve this?

~Hopefully the attached video (using the forced min size) will make it more clear.~ 
(_video removed due to company concerns_)

**Comment by JohnB** [comment]
Problem solved via `getHelperDimensions()` and some CSS.

**Comment by lukemcgregor** [comment]
@JohnB do you have an example of how to do this?
