### ISSUE TITLE
Is it possible to have custom placeholder when sorting items?

### ISSUE THREAD

**Issue by junqdu** [clauderic/react-sortable-hoc#779]
E.g.
![Screen Shot 2021-03-18 at 11 16 03 AM (2)](https://user-images.githubusercontent.com/4250728/111679039-2220da80-87de-11eb-9696-ff1bd86a1fe8.png)
 A vertical bar to indicate where the item/s going to be reordered to

**Comment by junqdu** [comment]
Or is it possible for dnd/kit to achieve that? Thanks!

**Comment by clauderic** [comment]
Not easily, you'd be better served using [`@dnd-kit`](https://github.com/clauderic/dnd-kit) for this type of use-case.

**Comment by junqdu** [comment]
@clauderic Thanks for the reply, but for @dnd/kit, I didn't find a way to customize the "placeholder", I know we can customize the overlay, which is the ghost that is being dragged.

**Comment by clauderic** [comment]
Please open an issue with a codesandbox of what you are trying to achieve in the [@dnd-kit](https://github.com/clauderic/dnd-kit) repository and we can continue the discussion there.
