### ISSUE TITLE
Grid sort: detection needs to include the whole square, not just the first half

### ISSUE THREAD

**Issue by smurfs2549** [clauderic/react-sortable-hoc#782]
When large image on the left, small graph on the right, it's hard to move the larage image to the right.  
Like the the screenshot: 
https://user-images.githubusercontent.com/8286468/111748332-5c1bda80-88cb-11eb-8c38-9cff9a97c6d9.mp4

https://codepen.io/smurfs/pen/eYBwywN?editors=1111

**Comment by clauderic** [comment]
Grid sorting in `react-sortable-hoc` is only optimized for tiles of the same size at the moment. Try using [`@dnd-kit`](https://github.com/clauderic/dnd-kit) for more advanced use cases.

**Comment by smurfs2549** [comment]
Thanks for your replying. I tried used dnd-kit package, it's really nice package. But I have another two questiions used dnd-kit.
      One is the sortable box redraw when the box picked up.
      The other is dragging a box to move it, the whole screen starts scrolling. (https://github.com/clauderic/dnd-kit/issues/23.).

**Comment by smurfs2549** [comment]
Thanks! Will open an issue in the @dnd-kit repository.
