### ISSUE TITLE
Examples source code

### ISSUE THREAD

**Issue by pkerpedjiev** [clauderic/react-sortable-hoc#85]
Pardon if this is a silly question, but is there a way to see the source code for the examples located here (http://clauderic.github.io/react-sortable-hoc/) without opening `https://github.com/clauderic/react-sortable-hoc/blob/master/src/.stories/index.js`?

**Comment by clauderic** [comment]
Hey @pkerpedjiev, unfortunately not currently, though it is on my to-do list. Is there a specific use-case you'd like me to help you with?

**Comment by pkerpedjiev** [comment]
That's very kind of you, but I think I can figure it out with the source code in `index.js`. The examples are really nice and it would great if their source was easily accessible. But if it's already on your todo list, you can just close this issue.

**Comment by jason00111** [comment]
@clauderic Is there any way to see the source code for the multiple lists example located here: http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/multiple-lists?_k=2ibm5h ?

**Comment by rvlewerissa** [comment]
Hi, I need the source code of the multiple list too. Maybe just explain to us how to make one?

**Comment by clauderic** [comment]
Hey @rvlewerissa, assuming you already followed the basic instructions, you'll need to make sure your SortableElements are all wrapped under the same SortableContainer, and then give them a collection prop to distinguish which list they should be part of.

The setup looks a little like this:
```
<SortableList>
  <SortableElement index={1} collection={0} />
  <SortableElement index={2} collection={0} />
  <SortableElement index={3} collection={0} />

  <SortableElement index={1} collection={1} />
  <SortableElement index={2} collection={1} />
  <SortableElement index={3} collection={1} />

  <SortableElement index={1} collection={2} />
  <SortableElement index={2} collection={2} />
  <SortableElement index={3} collection={2} />
</SortableList>
```

You'll need to modify your `onSortEnd` handler to make sure you update the right collection in your state (`onSortEnd({oldIndex, newIndex, collection}) => { ... }`)

I'll try to put a fiddle together by the end of the day.

**Comment by clauderic** [comment]
**Update:**
Here's a basic fiddle illustrating how to set up collections within the same SortableContainer:
https://jsfiddle.net/y89ayoLb/1/

**Comment by rvlewerissa** [comment]
@clauderic  Hi thanks for the help!

**Comment by thebarty** [comment]
@clauderic please make the demo public! Would be really helpful especially when it comes to css
