### ISSUE TITLE
Selected Element getting disappeared

### ISSUE THREAD

**Issue by Miteshdv** [clauderic/react-sortable-hoc#87]
Hi ,
 Whenever i try drag an element the element disappears and after drag finish the element appears.
Please help me. Component is excellent and perfect

Thanks

**Comment by Miteshdv** [comment]
Ok the issue is my Sortable component is inside react-boostrap Modal component.
The dragged component is behind the Popup,
Can you please help me

**Comment by clauderic** [comment]
You can add the `helperClass` prop to your enhanced `SortableContainer` component to style the helper and give it a higher [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) value.

For example:

```jsx
...
render() {
 return (
   < SortableList helperClass='sortableHelper' />
  )
}
```

And then in your css:
```css
.sortableHelper {
   z-index: 10;
}
```

**Comment by Miteshdv** [comment]
I did the same its not working :(

**Comment by clauderic** [comment]
You'll need to adjust the z-index to your specific use case. If in doubt, just try incrementing the value until it starts working (for instance, try `z-index: 9999`)

**Comment by Miteshdv** [comment]
Hmm Thanks for reply , its still not working .  i have one question , the dragged mini opaque element that appear . Is it part of SortableList ? or it is is also a some popup? . because i am suspicious that react-bootstrap popup is making it self at that highest z order. But i have no way to debug

**Comment by Miteshdv** [comment]
Ok

 <SortableItem key={`item-${index}`} index={index} value={fieldName} style = {{zIndex: 100000}}/>

This worked can u please tell me why this worked and it didnt work whne applying css to sortableList

**Comment by Miteshdv** [comment]
"<SortableItem key={`item-${index}`} index={index} value={fieldName} style = {{zIndex: 100000}}/>"

**Comment by Miteshdv** [comment]
Ok This worked \<SortableItem key={`item-${index}`} index={index} value={fieldName} style = {{zIndex: 100000}}/>
Can u please tell me why the above mentioned way worked and sortableHelper class on sortbale list didnt ?

**Comment by clauderic** [comment]
The above applies the style directly on the element, which then gets cloned and appended to the `document.body` element when you start sorting (this is the sortable helper). 

The above mentioned solution instead adds a class of your choice to the helper when it is cloned. 

Both should work, I'd need to diagnose why the first option isn't working for you.

**Comment by Miteshdv** [comment]
https://github.com/Miteshdv/Form-Creator/blob/master/formElementsReorder/FormReOrderView.jsx  you can go to Miteshdv/form-creator on github download project npm install nd check it pls

**Comment by microdou** [comment]
@Miteshdv @clauderic I had the same problem with `Popover` in `react-bootstrap`. `z-index` has to be marked with `!important` to override bootstrap styles.

```
.sortableHelper {
   z-index: 10000 !important;
}
```

**Comment by Sachem** [comment]
@Miteshdv as this element that you drag is appended at the end of the BODY, make sure you don't put the definition of .sortableHelper in the scope of some other CSS class (like you probably do with the styles for the elements) as it will simply not work.

**Comment by Pyot** [comment]
For me, it works when I add  to class to <li>:

```
const SortableItem = SortableElement(({value}) =>
  <li className="sortableHelper">{value}</li>
);
```
and CSS

```
.sortableHelper {
   z-index: 9999;
}
```

if a style of a draggable element does not satisfy you. Please make adjustment in .sortableHelper

**Comment by waynebloss** [comment]
Inside of a `material-ui` modal, this worked nicely:

```js
// file `ReorderThingsForm.styles.js`
import { makeStyles } from "@material-ui/core";

export const useStyles = makeStyles(
  theme => ({
    sorting: {
      zIndex: theme.zIndex.modal + 100,
    },
  }),
  {
    classNamePrefix: "ReorderThingsForm",
  },
);
```

```jsx
// file `ReorderThingsForm.jsx`
import ...;
import { useStyles } from "./ReorderThingsForm.styles";

const MySortableContainer = SortableContainer(...);

export function ReorderThingsForm() {
  const classes = useStyles();
  return (
    <...>
      <MySortableContainer helperClass={classes.sorting} />
    </...>
  );
}
```

**Comment by lichenbuliren** [comment]
![image](https://user-images.githubusercontent.com/8489343/76742420-07bbb780-67ac-11ea-8b80-f74d0041a93f.png)
if you use it in a modal component，then the `z-index` will not be used;
the correct way is to use `useRef` and `helperContainer`

``` js
const modalBody = useRef<any>(null);
...
<Modal.Body ref={modalBody} className={styles.sortModalBody}>
  <SortableList
    items={sorts}
    helperContainer={modalBody.current}
    onSortEnd={sortEnd => handleSortEnd(sortEnd)}
  />
</Modal.Body>
```

**Comment by amanbabbar-kipl** [comment]
> ![image](https://user-images.githubusercontent.com/8489343/76742420-07bbb780-67ac-11ea-8b80-f74d0041a93f.png)
> if you use it in a modal component，then the `z-index` will not be used;
> the correct way is to use `useRef` and `helperContainer`
> 
> ```js
> const modalBody = useRef<any>(null);
> ...
> <Modal.Body ref={modalBody} className={styles.sortModalBody}>
>   <SortableList
>     items={sorts}
>     helperContainer={modalBody.current}
>     onSortEnd={sortEnd => handleSortEnd(sortEnd)}
>   />
> </Modal.Body>
> ```

on first sort element still invisible and when i sort second time then it is working fine. can you help me out asap.

**Comment by denyomonogatari** [comment]
https://github.com/clauderic/react-sortable-hoc/issues/87#issuecomment-556145361
If you are using another component besides modal from Material-UI you can get the z-index by looking at https://material-ui.com/customization/z-index/

**Comment by notsegfault** [comment]
If you want to control the zIndex more dynamically:

use updateBeforeSortStart event:

`updateBeforeSortStart={(node) => {
        node.node.style.zIndex=9999;
      }}`

**Comment by kseikyo** [comment]
If anyone finds themselves using (maintaining a project with) react-select with react-sortable-hoc.

My solution was to style the class for the multiValue item, as of now 

```css
.css-1rhbuit-multiValue```

**Comment by sejaswant** [comment]
- Make z-index value higher like 10000

**Comment by NaveenYarram** [comment]
Hi , 
I'm using drag and drop with react-sortable-hoc when i use drag and drop functionality i'm able to do , but after i close the drog and drop container  pop up what ever the fields i dragged those are coming on top of the UI .

I have been trying to resolve it but i'm not able to .


Could you please help me with this ?
