### ISSUE TITLE
Not working on OS X, with 3 finger drag gesture. Have tested in Safari and Chrome.

### ISSUE THREAD

**Issue by nutrina** [clauderic/react-sortable-hoc#88]
Hello,

As the title says, this is not working on OS X, with the 3 finger drag gesture.
It works only if I click, keep the button pressed and drag ...

- Gerald

**Comment by clauderic** [comment]
This is kind of a hard one for me to debug, since I don't own a force-touch sensitive trackpad. I'd welcome a PR that would solve this though

**Comment by trepidacious** [comment]
I've tried this on a (non-force-touch) trackpad (built into Macbook Pro and an old external one), and it works fine for me. There's the usual long delay when releasing, but that seems to be part of OS X so not unexpected.

**Comment by mkozhukharenko** [comment]
It works for me on OS X EI Capitan (3 finger drag). I think it's a problem with macOS Sierra.

**Comment by trepidacious** [comment]
El Capitan for me here too, I like to leave it a while before I upgrade in case there is broken stuff like this :)

**Comment by clauderic** [comment]
I believe this may be related to #80. @nutrina, would you able to test @v0lkan's fix to see if it solves the issue on your end?

**Comment by levithomason** [comment]
@clauderic I also have MacOS Sierra issues with items not being draggable.  The solution in #80 solves it for me.  I left more details there.

**Comment by clauderic** [comment]
This has been fixed.
