### ISSUE TITLE
Cannot set property 'sortableInfo' of null

### ISSUE THREAD

**Issue by andregoncalvesdev** [clauderic/react-sortable-hoc#89]
I tried to run the basic example and the items get rendered, but no draggable behaviour.

I´m using jspm/systemjs and react. 

Error:

Uncaught (in promise) Error: (SystemJS) Cannot set property 'sortableInfo' of null(…)

**Comment by andregoncalvesdev** [comment]
![screen shot 2016-11-15 at 13 50 36](https://cloud.githubusercontent.com/assets/9271177/20308150/8892f7e2-ab3a-11e6-83a3-a0f1547660cb.png)

this line returns null

**Comment by clauderic** [comment]
Can you set up a test case reproducing this? I've personally never used jspm

**Comment by andregoncalvesdev** [comment]
I solved updating to jspm@beta :)
