### ISSUE TITLE
Drag with delay

### ISSUE THREAD

**Issue by andregoncalvesdev** [clauderic/react-sortable-hoc#90]
I can experience on this demo (http://clauderic.github.io/react-sortable-hoc/#/advanced/activate-onpress-200ms?_k=5s2lnu), aswell on my project, some issues with the pressDelay property.

I tried different values but sometimes the delayed click dont trigger the drag.

**Comment by clauderic** [comment]
Can you provide more details? 

If you move your mouse before the `pressDelay` timer expires, will be canceled, which is perhaps what you're experiencing?
