### ISSUE TITLE
Cloning repository on Node 7

### ISSUE THREAD

**Issue by brownieboy** [clauderic/react-sortable-hoc#91]
I cloned the repository and ran `npm install` on Node 7.0.0 and npm 4.0.1.  But when I tried to run the examples, they failed because react-dom had not been installed.

I fixed this by moving react and react-dom from peerDependences to dependencies in package.json and then ran `npm install` again.

**Comment by clauderic** [comment]
I believe this is pretty standard. It's up to the user to manage `react-dom` as a dependency, the same way it's up to the user to manage `react` as a dependency.

Otherwise, you can end up with multiple different packages relying on their own versions of react, which is obviously undesirable.

**Comment by clauderic** [comment]
I believe `react-dom` used to be included in devDependencies to account for this. Looks like it was removed accidentally.
