### ISSUE TITLE
Sorting between different lists

### ISSUE THREAD

**Issue by sbayd** [clauderic/react-sortable-hoc#93]
Hi, 

Is there a way to move and sort elements between different lists?

I have multiple SortableContainer and I'm trying to move & sort items between them.

**Comment by clauderic** [comment]
This kind of request comes up frequently (see #92, #3). As a matter of fact, the issue posted right before yours is the exact same request.

In short, no, this is currently not something that is supported, though it is on the roadmap. If this is something you would like to contribute to, please chime in on #3, all PRs are welcome :)
