### ISSUE TITLE
Dropping an item from a list to another causes JS error

### ISSUE THREAD

**Issue by arthursouviron** [clauderic/react-sortable-hoc#96]
On the demo website on this example : http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/multiple-lists?_k=ri8104

Dropping an item from the list 0 into the list 1 causes the following JS error
![screen shot 2016-11-28 at 14 21 03](https://cloud.githubusercontent.com/assets/5681289/20658208/24aa7fa2-b576-11e6-8d66-6198e6599dce.png)

Using Chrome V54

**Comment by clauderic** [comment]
Good catch, thanks! 😅 It was a silly typo in the demo code
