### ISSUE TITLE
HOCs should consume props they use

### ISSUE THREAD

**Issue by frontendphil** [clauderic/react-sortable-hoc#98]
The HOCs should consume the props they use internally and not hand them down to the wrapped components. Currently I need to sort out all internal props so that they do not end up as props on the elements I'm rendering.

**Comment by clauderic** [comment]
Yeah, this has been discussed already in #95 and should be resolved soon. If you feel like getting your hands dirty, all PRs are welcome!

**Comment by clauderic** [comment]
This was addressed in #100, thank you!

**Comment by derwaldgeist** [comment]
Hm, I don't think that consuming the `index` was a good idea. Knowing the index of the element in the list is important for a lot of use-cases.
