### ISSUE TITLE
sorting won't work in IE9 when using helperClass 

### ISSUE THREAD

**Issue by silentmaker** [clauderic/react-sortable-hoc#99]
classList property is not supported by IE9 therefore sorting won't work in IE9 when using helperClass , the clone element sort of fixed on the window
![image](https://cloud.githubusercontent.com/assets/5415519/20744562/a392a91e-b717-11e6-91cb-745e2863b26d.png)

**Comment by clauderic** [comment]
This library relies heavily on CSS transforms and CSS animations, both of which work very poorly in IE9. As such, IE9 support hasn't been a priority such far, but if you feel like taking a stab at it, I'd be happy to review a PR for this.
